# Decision Tree Regression

Decision Tree Regression is a **Supervised Machine Learning Regression Algorithm**.

It is used when the target variable is **continuous (numerical)**.

Examples:

- House Price Prediction
- Salary Prediction
- Temperature Prediction
- Stock Price Estimation
- Sales Forecasting

Unlike Decision Tree Classifier, it predicts a **number**, not a class.

---

# Intuition

Suppose we want to predict **House Price**.

| House Size (sqft) | Price ($) |
|-------------------|-----------|
| 800 | 120,000 |
| 1000 | 150,000 |
| 1200 | 180,000 |
| 1800 | 300,000 |
| 2200 | 370,000 |

The tree keeps asking questions like:

```
House Size ≤ 1500?

        Yes                No
         │                  │
Average = $150,000    Average = $335,000
```

Instead of predicting a class,

it predicts the **average value of the samples in the leaf node**.

---

# How Does It Work?

```
Dataset
    │
    ▼
Find Best Split
    │
    ▼
Split Dataset
    │
    ▼
Repeat Until Stopping Condition
    │
    ▼
Leaf Node
    │
    ▼
Predict Average Target Value
```

---

# Example

Training Data

| Size | Price |
|------|-------|
| 900 | 120k |
| 1000 | 140k |
| 1100 | 150k |
| 2000 | 320k |
| 2200 | 350k |

Possible Tree

```
          Size ≤ 1500?

          Yes        No
           │          │
       Avg = 137k   Avg = 335k
```

Suppose a new house has

```
Size = 1050
```

It goes to

```
Left Leaf
```

Prediction

```
$137,000
```

---

# Key Difference

## Classification Tree

```
Leaf Node

↓

Class

Yes

No

Spam

Dog
```

---

## Regression Tree

```
Leaf Node

↓

Number

150,000

78.5

42.7
```

---

# How Does It Choose the Best Split?

Decision Tree Regression does **NOT** use

- Gini Impurity ❌
- Entropy ❌
- Information Gain ❌

Instead,

it uses **Variance Reduction**.

---

# What is Variance?

Variance measures **how spread out the target values are**.

If all values are close together,

↓

Low Variance.

If values are very different,

↓

High Variance.

Example

Low Variance

```
100

102

101

99
```

High Variance

```
50

200

400

900
```

---

# Goal of Decision Tree Regression

The tree tries to create child nodes where the target values are as similar as possible.

```
Mixed Values

↓

Split

↓

More Similar Values
```

---

# Variance Reduction

A good split should **reduce the variance**.

Formula

$$
\text{Variance Reduction}
=
\text{Parent Variance}
-
\text{Weighted Child Variance}
$$

The split with the **highest Variance Reduction** is chosen.

---

# Simple Example

Suppose we have house prices

```
100

110

120

500

520

540
```

Parent Node

```
High Variance
```

Split

```
Size ≤ 1500
```

Left Node

```
100

110

120
```

Right Node

```
500

520

540
```

Now each child node contains similar values.

```
Parent Variance

High
```

↓

```
Children Variance

Low
```

↓

```
Large Variance Reduction
```

Therefore,

this is a **good split**.

---

# Prediction

Suppose a leaf node contains

```
200

210

220

230
```

Prediction

```
Mean

=

(200 + 210 + 220 + 230) / 4

=

215
```

Every new sample reaching this leaf is predicted as

```
215
```

---

# Hyperparameters

## max_depth

Maximum depth of the tree.

```python
max_depth=5
```

---

## min_samples_split

Minimum samples required before splitting.

```python
min_samples_split=5
```

---

## min_samples_leaf

Minimum samples required in each leaf.

```python
min_samples_leaf=2
```

---

## max_leaf_nodes

Maximum number of leaf nodes.

```python
max_leaf_nodes=20
```

---

## random_state

Ensures reproducible results.

```python
random_state=42
```

---

# Scikit-Learn Syntax

```python
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
```

---

# Hyperparameter Tuning

```python
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

params = {
    "max_depth": [3, 5, 7, 10],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5]
}

grid = GridSearchCV(
    DecisionTreeRegressor(random_state=42),
    params,
    cv=5,
    scoring="neg_mean_squared_error"
)

grid.fit(X_train, y_train)

print(grid.best_params_)
```

---

# Advantages

✅ Easy to understand

✅ Handles non-linear relationships

✅ No feature scaling required

✅ Works with numerical and categorical features

---

# Disadvantages

❌ Easily overfits

❌ Sensitive to noisy data

❌ Produces step-like predictions instead of smooth curves

---

# Decision Tree Classifier vs Regressor

| Decision Tree Classifier | Decision Tree Regressor |
|--------------------------|-------------------------|
| Predicts a class | Predicts a number |
| Uses Gini or Entropy | Uses Variance Reduction |
| Output = Category | Output = Continuous Value |

---

# Rule of Thumb

```
Target Variable

↓

Category?

↓

DecisionTreeClassifier
```

```
Target Variable

↓

Number?

↓

DecisionTreeRegressor
```

---

# One-Line Definition

> **Decision Tree Regression is a supervised learning algorithm that predicts continuous values by recursively splitting the data into groups that minimize variance, with each leaf node predicting the average target value of the samples it contains.**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
from sklearn.datasets import load_diabetes

In [5]:
dataset = load_diabetes()

In [6]:
dataset

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [8]:
dataset["DESCR"]

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n'

In [9]:
dataset.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

___
# X and Y split

In [11]:
X = pd.DataFrame(dataset["data"], columns = dataset.feature_names)
y = pd.Series(dataset['target'])

In [12]:
X

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

___
# Train test split

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [14]:
X_train.corr()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
age,1.000000,0.159513,0.180804,0.324133,0.262160,0.199716,-0.023058,0.165480,0.266254,0.266706
sex,0.159513,1.000000,0.045831,0.180247,0.017967,0.110442,-0.338820,0.308991,0.105984,0.159663
bmi,0.180804,0.045831,1.000000,0.375038,0.255045,0.257140,-0.360168,0.428866,0.450936,0.389013
bp,0.324133,0.180247,0.375038,1.000000,0.242522,0.161199,-0.107979,0.208703,0.365678,0.375972
s1,0.262160,0.017967,0.255045,0.242522,1.000000,0.892852,0.042951,0.555728,0.520963,0.308419
s2,0.199716,0.110442,0.257140,0.161199,0.892852,1.000000,-0.194325,0.656085,0.298622,0.272405
s3,-0.023058,-0.338820,-0.360168,-0.107979,0.042951,-0.194325,1.000000,-0.735179,-0.379108,-0.283662
s4,0.165480,0.308991,0.428866,0.208703,0.555728,0.656085,-0.735179,1.000000,0.615701,0.419010
s5,0.266254,0.105984,0.450936,0.365678,0.520963,0.298622,-0.379108,0.615701,1.000000,0.456972
s6,0.266706,0.159663,0.389013,0.375972,0.308419,0.272405,-0.283662,0.419010,0.456972,1.000000

# Model Traiing

In [15]:
from sklearn.tree import DecisionTreeRegressor 

model = DecisionTreeRegressor()

model.fit(X_train, y_train)

DecisionTreeRegressor()

In [16]:
model.predict(X_train)

array([166., 189., 173., 220., 206.,  97.,  60.,  61., 242., 121., 128.,
       104., 265., 132., 283., 174., 129., 257., 137.,  63.,  93., 232.,
       208., 261., 179., 258., 262.,  51., 237.,  71., 139., 268.,  69.,
       317., 249., 154., 192., 116.,  81., 122., 259., 191., 292.,  55.,
       107., 210.,  91., 253.,  85., 252.,  59.,  78., 200.,  78., 245.,
       175.,  42., 127.,  53.,  94., 104., 199., 265., 281., 248., 257.,
       215., 303., 170.,  59., 277., 209., 138., 198., 124.,  96., 288.,
       225., 265., 101.,  55., 198.,  51., 252.,  64., 220., 131., 212.,
       142., 103., 155., 121.,  86., 111.,  65., 131.,  51., 128., 141.,
        48., 109., 178.,  88.,  84., 216., 150.,  60.,  96., 190.,  74.,
       279., 182., 160., 245., 276., 174., 180., 150., 196., 138.,  97.,
       246., 321., 308., 109.,  69., 182., 258., 161., 178., 214.,  45.,
       150., 160.,  55., 197., 185., 268., 310., 123.,  68.,  72., 185.,
       144., 147., 168., 178., 246., 151., 127.,  83., 332., 152., 109.,
        90.,  66., 214.,  85., 129.,  89., 259., 229., 200.,  77.,  54.,
        31., 109., 206., 144., 118.,  83., 242., 259.,  72., 163., 181.,
       141.,  71., 137., 195., 179., 102., 131.,  47., 235.,  77., 198.,
        93., 162., 225., 275., 183., 306.,  81.,  55., 146., 196., 230.,
       310.,  40., 135., 346.,  43., 128.,  77., 235.,  49.,  74.,  92.,
        84., 263., 144., 142., 341., 115., 158., 273.,  85.,  88., 220.,
        39.,  80., 172., 217., 336.,  52., 272., 115., 110., 131.,  71.,
       275., 118.,  25., 100., 281., 221., 248., 200., 132.,  91.,  67.,
       202.,  73.,  85., 275., 243.,  66., 293., 236., 243.,  87.,  39.,
       217.,  92., 296., 292., 142.,  50.,  53., 104.,  75., 120., 142.,
       143.,  99.,  65., 116., 233., 164.,  95.,  59., 139., 145., 177.,
       185.,  97.,  42., 201., 241.,  70.,  78.,  49., 103.,  44., 111.,
       191.,  47., 182.,  58., 155., 151.,  79., 104., 143., 152., 170.,
        75., 200., 124.,  91.,  49., 163.,  53., 283., 178., 219., 200.,
       113., 113.,  63., 114., 126., 274.,  88., 311.,  83.,  71., 134.,
       244.,  65., 173.,  57.,  68., 141., 270., 134., 202., 148.,  64.,
       302.])

```
You can Hyper Paremters Tune it using Random Search CV or Grid Search CV