In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1790237209.955256   11463 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1790237211.447845   11463 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1790237215.007588   11463 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

___
# Load Dataset

In [2]:
df = pd.read_csv("WELFake_Dataset.csv")

In [3]:
df

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...,...
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [4]:
# Drop Null Values
df = df.dropna(subset=["text", "label"])

In [5]:
# Combine Ttle + text 

df["content"] = df["title"] + df["text"]

/tmp/ipykernel_11463/2881946390.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["content"] = df["title"] + df["text"]

In [6]:
df

,Unnamed: 0,title,text,label,content
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1,1,NaN,Did they post their votes for Hillary already?,1,NaN
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,"Bobby Jindal, raised Hindu, uses story of Chri..."
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,SATAN 2: Russia unvelis an image of its terrif...
...,...,...,...,...,...
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0,Russians steal research on Trump in hack of U....
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1,WATCH: Giuliani Demands That Democrats Apolog...
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0,Migrants Refuse To Leave Train At Refugee Camp...
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0,Trump tussle gives unpopular Mexican leader mu...
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1,Goldman Sachs Endorses Hillary Clinton For Pre...

___
# data Preprocessing
___

In [7]:
# Drop unncessary Cols 
df = df.drop(columns=['Unnamed: 0', 'title', 'text'])

In [8]:
# Remove rows where content is missing
df = df.dropna(subset=["content"])

# Make sure every remaining value is a string
df["content"] = df["content"].astype(str)

In [9]:
print(df["content"].isna().sum())
print(df["content"].map(type).value_counts())

0
content
<class 'str'>    71537
Name: count, dtype: int64

In [10]:
df

       label                                            content
0          1  LAW ENFORCEMENT ON HIGH ALERT Following Threat...
2          1  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3          0  Bobby Jindal, raised Hindu, uses story of Chri...
4          1  SATAN 2: Russia unvelis an image of its terrif...
5          1  About Time! Christian Group Sues Amazon and SP...
...      ...                                                ...
72129      0  Russians steal research on Trump in hack of U....
72130      1   WATCH: Giuliani Demands That Democrats Apolog...
72131      0  Migrants Refuse To Leave Train At Refugee Camp...
72132      0  Trump tussle gives unpopular Mexican leader mu...
72133      1  Goldman Sachs Endorses Hillary Clinton For Pre...

[71537 rows x 2 columns]

___
# Tokenizer
___

In [11]:
# tokenize the Text 

tokenizer = Tokenizer(num_words=20000)
# Learn vocabulary from the text
# fit_on_texts() expects a list of strings
tokenizer.fit_on_texts(df["content"]) # learns Vocablary from the content

In [12]:
total_words = len(tokenizer.word_index) + 1  # 1 as 1 index is reserved for paddng

In [13]:
total_words

362179

In [14]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'of': 3,
 'and': 4,
 'a': 5,
 'in': 6,
 'that': 7,
 'is': 8,
 'for': 9,
 'on': 10,
 'it': 11,
 'he': 12,
 'with': 13,
 's': 14,
 'was': 15,
 'as': 16,
 'said': 17,
 'by': 18,
 'trump': 19,
 '”': 20,
 'his': 21,
 'be': 22,
 'have': 23,
 'has': 24,
 'not': 25,
 'at': 26,
 'are': 27,
 'from': 28,
 'this': 29,
 'an': 30,
 'who': 31,
 'they': 32,
 'but': 33,
 'i': 34,
 'we': 35,
 'you': 36,
 'about': 37,
 'will': 38,
 'their': 39,
 'would': 40,
 'had': 41,
 'or': 42,
 'been': 43,
 'more': 44,
 'president': 45,
 'were': 46,
 'people': 47,
 'one': 48,
 'her': 49,
 'she': 50,
 'which': 51,
 'all': 52,
 'new': 53,
 'u': 54,
 'if': 55,
 'what': 56,
 'out': 57,
 'after': 58,
 'mr': 59,
 'when': 60,
 'up': 61,
 'clinton': 62,
 'its': 63,
 'there': 64,
 'so': 65,
 'also': 66,
 'no': 67,
 'state': 68,
 'can': 69,
 'over': 70,
 'our': 71,
 'than': 72,
 'like': 73,
 'other': 74,
 '—': 75,
 'just': 76,
 'some': 77,
 'into': 78,
 'him': 79,
 'them': 80,
 'do': 81,
 't': 82,
 'could': 83,
 'states': 84,
 'time': 85,
 'government': 86,
 'obama': 87,
 'now': 88,
 'house': 89,
 'us': 90,
 'because': 91,
 'two': 92,
 'year': 93,
 'how': 94,
 'against': 95,
 'donald': 96,
 'even': 97,
 'campaign': 98,
 'only': 99,
 'first': 100,
 'united': 101,
 'many': 102,
 'any': 103,
 'last': 104,
 'news': 105,
 'election': 106,
 'white': 107,
 'republican': 108,
 'hillary': 109,
 'years': 110,
 'most': 111,
 'american': 112,
 'told': 113,
 'while': 114,
 'being': 115,
 'those': 116,
 'before': 117,
 'did': 118,
 'these': 119,
 'party': 120,
 'get': 121,
 'may': 122,
 'should': 123,
 'where': 124,
 'your': 125,
 'country': 126,
 'media': 127,
 'my': 128,
 'political': 129,
 'during': 130,
 'then': 131,
 'make': 132,
 'going': 133,
 'made': 134,
 'world': 135,
 'former': 136,
 'say': 137,
 'reuters': 138,
 'back': 139,
 'national': 140,
 'way': 141,
 'very': 142,
 'police': 143,
 'right': 144,
 'law': 145,
 'think': 146,
 'know': 147,
 'since': 148,
 'percent': 149,
 'here': 150,
 'down': 151,
 'according': 152,
 'security': 153,
 'day': 154,
 'trump’s': 155,
 'well': 156,
 'under': 157,
 'much': 158,
 'york': 159,
 'russia': 160,
 'take': 161,
 '2016': 162,
 'public': 163,
 'such': 164,
 'see': 165,
 'between': 166,
 'presidential': 167,
 'war': 168,
 'called': 169,
 'support': 170,
 'still': 171,
 'want': 172,
 'video': 173,
 'me': 174,
 'including': 175,
 'court': 176,
 'through': 177,
 'america': 178,
 'twitter': 179,
 '000': 180,
 'vote': 181,
 'democratic': 182,
 'officials': 183,
 'says': 184,
 'week': 185,
 'another': 186,
 '1': 187,
 'republicans': 188,
 'bill': 189,
 'million': 190,
 'military': 191,
 'work': 192,
 'group': 193,
 'both': 194,
 'federal': 195,
 'off': 196,
 'administration': 197,
 'own': 198,
 'go': 199,
 'it’s': 200,
 'part': 201,
 'washington': 202,
 'long': 203,
 'office': 204,
 'foreign': 205,
 'department': 206,
 'same': 207,
 'north': 208,
 'russian': 209,
 'women': 210,
 'why': 211,
 'three': 212,
 'policy': 213,
 'times': 214,
 'never': 215,
 'around': 216,
 'city': 217,
 'americans': 218,
 'senate': 219,
 'need': 220,
 '“the': 221,
 'black': 222,
 'good': 223,
 'saying': 224,
 'next': 225,
 'case': 226,
 'use': 227,
 'statement': 228,
 'left': 229,
 'help': 230,
 'every': 231,
 'does': 232,
 'power': 233,
 'democrats': 234,
 'man': 235,
 '–': 236,
 '“i': 237,
 'show': 238,
 'come': 239,
 'asked': 240,
 'general': 241,
 'whether': 242,
 'congress': 243,
 'used': 244,
 'money': 245,
 '2': 246,
 'too': 247,
 'tax': 248,
 'end': 249,
 'really': 250,
 'secretary': 251,
 'rights': 252,
 'change': 253,
 'without': 254,
 'voters': 255,
 'far': 256,
 'don’t': 257,
 'fbi': 258,
 'report': 259,
 'china': 260,
 'tuesday': 261,
 'life': 262,
 'put': 263,
 'health': 264,
 'deal': 265,
 'might': 266,
 'order': 267,
 'com': 268,
 'via': 269,
 'days': 270,
 'family': 271,
 're': 272,
 'members': 273,
 'found': 274,
 'candidate': 275,
 'fact': 276,
 'took': 277,
 'friday': 278,
 'information': 279,
 'syria': 280,
 'among': 281,
 'home': 282,
 'wednesday': 283,
 'something': 284,
 'already': 285,
 'again': 286,
 'top': 287,
 '10': 288,
 'thursday': 289,
 'place': 290,
 'investigation': 291,
 'old': 292,
 'attack': 293,
 'things': 294,
 'system': 295,
 'business': 296,
 'several': 297,
 'post': 298,
 'official': 299,
 'reported': 300,
 'high': 301,
 'committee': 302,
 'justice': 303,
 'minister': 304,
 'few': 305,
 'monday': 306,
 'however': 307,
 'least': 308,
 'month': 309,
 'though': 310,
 '5': 311,
 '3': 312,
 'point': 313,
 'yet': 314,
 'ms': 315,
 'countries': 316,
 'recent': 317,
 'children': 318,
 'great': 319,
 'believe': 320,
 'director': 321,
 'social': 322,
 'later': 323,
 'came': 324,
 'john': 325,
 'leader': 326,
 'free': 327,
 'big': 328,
 'got': 329,
 'real': 330,
 'must': 331,
 'little': 332,
 'look': 333,
 'likely': 334,
 'become': 335,
 'international': 336,
 'chief': 337,
 'today': 338,
 'nuclear': 339,
 'story': 340,
 'south': 341,
 'control': 342,
 'months': 343,
 'number': 344,
 'image': 345,
 'four': 346,
 'added': 347,
 'iran': 348,
 'decision': 349,
 'clear': 350,
 'senator': 351,
 'watch': 352,
 'plan': 353,
 'school': 354,
 'interview': 355,
 'intelligence': 356,
 'call': 357,
 'past': 358,
 'leaders': 359,
 'away': 360,
 'working': 361,
 'meeting': 362,
 'major': 363,
 'making': 364,
 'm': 365,
 'groups': 366,
 'speech': 367,
 'anti': 368,
 'once': 369,
 'email': 370,
 'sanders': 371,
 'trade': 372,
 'until': 373,
 'economic': 374,
 'seen': 375,
 'win': 376,
 'keep': 377,
 'press': 378,
 'known': 379,
 'ever': 380,
 'set': 381,
 'better': 382,
 'history': 383,
 'immigration': 384,
 'act': 385,
 '4': 386,
 'thing': 387,
 'company': 388,
 'others': 389,
 'issue': 390,
 'night': 391,
 'wrote': 392,
 'trying': 393,
 'less': 394,
 'care': 395,
 'don': 396,
 'actually': 397,
 'human': 398,
 'islamic': 399,
 'lot': 400,
 'based': 401,
 'best': 402,
 'run': 403,
 'supporters': 404,
 'doing': 405,
 'went': 406,
 'give': 407,
 'al': 408,
 'matter': 409,
 'conservative': 410,
 'men': 411,
 'executive': 412,
 'program': 413,
 'move': 414,
 'university': 415,
 'second': 416,
 'across': 417,
 'enough': 418,
 'force': 419,
 'forces': 420,
 'team': 421,
 'nothing': 422,
 '2015': 423,
 'ago': 424,
 'killed': 425,
 'given': 426,
 'important': 427,
 'attacks': 428,
 'd': 429,
 'korea': 430,
 'find': 431,
 'each': 432,
 'himself': 433,
 'question': 434,
 'stop': 435,
 'early': 436,
 '20': 437,
 'won': 438,
 'november': 439,
 '“we': 440,
 'nation': 441,
 'billion': 442,
 'fox': 443,
 'defense': 444,
 'de': 445,
 'person': 446,
 'evidence': 447,
 'muslim': 448,
 'led': 449,
 'job': 450,
 'local': 451,
 'course': 452,
 '8': 453,
 'issues': 454,
 'taking': 455,
 'border': 456,
 'emails': 457,
 'possible': 458,
 'wall': 459,
 'race': 460,
 'private': 461,
 'agency': 462,
 'reports': 463,
 'sunday': 464,
 'done': 465,
 'face': 466,
 'having': 467,
 'legal': 468,
 'woman': 469,
 'n': 470,
 'center': 471,
 'pay': 472,
 'open': 473,
 'five': 474,
 'head': 475,
 'october': 476,
 'let': 477,
 'debate': 478,
 'earlier': 479,
 'process': 480,
 'continue': 481,
 'close': 482,
 'march': 483,
 'behind': 484,
 'violence': 485,
 'held': 486,
 'instead': 487,
 'along': 488,
 'companies': 489,
 'full': 490,
 'different': 491,
 'hard': 492,
 'using': 493,
 '6': 494,
 'community': 495,
 'member': 496,
 'often': 497,
 'financial': 498,
 'facebook': 499,
 'taken': 500,
 'european': 501,
 '11': 502,
 'able': 503,
 'death': 504,
 'name': 505,
 'senior': 506,
 'comment': 507,
 'released': 508,
 'action': 509,
 'live': 510,
 'future': 511,
 'anything': 512,
 'fight': 513,
 'global': 514,
 'always': 515,
 'read': 516,
 'cruz': 517,
 '2017': 518,
 'within': 519,
 'gop': 520,
 'nominee': 521,
 'air': 522,
 'majority': 523,
 'featured': 524,
 'following': 525,
 'source': 526,
 'lead': 527,
 'young': 528,
 'despite': 529,
 'gun': 530,
 'barack': 531,
 'cnn': 532,
 'illegal': 533,
 'iraq': 534,
 'syrian': 535,
 'line': 536,
 'lives': 537,
 'union': 538,
 'am': 539,
 '9': 540,
 'judge': 541,
 'water': 542,
 '30': 543,
 'began': 544,
 'that’s': 545,
 '7': 546,
 'middle': 547,
 'role': 548,
 'nations': 549,
 'democrat': 550,
 'comes': 551,
 'street': 552,
 'anyone': 553,
 'coming': 554,
 'bush': 555,
 'politics': 556,
 '2014': 557,
 'someone': 558,
 'nearly': 559,
 'problem': 560,
 'almost': 561,
 'putin': 562,
 'wants': 563,
 'sure': 564,
 'attorney': 565,
 'reporters': 566,
 '15': 567,
 'getting': 568,
 'january': 569,
 'expected': 570,
 'economy': 571,
 'plans': 572,
 'further': 573,
 'whose': 574,
 'texas': 575,
 'weeks': 576,
 'jobs': 577,
 'response': 578,
 'service': 579,
 'voting': 580,
 'small': 581,
 'means': 582,
 'israel': 583,
 'kind': 584,
 'special': 585,
 'saudi': 586,
 'running': 587,
 'large': 588,
 'start': 589,
 'supreme': 590,
 'candidates': 591,
 'talk': 592,
 'comey': 593,
 'together': 594,
 'pic': 595,
 'current': 596,
 'thought': 597,
 'outside': 598,
 'comments': 599,
 'co': 600,
 'spokesman': 601,
 'clinton’s': 602,
 'east': 603,
 'governor': 604,
 'opposition': 605,
 'staff': 606,
 'reason': 607,
 'rather': 608,
 'questions': 609,
 'prime': 610,
 'officers': 611,
 'side': 612,
 'tell': 613,
 'c': 614,
 'efforts': 615,
 'lost': 616,
 'late': 617,
 'students': 618,
 'front': 619,
 'recently': 620,
 'wanted': 621,
 'crisis': 622,
 'july': 623,
 'civil': 624,
 'article': 625,
 'leave': 626,
 'announced': 627,
 'bad': 628,
 'thousands': 629,
 'term': 630,
 'makes': 631,
 'paul': 632,
 'sent': 633,
 'effort': 634,
 'six': 635,
 'daily': 636,
 'morning': 637,
 'workers': 638,
 'themselves': 639,
 'idea': 640,
 'weapons': 641,
 'conference': 642,
 'event': 643,
 'words': 644,
 'california': 645,
 'everyone': 646,
 'june': 647,
 'saturday': 648,
 'votes': 649,
 'west': 650,
 'feel': 651,
 'elections': 652,
 'agreement': 653,
 'list': 654,
 'data': 655,
 'eu': 656,
 'letter': 657,
 'needs': 658,
 'near': 659,
 'access': 660,
 'florida': 661,
 'everything': 662,
 'ryan': 663,
 'criminal': 664,
 'market': 665,
 'j': 666,
 'budget': 667,
 'rules': 668,
 'try': 669,
 'policies': 670,
 'hope': 671,
 'strong': 672,
 '12': 673,
 'position': 674,
 '100': 675,
 'citizens': 676,
 'foundation': 677,
 'true': 678,
 'threat': 679,
 'looking': 680,
 'message': 681,
 'millions': 682,
 'area': 683,
 'claims': 684,
 'hours': 685,
 'europe': 686,
 'george': 687,
 'half': 688,
 'climate': 689,
 'calls': 690,
 'calling': 691,
 '2012': 692,
 'central': 693,
 'latest': 694,
 'especially': 695,
 'mexico': 696,
 'cannot': 697,
 'accused': 698,
 'food': 699,
 'energy': 700,
 'council': 701,
 'gave': 702,
 'isis': 703,
 'organization': 704,
 'became': 705,
 'oil': 706,
 'level': 707,
 'received': 708,
 'western': 709,
 'refugees': 710,
 'talks': 711,
 'follow': 712,
 'either': 713,
 'ban': 714,
 'shows': 715,
 'lawmakers': 716,
 'college': 717,
 'love': 718,
 'seems': 719,
 'personal': 720,
 'chairman': 721,
 'army': 722,
 'region': 723,
 'interest': 724,
 'enforcement': 725,
 'hold': 726,
 'sanctions': 727,
 'third': 728,
 'entire': 729,
 'due': 730,
 'liberal': 731,
 'authorities': 732,
 'happened': 733,
 'legislation': 734,
 'turn': 735,
 'involved': 736,
 'example': 737,
 'key': 738,
 'tried': 739,
 'decades': 740,
 'allow': 741,
 'elected': 742,
 'bring': 743,
 'failed': 744,
 'bank': 745,
 'breitbart': 746,
 'although': 747,
 'stand': 748,
 'cases': 749,
 'speaking': 750,
 'chinese': 751,
 'i’m': 752,
 'movement': 753,
 'poll': 754,
 'started': 755,
 'class': 756,
 'dr': 757,
 'obamacare': 758,
 'room': 759,
 'probably': 760,
 'industry': 761,
 'fire': 762,
 'worked': 763,
 'victory': 764,
 'officer': 765,
 'share': 766,
 'immigrants': 767,
 'talking': 768,
 'peace': 769,
 'potential': 770,
 'record': 771,
 'turned': 772,
 'simply': 773,
 'freedom': 774,
 'book': 775,
 'rule': 776,
 'below': 777,
 'muslims': 778,
 'result': 779,
 'truth': 780,
 'toward': 781,
 'research': 782,
 'primary': 783,
 'showed': 784,
 'services': 785,
 'presidency': 786,
 'crime': 787,
 'james': 788,
 'sources': 789,
 'hand': 790,
 'shot': 791,
 'building': 792,
 'polls': 793,
 'didn’t': 794,
 'soon': 795,
 'situation': 796,
 'british': 797,
 'mrs': 798,
 '50': 799,
 'mean': 800,
 'congressional': 801,
 'laws': 802,
 'continued': 803,
 'allowed': 804,
 'visit': 805,
 'wife': 806,
 'release': 807,
 'capital': 808,
 'cut': 809,
 'published': 810,
 'friends': 811,
 'wrong': 812,
 'https': 813,
 'images': 814,
 'vice': 815,
 'provide': 816,
 'son': 817,
 'hit': 818,
 'britain': 819,
 'needed': 820,
 'april': 821,
 'longer': 822,
 'county': 823,
 '25': 824,
 'play': 825,
 'protect': 826,
 'met': 827,
 'father': 828,
 'saw': 829,
 'david': 830,
 'obama’s': 831,
 've': 832,
 'relations': 833,
 'points': 834,
 'terrorist': 835,
 'september': 836,
 'planned': 837,
 'itself': 838,
 'view': 839,
 'return': 840,
 'turkey': 841,
 'described': 842,
 'short': 843,
 'paid': 844,
 'fighting': 845,
 'claim': 846,
 'f': 847,
 'coalition': 848,
 'immediately': 849,
 'decided': 850,
 'non': 851,
 'rally': 852,
 'final': 853,
 'single': 854,
 'michael': 855,
 'include': 856,
 'host': 857,
 'ahead': 858,
 'e': 859,
 'whole': 860,
 'allies': 861,
 'sexual': 862,
 '2013': 863,
 'spending': 864,
 'results': 865,
 'forward': 866,
 'charges': 867,
 'living': 868,
 'didn': 869,
 'terrorism': 870,
 'serious': 871,
 'reality': 872,
 'parties': 873,
 'appeared': 874,
 'leading': 875,
 'spent': 876,
 'shooting': 877,
 'ruling': 878,
 '“it': 879,
 'tv': 880,
 'posted': 881,
 'cost': 882,
 'network': 883,
 'fear': 884,
 'actions': 885,
 'similar': 886,
 'families': 887,
 'moment': 888,
 'understand': 889,
 'else': 890,
 'address': 891,
 'brought': 892,
 'december': 893,
 'sign': 894,
 'step': 895,
 'doesn’t': 896,
 'documents': 897,
 'secret': 898,
 'concerns': 899,
 'ties': 900,
 'problems': 901,
 'goes': 902,
 'child': 903,
 'inside': 904,
 'board': 905,
 'district': 906,
 'low': 907,
 'game': 908,
 'funding': 909,
 'popular': 910,
 'education': 911,
 'february': 912,
 'meet': 913,
 'body': 914,
 'account': 915,
 'can’t': 916,
 'risk': 917,
 'perhaps': 918,
 'created': 919,
 'ground': 920,
 'nomination': 921,
 'pro': 922,
 'project': 923,
 'voted': 924,
 'doesn': 925,
 'increase': 926,
 'racist': 927,
 'biggest': 928,
 'he’s': 929,
 'bernie': 930,
 'insurance': 931,
 'century': 932,
 'germany': 933,
 'august': 934,
 'backed': 935,
 'conservatives': 936,
 'agencies': 937,
 'protesters': 938,
 'dollars': 939,
 'claimed': 940,
 'review': 941,
 'heard': 942,
 'happen': 943,
 'influence': 944,
 'medical': 945,
 'helped': 946,
 'related': 947,
 'sense': 948,
 'arrested': 949,
 'fake': 950,
 'land': 951,
 'la': 952,
 'ask': 953,
 'adding': 954,
 'phone': 955,
 '“': 956,
 'series': 957,
 'establishment': 958,
 'spoke': 959,
 'reform': 960,
 'cause': 961,
 'religious': 962,
 'p': 963,
 'society': 964,
 'main': 965,
 'b': 966,
 'website': 967,
 'leadership': 968,
 'hate': 969,
 'self': 970,
 'mother': 971,
 'convention': 972,
 'town': 973,
 'included': 974,
 'common': 975,
 'pressure': 976,
 'attention': 977,
 'areas': 978,
 'largest': 979,
 'standing': 980,
 'drug': 981,
 'speak': 982,
 'create': 983,
 'choice': 984,
 'study': 985,
 'mass': 986,
 'r': 987,
 'details': 988,
 'clearly': 989,
 'powerful': 990,
 'seven': 991,
 'total': 992,
 'online': 993,
 'travel': 994,
 'build': 995,
 'passed': 996,
 'mind': 997,
 'quickly': 998,
 'hands': 999,
 'dead': 1000,
 ...}

___
# Input Sequence
___

``` 
We are not dong the N-gram sequence like in GRU as its not Predictiing Words

In [15]:
sequences = tokenizer.texts_to_sequences(df["content"])

In [16]:
sequences

[[145,
  725,
  10,
  301,
  4233,
  525,
  1368,
  95,
  2572,
  4,
  3191,
  10,
  540,
  10010,
  4,
  1147,
  173,
  67,
  507,
  8,
  570,
  28,
  531,
  87,
  273,
  3,
  1,
  42,
  4,
  10010,
  3750,
  169,
  9,
  1,
  16230,
  4,
  5205,
  3,
  107,
  47,
  4,
  2572,
  32,
  3395,
  389,
  10,
  5,
  1120,
  238,
  261,
  391,
  2,
  735,
  1,
  7730,
  4,
  1466,
  107,
  47,
  4,
  2572,
  2,
  1313,
  5,
  681,
  37,
  1,
  1233,
  3,
  222,
  47,
  6,
  178,
  48,
  3,
  1,
  847,
  4914,
  8,
  169,
  11976,
  50,
  24,
  5,
  1120,
  3091,
  238,
  3458,
  28,
  575,
  169,
  11976,
  14,
  847,
  7473,
  1184,
  1120,
  238,
  5,
  12490,
  3,
  49,
  179,
  1001,
  26,
  540,
  4153,
  963,
  365,
  715,
  7,
  50,
  15,
  3310,
  404,
  2,
  357,
  88,
  2596,
  35,
  481,
  2,
  6387,
  1,
  8303,
  3,
  107,
  777,
  8,
  5,
  12490,
  179,
  1120,
  357,
  6368,
  1120,
  238,
  5957,
  26,
  288,
  3264,
  963,
  365,
  1096,
  1812,
  85,
  130,
  1,
  238,
  989,
  357,
  9,
  16230,
  4,
  1233,
  3,
  107,
  47,
  5,
  246,
  3721,
  2435,
  4004,
  28,
  1,
  1120,
  238,
  69,
  22,
  942,
  150,
  11,
  15,
  1199,
  2,
  746,
  575,
  18,
  558,
  31,
  40,
  73,
  2,
  22,
  2423,
  2,
  16,
  12,
  24,
  285,
  708,
  504,
  1368,
  16,
  5,
  779,
  3,
  13900,
  642,
  690,
  30,
  6361,
  222,
  235,
  17,
  60,
  116,
  971,
  847,
  27,
  18,
  639,
  7,
  14,
  60,
  60,
  35,
  123,
  589,
  847,
  7473,
  80,
  61,
  73,
  32,
  81,
  90,
  60,
  5,
  3895,
  3,
  80,
  15489,
  48,
  3,
  90,
  57,
  7,
  14,
  94,
  35,
  123,
  3199,
  61,
  12,
  17,
  961,
  35,
  285,
  3199,
  61,
  6,
  5660,
  2925,
  64,
  123,
  22,
  635,
  42,
  991,
  222,
  971,
  847,
  165,
  7,
  107,
  446,
  4,
  131,
  2265,
  39,
  4293,
  477,
  14,
  735,
  1,
  7907,
  32,
  14668,
  7,
  55,
  2572,
  755,
  1744,
  47,
  131,
  64,
  38,
  22,
  5,
  68,
  3,
  1584,
  12,
  9933,
  7,
  48,
  3,
  92,
  294,
  40,
  943,
  5,
  328,
  4293,
  987,
  14,
  168,
  42,
  15489,
  32,
  27,
  133,
  2,
  589,
  61,
  35,
  27,
  285,
  568,
  425,
  57,
  150,
  65,
  56,
  1,
  847,
  1792,
  35,
  329,
  2,
  1290,
  11976,
  83,
  22,
  942,
  224,
  16836,
  7,
  14,
  678,
  7,
  14,
  65,
  847,
  1172,
  678,
  12,
  17,
  35,
  220,
  2,
  735,
  1,
  7907,
  10,
  80,
  71,
  1424,
  27,
  568,
  791,
  57,
  150,
  2589,
  658,
  2,
  335,
  5,
  5640,
  10,
  39,
  612,
  12,
  17,
  2330,
  17342,
  82,
  151,
  9,
  7,
  14,
  82,
  42,
  1463,
  33,
  73,
  34,
  137,
  2330,
  24,
  5,
  491,
  674,
  3,
  168,
  12,
  803,
  91,
  32,
  396,
  82,
  407,
  5,
  847,
  1792,
  2925,
  12,
  17,
  286,
  35,
  266,
  16,
  156,
  13348,
  80,
  9,
  7,
  14,
  82,
  4,
  735,
  1,
  7907,
  10,
  119,
  470,
  12,
  17,
  7,
  141,
  35,
  69,
  589,
  73,
  35,
  17342,
  82,
  7,
  102,
  4245,
  4,
  64,
  69,
  22,
  44,
  10,
  39,
  612,
  487,
  3,
  7625,
  32,
  27,
  57,
  39,
  1233,
  222,
  47,
  222,
  537,
  396,
  82,
  409,
  7,
  14,
  56,
  116,
  971,
  847,
  65,
  35,
  329,
  2,
  132,
  11,
  409,
  2,
  80,
  431,
  5,
  971,
  847,
  7,
  8,
  1315,
  5030,
  21,
  4293,
  4,
  131,
  847,
  6,
  5645,
  79,
  28,
  5,
  4730,
  4749,
  161,
  5,
  1658,
  3,
  11,
  4,
  131,
  1313,
  11,
  2,
  1,
  971,
  847,
  35,
  76,
  220,
  48,
  737,
  4,
  131,
  47,
  38,
  589,
  29,
  38,
  735,
  1,
  7907,
  10,
  14,
  82,
  12,
  17,
  12,
  17,
  29,
  38,
  589,
  5,
  12049,
  151,
  1201,
  12,
  17,
  7,
  60,
  48,
  107,
  446,
  8,
  6855,
  4,
  131,
  32,
  27,
  76,
  4400,
  5205,
  7,
  38,
  589,
  1,
  12049,
  151,
  1201,
  12,
  803,
  222,
  47,
  27,
  223,
  26,
  1710,
  5883,
  12,
  17,
  7,
  15,
  94,
  2,
  121,
  1,
  4154,
  790,
  186,
  222,
  235,
  959,
  61,
  224,
  32,
  820,
  2,
  1466,
  2572,
  7,
  27,
  1233,
  90,
  1,
  100,
  222,
  2287,
  17,
  7,
  38,
  22,
  1,
  402,
  4841,
  144,
  64,
  746,
  575,
  1123,
  300,
  94,
  11976,
  15,
  2873,
  60,
  927,
  107,
  47,
  10308,
  4,
  8834,
  48,
  3,
  49,
  642,
  690,
  50,
  5575,
  508,
  1,
  955,
  344,
  3,
  48,
  3,
  1,
  1,
  2168,
  849,
  755,
  2648,
  2290,
  690,
  48,
  3,
  1,
  847,
  753,
  404,
  2102,
  113,
  5,
  2168,
  31,
  10308,
  39,
  1413,
  881,
  642,
  357,
  35,
  27,
  133,
  2,
  2060,
  4,
  6733,
  125,
  4207,
  806,
  4,
  125,
  847,
  7473,
  1505,
  3,
  6923,
  82,
  9625,
  11780,
  38,
  22,
  6855,
  28,
  5,
  4749,
  746,
  575,
  1123,
  8109,
  11976,
  26,
  5,
  11781,
  14539,
  1018,
  26,
  1,
  823,
  1810,
  6,
  575,
  124,
  50,
  17,
  52,
  107,
  47,
  123,
  22,
  425,
  50,
  113,
  1437,
  4,
  13074,
  36,
  165,
  29,
  4293,
  3126,
  10,
  128,
  475,
  7,
  582,
  34,
  539,
  48,
  3,
  116,
  44,
  2482,
  50,
  17,
  50,
  15,
  26,
  1,
  1018,
  91,
  119,
  971,
  847,
  3291,
  11781,
  14539,
  91,
  50,
  41,
  3126,
  73,
  174,
  222,
  8235,
  137,
  32,
  38,
  22,
  1327,
  1,
  6440,
  1605,
  7,
  27,
  397,
  1326,
  9,
  1,
  835,
  428,
  10,
  836,
  7908,
  3421,
  10,
  7,
  154,
  16,
  300,
  18,
  746,
  575,
  64,
  27,
  297,
  4488,
  4,
  179,
  10011,
  9,
  1,
  753,
  1043,
  3765,
  433,
  16,
  48,
  3,
  1,
  475,
  4914,
  12,
  17,
  6,
  5,
  1454,
  173,
  7,
  404,
  38,
  22,
  3953,
  39,
  7961,
  3,
  1,
  8303,
  3,
  39,
  13157,
  39,
  1252,
  107,
  5731,
  73,
  1,
  112,
  1390,
  1,
  797,
  1390,
  143,
  10243,
  4,
  7797,
  7731,
  6182,
  10058,
  42,
  881,
  36,
  247,
  69,
  230,
  5,
  528,
  1899,
  39,
  5,
  13,
  1,
  15709,
  3,
  6190,
  50,
  881,
  92,
  2470,
  48,
  7,
  1073,
  2,
  22,
  1622,
  4,
  5,
  1159,
  3,
  5,
  222,
  235,
  16562,
  39,
  7053,
  13,
  1,
  112,
  1390,
  9,
  729,
  340,
  746,
  105],
 [6377,
  831,
  565,
  241,
  184,
  111,
  5443,
  8615,
  46,
  49,
  282,
  68,
  3,
  208,
  1044,
  173,
  88,
  111,
  3,
  1,
  5017,
  2680,
  104,
  391,
  46,
  7942,
  39,
  1698,
  4,
  2719,
  144,
  2,
  2391,
  1018,
  6,
  267,
  2,
  1358,
  454,
  4,
  983,
  253,
  4115,
  2265,
  7822,
  1879,
  3820,
  6,
  5,
  13158],
 [9461,
  11741,
  1033,
  7776,
  2436,
  340,
  3,
  1196,
  10382,
  2,
  12619,
  7696,
  9,
  770,
  162,
  2154,
  1929,
  2001,
  13159,
  324,
  150,
  9,
  5,
  461,
  2165,
  278,
  391,
  2,
  1200,
  5,
  10382,
  340,
  3434,
  6,
  1,
  2934,
  3,
  167,
  556,
  94,
  3695,
  1695,
  9461,
  11741,
  3589,
  28,
  2,
  13850,
  5194,
  4,
  1644,
  705,
  56,
  12,
  690,
  30,
  2619,
  20,
  70,
  92,
  685,
  11741,
  3728,
  2888,
  768,
  13,
  5,
  1712,
  6,
  301,
  354,
  31,
  621,
  2,
  128,
  4181,
  20,
  2045,
  1,
  3862,
  6,
  5,
  9379,
  65,
  21,
  1089,
  40,
  25,
  165,
  79,
  4,
  2297,
  5,
  8616,
  114,
  1778,
  5,
  2012,
  130,
  21,
  506,
  93,
  7,
  9739,
  3008,
  10,
  1,
  2129,
  237,
  15,
  2183,
  4,
  2183,
  492,
  20,
  11741,
  113,
  1,
  13159,
  1007,
  15,
  1,
  817,
  3,
  1034,
  4,
  12,
  41,
  1040,
  9,
  71,
  10802,
  20,
  2541,
  13,
  1,
  1196,
  15866,
  31,
  527,
  6,
  1,
  436,
  167,
  5293,
  84,
  3,
  1402,
  4,
  341,
  1044,
  15,
  201,
  3,
  5,
  484,
  1,
  3973,
  634,
  18,
  1,
  3695,
  604,
  2,
  431,
  5,
  129,
  1109,
  7,
  83,
  230,
  12439,
  79,
  78,
  1,
  287,
  9523,
  3,
  108,
  591,
  1151,
  2,
  403,
  9,
  1,
  107,
  89,
  6,
  162,
  379,
  6,
  520,
  5686,
  1360,
  9,
  21,
  3,
  213,
  454,
  164,
  16,
  264,
  395,
  11741,
  5,
  7994,
  7193,
  4,
  4477,
  3,
  1,
  12620,
  16837,
  1537,
  415,
  232,
  25,
  23,
  30,
  2042,
  3024,
  3,
  2024,
  404,
  2,
  230,
  1696,
  9432,
  598,
  21,
  282,
  68,
  65,
  12,
  8,
  21,
  962,
  1082,
  6,
  5,
  141,
  7,
  24,
  2718,
  2,
  1701,
  2,
  1334,
  3,
  1,
  11262,
  3761,
  2155,
  3,
  962,
  936,
  102,
  3,
  1080,
  23,
  314,
  2,
  431,
  5,
  2400,
  281,
  1,
  188,
  15963,
  1,
  167,
  460,
  74,
  770,
  162,
  520,
  591,
  27,
  1,
  5609,
  1109,
  175,
  11977,
  3935,
  632,
  8324,
  4,
  1236,
  517,
  10586,
  4,
  2513,
  1695,
  1072,
  1133,
  33,
  70,
  1,
  1281,
  6,
  75,
  5,
  11863,
  3,
  5369,
  9,
  7696,
  16,
  1,
  282,
  3,
  2582,
  415,
  2836,
  6,
  1,
  4555,
  18,
  1,
  6159,
  4964,
  18414,
  75,
  11741,
  874,
  2,
  132,
  1489,
  6,
  1514,
  2,
  21,
  2165,
  13,
  1,
  13159,
  12,
  2120,
  5,
  156,
  708,
  2,
  891,
  2,
  1130,
  180,
  1196,
  936,
  2680,
  9,
  10414,
  3028,
  768,
  286,
  37,
  21,
  1770,
  114,
  56,
  12,
  17,
  15,
  45,
  831,
  771,
  3,
  2408,
  962,
  2582,
  1,
  13159,
  31,
  324,
  2,
  913,
  11741,
  17,
  21,
  8384,
  15118,
  3,
  21,
  4741,
  1928,
  57,
  1520,
  24,
  1,
  5363,
  4,
  12,
  24,
  56,
  11,
  1045,
  2,
  6282,
  80,
  20,
  17,
  8552,
  8883,
  3,
  4294,
  1682,
  1196,
  1067,
  6,
  1402,
  8883,
  946,
  136,
  3756,
  604,
  1072,
  4639,
  6,
  21,
  1291,
  1085,
  98,
  9,
  1575,
  6,
  1402,
  186,
  4639,
  1,
  6159,
  614,
  5949,
  6463,
  3,
  416,
  7235,
  1067,
  6,
  14,
  614,
  17,
  2260,
  2,
  1196,
  1616,
  4,
  21,
  6418,
  340,
  263,
  79,
  5695,
  5,
  13,
  4639,
  31,
  15,
  5,
  7235,
  12193,
  117,
  2193,
  556,
  1,
  3233,
  13159,
  4665,
  2,
  70,
  1,
  1281,
  26,
  1,
  4972,
  3,
  1,
  112,
  9626,
  923,
  5,
  156,
  1918,
  4227,
  193,
  7,
  8304,
  5609,
  2068,
  2,
  2922,
  6,
  1,
  6932,
  5490,
  13,
  1048,
  14601,
  121,
  57,
  1,
  181,
  7054,
  4,
  1131,
  2,
  2197,
  13159,
  6,
  7124,
  4331,
  6538,
  1,
  4931,
  1913,
  830,
  6097,
  24,
  1434,
  5,
  3912,
  883,
  6,
  1929,
  427,
  84,
  164,
  16,
  1402,
  3478,
  1323,
  4,
  341,
  1044,
  4,
  24,
  449,
  4977,
  2,
  583,
  13,
  632,
  4,
  389,
  1151,
  2,
  132,
  16231,
  13,
  5609,
  1366,
  1,
  193,
  7,
  6097,
  2705,
  974,
  96,
  5,
  1748,
  304,
  4,
  1913,
  3,
  1,
  112,
  271,
  1533,
  5,
  2028,
  5609,
  2024,
  193,
  7,
  24,
  944,
  177,
  63,
  883,
  3,
  44,
  72,
  7344,
  1196,
  1120,
  3948,
  111,
  3,
  1,
  13159,
  7,
  704,
  892,
  2,
  41,
  25,
  827,
  11741,
  33,
  32,
  17,
  12,
  2559,
  39,
  724,
  620,
  60,
  12,
  3163,
  866,
  2,
  1479,
  6924,
  9284,
  14183,
  3,
  1,
  1057,
  238,
  271,
  1747,
  5,
  2308,
  70,
  11395,
  1176,
  12,
  134,
  37,
  7640,
  6,
  30,
  355,
  13,
  19977,
  1957,
  1294,
  21,
  805,
  11741,
  2576,
  433,
  16,
  5,
  1378,
  1388,
  8501,
  130,
  21,
  10414,
  891,
  648,
  12,
  277,
  61,
  1,
  961,
  3,
  6667,
  2895,
  574,
  872,
  957,
  37,
  4,
  3094,
  11,
  866,
  20,
  15,
  3847,
  104,
  185,
  58,
  5,
  3252,
  1160,
  1319,
  7,
  32,
  41,
  6681,
  95,
  207,
  1050,
  1586,
  26,
  1,
  692,
  182,
  140,
  972,
  6,
  5443,
  1,
  10012,
  3187,
  4,
  830,
  194,
  2582,
  7456,
  2292,
  1,
  9186,
  4,
  5,
  461,
  4347,
  13,
  11741,
  31,
  169,
  1,
  509,
  95,
  80,
  16838,
  6313,
  3,
  9696,
  28,
  1,
  3703,
  761,
  20,
  1251,
  119,
  2264,
  41,
  6681,
  26,
  1,
  108,
  120,
  972,
  487,
  3,
  13027,
  39,
  238,
  40,
  760,
  23,
  426,
  80,
  5,
  1358,
  20,
  11741,
  17,
  16,
  1,
  2582,
  1093,
  8468,
  12,
  1909,
  1,
  15043,
  3913,
  7582,
  1907,
  3497,
  51,
  1760,
  5,
  468,
  1345,
  58,
  3139,
  2,
  816,
  1046,
  13,
  931,
  1214,
  9,
  18180,
  16,
  1501,
  157,
  1,
  1919,
  395,
  385,
  273,
  3,
  1,
  271,
  7,
  4326,
  15043,
  3913,
  31,
  23,
  335,
  6469,
  2,
  102,
  962,
  936,
  23,
  17,
  7,
  32,
  27,
  8796,
  1459,
  2,
  1,
  227,
  3,
  1021,
  3606,
  3,
  2110,
  342,
  4,
  7,
  32,
  1126,
  1,
  4539,
  5,
  2729,
  3,
  39,
  100,
  1414,
  144,
  2,
  962,
  774,
  1,
  271,
  15,
  2,
  2302,
  1,
  4112,
  18,
  115,
  6063,
  3937,
  1635,
  156,
  1061,
  2404,
  2127,
  4,
  2224,
  6993,
  346,
  110,
  6,
  5,
  4436,
  97,
  6,
  1,
  6129,
  3,
  1,
  8354,
  4369,
  20,
  11741,
  113,
  1,
  2582,
  7456,
  3,
  29,
  1719,
  2,
  1,
  87,
  197,
  20,
  33,
  9,
  1,
  13159,
  31,
  324,
  2,
  165,
  11741,
  6,
  509,
  1,
  6496,
  198,
  340,
  15,
  1,
  5766,
  3,
  1,
  1281,
  4,
  6,
  102,
  1010,
  12,
  15,
  2474,
  103,
  74,
  14409,
  45,
  119,
  1366,
  41,
  827,
  11741,
  15,
  1213,
  6,
  10139,
  346,
  343,
  58,
  21,
  1089,
  1751,
  6,
  6700,
  6785,
  952,
  28,
  39,
  2005,
  1723,
  12,
  1354,
  21,
  505,
  2,
  9461,
  16,
  5,
  528,
  1979,
  9462,
  1,
  505,
  3,
  5,
  2307,
  10,
  5,
  2400,
  1057,
  238,
  221,
  4795,
  3895,
  20,
  21,
  349,
  2,
  335,
  5,
  1196,
  12,
  113,
  1,
  13159,
  118,
  25,
  239,
  6,
  48,
  888,
  3,
  10639,
  487,
  12,
  17,
  11,
  733,
  6,
  16755,
  1098,
  28,
  581,
  7474,
  8197,
  70,
  85,
  11741,
  2888,
  7,
  21,
  3998,
  1232,
  28,
  4847,
  354,
  702,
  ...],
 [9380,
  246,
  160,
  30,
  345,
  3,
  63,
  6354,
  53,
  236,
  709,
  135,
  1045,
  5767,
  1211,
  1035,
  6342,
  9380,
  246,
  38,
  1656,
  1,
  10383,
  1005,
  9808,
  26,
  386,
  312,
  1538,
  1192,
  5696,
  4,
  13,
  5,
  1735,
  3,
  494,
  1538,
  288,
  1,
  641,
  27,
  4384,
  16,
  201,
  3,
  30,
  1602,
  2455,
  160,
  11,
  83,
  2338,
  5,
  10881,
  3,
  1130,
  236,
  246,
  180,
  214,
  16,
  990,
  16,
  1,
  3281,
  1809,
  10,
  10882,
  4,
  6,
  9433,
  18,
  4,
  14,
  160,
  24,
  5438,
  8013,
  3164,
  3,
  63,
  979,
  380,
  339,
  1035,
  2890,
  3,
  3715,
  30,
  683,
  1,
  2350,
  3,
  1142,
  1,
  5767,
  1211,
  1035,
  6342,
  9380,
  246,
  18,
  1070,
  24,
  5,
  287,
  3087,
  3,
  386,
  312,
  1538,
  1192,
  416,
  4,
  24,
  43,
  1678,
  2,
  368,
  1035,
  5500,
  1611,
  1,
  53,
  1035,
  83,
  2338,
  10740,
  3,
  1130,
  236,
  246,
  180,
  214,
  16,
  990,
  16,
  1,
  3281,
  1809,
  10,
  10882,
  4,
  6,
  9433,
  11828,
  151,
  9,
  173,
  209,
  45,
  1615,
  562,
  8,
  1686,
  1697,
  2,
  1656,
  1,
  1889,
  2483,
  10383,
  1005,
  9380,
  641,
  13,
  1,
  53,
  2094,
  1747,
  5,
  4332,
  3,
  317,
  8502,
  13,
  1,
  650,
  1,
  2395,
  24,
  3163,
  61,
  1,
  1595,
  95,
  1,
  650,
  4,
  1620,
  5,
  957,
  3,
  7,
  24,
  11420,
  1148,
  6,
  1,
  90,
  4,
  1702,
  1,
  3164,
  46,
  1319,
  993,
  18,
  337,
  11298,
  28,
  1,
  4816,
  3469,
  1757,
  5,
  681,
  881,
  3010,
  1,
  1658,
  17,
  7697,
  13,
  1,
  6516,
  3,
  1,
  209,
  86,
  1,
  68,
  444,
  267,
  9,
  1332,
  4,
  1,
  1697,
  1242,
  692,
  1,
  4816,
  3469,
  1757,
  15,
  6455,
  2,
  589,
  3469,
  4,
  1122,
  192,
  10,
  1,
  10086,
  1,
  5767,
  1211,
  1035,
  8,
  17,
  2,
  3447,
  1008,
  339,
  10740,
  4,
  8,
  2890,
  3,
  3715,
  30,
  683,
  1,
  2350,
  3,
  1142,
  42,
  575,
  152,
  2,
  209,
  105,
  883,
  51,
  8,
  1927,
  18,
  2054,
  1083,
  3,
  3931,
  1,
  2585,
  8,
  66,
  503,
  2,
  10741,
  5195,
  11,
  8,
  570,
  2,
  23,
  5,
  1735,
  3,
  494,
  1538,
  288,
  180,
  4120,
  51,
  40,
  741,
  1154,
  2,
  293,
  1241,
  4,
  9,
  729,
  625,
  2332,
  1904],
 [37,
  85,
  1196,
  193,
  17967,
  3226,
  4,
  14540,
  9,
  7850,
  16,
  969,
  35,
  69,
  137,
  10,
  29,
  48,
  8,
  11,
  14,
  37,
  85,
  558,
  3804,
  1,
  1270,
  2378,
  145,
  471,
  10,
  261,
  429,
  788,
  2361,
  10384,
  1384,
  5,
  1545,
  95,
  1,
  1270,
  2378,
  145,
  471,
  14540,
  1,
  3165,
  8073,
  704,
  4,
  3226,
  9,
  9322,
  962,
  2311,
  4,
  4000,
  6,
  17851,
  1,
  14540,
  3089,
  16,
  5,
  969,
  193,
  114,
  66,
  19854,
  11,
  6,
  116,
  1097,
  4,
  3226,
  1470,
  1,
  1083,
  196,
  3,
  63,
  3165,
  4860,
  413,
  3226,
  5780,
  35,
  13529,
  338,
  10,
  5,
  4218,
  2,
  144,
  5,
  2732,
  812,
  757,
  2495,
  7360,
  45,
  4,
  2140,
  26,
  17,
  6,
  5,
  228,
  261,
  116,
  31,
  9718,
  5001,
  1196,
  10384,
  16,
  969,
  366,
  5726,
  9,
  7402,
  2,
  1,
  2291,
  1196,
  1770,
  27,
  713,
  17852,
  14791,
  42,
  14235,
  17244,
  6,
  1,
  226,
  3,
  1,
  1270,
  2378,
  145,
  471,
  71,
  1545,
  8709,
  1,
  4880,
  1,
  14540,
  24,
  5515,
  30,
  368,
  3253,
  969,
  193,
  9,
  63,
  605,
  2,
  207,
  1050,
  1586,
  4,
  119,
  1252,
  4,
  533,
  23,
  5,
  8013,
  1201,
  10,
  1,
  327,
  2603,
  3,
  1742,
  4,
  10,
  962,
  327,
  367,
  9,
  52,
  47,
  3,
  1770,
  7360,
  1369,
  58,
  467,
  426,
  1,
  14540,
  30,
  1235,
  2,
  14337,
  35,
  23,
  11829,
  29,
  468,
  509,
  1151,
  5,
  1448,
  18,
  5,
  2711,
  3,
  71,
  6925,
  2,
  4432,
  71,
  198,
  252,
  157,
  1,
  145,
  4,
  2,
  1479,
  1,
  962,
  327,
  367,
  252,
  3,
  52,
  218,
  1,
  45,
  2179,
  1,
  1545,
  2955,
  57,
  867,
  95,
  1,
  14540,
  4,
  3226,
  516,
  44],
 [757,
  1942,
  2135,
  1885,
  18,
  1,
  3850,
  237,
  215,
  41,
  30,
  6025,
  373,
  34,
  959,
  26,
  1,
  140,
  4202,
  6980,
  1942,
  2135,
  1720,
  1,
  340,
  3,
  56,
  733,
  60,
  12,
  959,
  57,
  95,
  87],
 [89, 5349, 2019, 10, 19, 160, 950, 340, 2493, 447, 3, 173],
 [2252,
  2161,
  2303,
  5265,
  3009,
  238,
  99,
  2252,
  73,
  2,
  982,
  9,
  2911,
  173,
  1,
  2303,
  3,
  1,
  2161,
  3435,
  341,
  3,
  107,
  8536,
  8,
  980,
  484,
  21,
  499,
  298,
  7,
  11055,
  3009,
  1672,
  31,
  161,
  5,
  6108,
  130,
  1,
  140,
  2951,
  2,
  1018,
  143,
  5705,
  1,
  298,
  15,
  134,
  10,
  1,
  2161,
  14,
  499,
  1001,
  261,
  391,
  4,
  24,
  148,
  708,
  1024,
  3,
  599,
  4,
  2595,
  1,
  298,
  3574,
  1,
  2161,
  38,
  67,
  822,
  238,
  103,
  3009,
  2041,
  29,
  38,
  741,
  90,
  2,
  522,
  1,
  4,
  1009,
  574,
  6786,
  27,
  678,
  218,
  3134,
  9,
  103,
  14184,
  2161,
  600,
  2303,
  9029,
  31,
  2405,
  61,
  6,
  1,
  13632,
  3156,
  810,
  1,
  298,
  4,
  17,
  12,
  925,
  82,
  395,
  55,
  1,
  298,
  2166,
  77,
  2373,
  360,
  1674,
  34,
  40,
  25,
  395,
  55,
  851,
  218,
  869,
  82,
  1,
  290,
  17,
  34,
  429,
  73,
  2,
  982,
  9,
  2911,
  178,
  34,
  4077,
  36,
  2871,
  82,
  165,
  103,
  3743,
  42,
  9697,
  6,
  71,
  860,
  126,
  161,
  5,
  6108,
  164,
  16,
  119,
  2264,
  81,
  34,
  4077,
  36,
  2805,
  82,
  431,
  48,
  32,
  4519,
  56,
  71,
  319,
  441,
  24,
  426,
  80,
  4,
  34,
  146,
  7,
  14,
  1,
  308,
  36,
  83,
  81,
  2,
  407,
  1881,
  2,
  71,
  126,
  8,
  748,
  9,
  1,
  1390,
  4,
  1,
  2951,
  16,
  3,
  283,
  637,
  5,
  523,
  3,
  1,
  599,
  46,
  6,
  170,
  3,
  1,
  2161,
  35,
  52,
  718,
  7641,
  9,
  29,
  34,
  1304,
  22,
  18,
  13,
  16,
  102,
  47,
  34,
  69,
  2070,
  61,
  17,
  48,
  13409,
  186,
  446,
  15,
  1311,
  1715,
  5468,
  5468,
  3,
  452,
  8,
  25,
  3957,
  1,
  1553,
  3,
  1508,
  14,
  91,
  32,
  396,
  82,
  395,
  37,
  80,
  516,
  44],
 [694,
  1705,
  4040,
  10742,
  5727,
  3,
  2052,
  660,
  236,
  6,
  29,
  1855,
  567,
  2560,
  2741,
  1159,
  1,
  15321,
  7,
  11864,
  18516,
  2,
  8,
  375,
  3632,
  1159,
  1,
  3412,
  2741,
  15185,
  369,
  286,
  1,
  5727,
  3,
  1871,
  14006,
  5522,
  2268,
  1714,
  5,
  1186,
  54,
  14,
  706,
  1705,
  24,
  43,
  1568,
  151,
  58,
  5,
  4040,
  15,
  300,
  306,
  637,
  4894,
  1797,
  1860,
  17,
  306,
  11,
  41,
  1568,
  63,
  5147,
  1705,
  5,
  2339,
  180,
  7361,
  1192,
  154,
  16935,
  7,
  5147,
  706,
  28,
  3654,
  2,
  2793,
  2132,
  15710,
  1,
  4040,
  2162,
  464,
  391,
  6,
  30,
  2880,
  683,
  3,
  1,
  388,
  118,
  25,
  816,
  30,
  4533,
  3,
  1,
  6118,
  11978,
  33,
  17,
  64,
  15,
  67,
  2356,
  2,
  1,
  163,
  2586,
  481,
  2,
  132,
  1489,
  6,
  7895,
  61,
  1,
  8503,
  7327,
  52,
  3,
  51,
  24,
  43,
  3442,
  6,
  5,
  18886,
  17443,
  26,
  3490,
  20,
  1,
  388,
  17,
  6,
  5,
  105,
  807,
  14669,
  3965,
  7,
  1,
  1705,
  8,
  5,
  799,
  1554,
  166,
  4894,
  4,
  2088,
  4653,

In [17]:
max_sequence_len = 600

___
# Pad Sequence
___

In [18]:
input_padded = pad_sequences(
    sequences, maxlen = max_sequence_len, padding = "pre"
)

input_padded

array([[    5,    68,     3, ...,   340,   746,   105],
       [    0,     0,     0, ...,     6,     5, 13158],
       [    1,  3703,   761, ...,   274,   174,    20],
       ...,
       [    0,     0,     0, ...,  7610,   417,   686],
       [    0,     0,     0, ...,   484,   696,    20],
       [    0,     0,     0, ...,    22, 15834,   766]],
      shape=(71537, 600), dtype=int32)

___
# X and Y split 
___

In [19]:
X = input_padded
y = df["label"].values

___
# Train Test Split 
___

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

___
# Model Training
___

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, GRU, Dropout, Dense


model = Sequential()
model.add(Embedding(total_words, 64, input_length=max_sequence_len))
model.add(Bidirectional(GRU(100)))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))  # binary: fake/real

/home/aizen/miniconda3/envs/gensim-env/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
E0000 00:00:1790237278.135884   11463 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [22]:
model.compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = ["accuracy"]
)

In [23]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

In [ ]:
# Train Model 

history = model.fit(
    X_train,
    y_train,
    validation_data = (X_test, y_test),
    epochs = 50,
    callbacks = [early_stopping],
    verbose = 1
)

___
# Prediction
___

In [ ]:
def predict_news(text):
    sequence = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequence, maxlen=max_sequence_len, padding='pre')
    prediction = model.predict(padded, verbose=0)[0][0]
    label = "REAL" if prediction >= 0.5 else "FAKE"
    print(f"Prediction : {label}")
    print(f"Confidence : {prediction:.4f}")

# Test
predict_news("NASA confirms water found on Mars surface in new study")
predict_news("SHOCKING: Government putting chemicals in water to control minds")