# Group by
- When we have a column ( catagorical  {has different catigories like Genre Col has: Action, Comedy, Horror }) group by will split Datasets in different groups based on Catigories like Action group, Comedy grp etc:


        df.groupby("col_name")

In [1]:
import pandas as pd

In [7]:
# imdb-top-1000
movies = pd.read_csv("imdb-top-1000.csv")
movies.head(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0

In [14]:
genre = movies.groupby("Genre")

In [18]:
# now Genre Has split Whole Dataset in group bsed on Genres
genre.sum().head(3)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0

# genre = movies.groupby("genre)

- Genre col has many catigories for Action, comedy, Drame etc 
- we we apply groupby on genre col -->> the Whole Dataset split in three Tables -->> Action, Drama, Comedy

- Each table has all the other cols that OG dataFrame had 
- when we apply sum then in each group like in Action there are many cols each cols has Data (values) so in every col all the values sums up and only the reslut is shown thats why the above cols shows so high numbs in each col

Original DataFrame
--------------------------

| Title    | Genre  | Rating |
| -------- | ------ | ------ |
| Avengers | Action | 8      |
| Batman   | Action | 9      |
| Mask     | Comedy | 7      |
| Joker    | Drama  | 8      |
| Titanic  | Drama  | 9      |


after group by:

- Action Group

| Title    | Genre  | Rating |
| -------- | ------ | ------ |
| Avengers | Action | 8      |
| Batman   | Action | 9      |


- Comedy Group

| Title | Genre  | Rating |
| ----- | ------ | ------ |
| Mask  | Comedy | 7      |


- Drama Group

| Title   | Genre | Rating |
| ------- | ----- | ------ |
| Joker   | Drama | 8      |
| Titanic | Drama | 9      |

In [21]:
genre.max().head(3)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0

# Selecting Specific Col WHen Applying Mathematical Funstions

        df.groupby("Catagorical_col")["specific_col"]

In [22]:
# Find top 3 genre by total earnings  
# now we Only need Gross Col we dont need to calculate for other cols in a group 
# so we Specify it
movies.groupby("Genre")["Gross"].sum().sort_values(ascending = False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [24]:
# find the Genre which has highiest avg imdb rating

movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending = False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [ ]:
#find Directory who is most poular  ( nmbr of votes )
# group by directo
movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending = False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [30]:
# find number of movies done by each Acto
movies["Star1"].value_counts()

Star1
Tom Hanks            12
Robert De Niro       11
Al Pacino            10
Clint Eastwood       10
Leonardo DiCaprio     9
                     ..
Phil Harris           1
David Hemmings        1
John Lennon           1
Tallulah Bankhead     1
Robert Donat          1
Name: count, Length: 660, dtype: int64

# Attributes 

- Length:

        -find total number of groups 

                len(df.groupby("col")) 

- Item:

    - How many rows (items ) are in eacg hroup 

            df.groupby().size()  

    (it size same as value counts )

- First / Last / nth:

        df.groupby().first()  -->> give 1st item of each group 

        df.groupby.last()    --->> give last item of each group

        df.groupby().nth(idx)   --->> give that item of each group

- Get Group:

    - How many items are in Particular group 

            df.groupby().get_groups("grp name")    -->> give all the items of this grp

In [31]:
#
len(movies.groupby("Genre"))

14

In [32]:
len(movies.groupby("Director"))

548

In [33]:
movies.groupby("Genre").size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [34]:
movies.groupby("Genre").first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [35]:
df.groupby("Genre").last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [36]:
df.groupby("Genre").nth(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0
35,The Intouchables,2011,112,Biography,8.5,Olivier Nakache,Éric Toledano,760360,13182281.0,57.0
52,City Lights,1931,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,167839,19181.0,99.0
56,Kimi no na wa.,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
110,Das Boot,1981,149,Adventure,8.3,Wolfgang Petersen,Jürgen Prochnow,231855,11487676.0,86.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [ ]:
movies.groupby("Genre").get_group("Horror")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

# Aggregate Functions 
- min() , max() , sum() etc

## Multiple Aggregate Functions
### Using Dict:

    df.groupby().agg({"col name": "func" , "col name2": "func"})

- specific Fnction on specfic col

### using list:

    df.groupby().agg( ["func", "func2] )

- apply these function on ever col

### merge

    df.groupby.agg( {"col name": ["func1" , "func2" ]} )

In [39]:
genre = movies.groupby("Genre")
genre

In [43]:
genre.sum().head(1)  # apply sum on all the col

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0

In [ ]:
# apply specific function on specifc col

genre.agg( 
    {
        "Runtime": "mean",
        "IMDB_Rating": "mean",
        "No_of_Votes": "sum",
        "Gross": "sum",
        "Metascore": "min"
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [ ]:
genre.agg( ["max", "min"])
# now each col has min max col

                                  Series_Title  \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                           Released_Year       Runtime       \
                                       min           max   min     max  min
Genre
Action                                 300          2019  1924     321   45
Adventure            2001: A Space Odyssey            PG  1925     228   88
Animation                            Akira          2020  1940     137   71
Biography                 12 Years a Slave          2020  1928     209   93
Comedy                (500) Days of Summer          2020  1921     188   68
Crime                         12 Angry Men          2019  1931     229   80
Drama                                 1917          2020  1925     242   64
Family          E.T. the Extra-Terrestrial          1982  1971     115  100
Fantasy       Das Cabinet des Dr. Caligari          1922  1920      94   76
Film-Noir                Shadow of a Doubt          1949  1941     108  100
Horror                               Alien          2017  1933     122   71
Mystery                          Dark City          2012  1938     138   96
Thriller                   Wait Until Dark          1967  1967     108  108
Western    Il buono, il brutto, il cattivo          1976  1965     165  132

          IMDB_Rating               Director                         \
                  max  min               max                    min
Genre
Action            9.0  7.6       Zack Snyder       Abhishek Chaubey
Adventure         8.6  7.6  Ömer Faruk Sorak         Akira Kurosawa
Animation         8.6  7.6   Yoshifumi Kondô            Adam Elliot
Biography         8.9  7.6      Tom McCarthy             Adam McKay
Comedy            8.6  7.6       Zoya Akhtar  Alejandro G. Iñárritu
Crime             9.2  7.6      Yavuz Turgul         Akira Kurosawa
Drama             9.3  7.6       Çagan Irmak             Aamir Khan
Family            7.8  7.8  Steven Spielberg             Mel Stuart
Fantasy           8.1  7.9      Robert Wiene            F.W. Murnau
Film-Noir         8.1  7.8       John Huston       Alfred Hitchcock
Horror            8.5  7.6  William Friedkin     Alejandro Amenábar
Mystery           8.4  7.6     Terry Gilliam            Alex Proyas
Thriller          7.8  7.8     Terence Young          Terence Young
Western           8.8  7.8      Sergio Leone         Clint Eastwood

                      Star1                           No_of_Votes          \
                        max                       min         max     min
Genre
Action         Yun-Fat Chow                Aamir Khan     2303232   25312
Adventure      Yves Montand                Aamir Khan     1512360   29999
Animation      Yôji Matsuda             Adrian Molina      999790   25229
Biography     Éric Toledano              Adrien Brody     1213505   27254
Comedy     Ömer Faruk Sorak                Aamir Khan      939631   26337
Crime        Vincent Cassel                Ajay Devgn     1826188   27712
Drama        Çetin Tekindor                Abhay Deol     2343110   25088
Family         Henry Thomas               Gene Wilder      372490  178731
Fantasy       Werner Krauss               Max Schreck       88794   57428
Film-Noir     Teresa Wright           Humphrey Bogart      158731   59556
Horror     Sigourney Weaver           Anthony Perkins      787806   27007
Mystery         Vidya Balan  Bernard-Pierre Donnadieu     1129894   33982
Thriller     Audrey Hepburn            Audrey Hepburn       27733   27733
Western         Henry Fonda            Clint Eastwood      688390   65659

                 Gross              Metascore
                   max          min       max   min
Genre
Action     936662225.0       3296.0      98.0  33.0
Adventure  874211619.0      61001.0     100.0  41.0
Animation  873839108.0     128985.0      96.0  61.0
Biography  753585104.0      21877.0      97.0  48.0
Comedy     886752933.0       1305.0      99.0  45.0
Crime      790482117.0       6013.0     100.0  47.0
Drama      924558264.0       3600.0     100.0  28.0
Family     435110554.0    4000000.0      91.0  67.0
Fantasy    445151978.0  337574718.0       NaN   NaN
Film-Noir  123353292.0     449191.0      97.0  94.0
Horror     298791505.0      89029.0      97.0  46.0
Mystery    474203697.0    1035953.0     100.0  52.0
Thriller    17550741.0   17550741.0      81.0  81.0
Western     31800000.0    5321508.0      90.0  69.0

In [48]:
genre.agg( 
    {
        "Runtime": ["min", "max"],
        "IMDB_Rating": ["min", "max"],
        "No_of_Votes": ["sum", "mean"],
        "Gross" :    ["sum", "max", "min"]
    }
)

          Runtime      IMDB_Rating      No_of_Votes                 \
              min  max         min  max         sum           mean
Genre
Action         45  321         7.6  9.0    72282412  420246.581395
Adventure      88  228         7.6  8.6    22576163  313557.819444
Animation      71  137         7.6  8.6    21978630  268032.073171
Biography      93  209         7.6  8.9    24006844  272805.045455
Comedy         68  188         7.6  8.6    27620327  178195.658065
Crime          80  229         7.6  9.2    33533615  313398.271028
Drama          64  242         7.6  9.3    61367304  212343.612457
Family        100  115         7.8  7.8      551221  275610.500000
Fantasy        76   94         7.9  8.1      146222   73111.000000
Film-Noir     100  108         7.8  8.1      367215  122405.000000
Horror         71  122         7.6  8.5     3742556  340232.363636
Mystery        96  138         7.6  8.4     4203004  350250.333333
Thriller      108  108         7.8  7.8       27733   27733.000000
Western       132  165         7.8  8.8     1289665  322416.250000

                  Gross
                    sum          max          min
Genre
Action     3.263226e+10  936662225.0       3296.0
Adventure  9.496922e+09  874211619.0      61001.0
Animation  1.463147e+10  873839108.0     128985.0
Biography  8.276358e+09  753585104.0      21877.0
Comedy     1.566387e+10  886752933.0       1305.0
Crime      8.452632e+09  790482117.0       6013.0
Drama      3.540997e+10  924558264.0       3600.0
Family     4.391106e+08  435110554.0    4000000.0
Fantasy    7.827267e+08  445151978.0  337574718.0
Film-Noir  1.259105e+08  123353292.0     449191.0
Horror     1.034649e+09  298791505.0      89029.0
Mystery    1.256417e+09  474203697.0    1035953.0
Thriller   1.755074e+07   17550741.0   17550741.0
Western    5.822151e+07   31800000.0    5321508.0

## Practice

In [65]:
import numpy as np

np.random.seed(42)

characters = [
    "Naruto","Sasuke","Sakura","Kakashi","Itachi","Hinata","Shikamaru",
    "Neji","Rock Lee","Gaara","Tsunade","Jiraiya","Orochimaru",
    "Minato","Madara","Obito","Pain","Konan","Killer Bee","Yamato"
]

villages = ["Leaf","Sand","Mist","Stone","Cloud"]

teams = ["Team 7","Team 8","Team 10","Akatsuki","Anbu"]

missions = ["D","C","B","A","S"]

df = pd.DataFrame({
    "Character": np.random.choice(characters,500),
    "Village": np.random.choice(villages,500),
    "Team": np.random.choice(teams,500),
    "MissionRank": np.random.choice(missions,500),
    "ChakraLevel": np.random.randint(50,1000,500),
    "BattlesWon": np.random.randint(0,100,500),
    "BattlesLost": np.random.randint(0,50,500),
    "JutsuKnown": np.random.randint(5,200,500),
    "Age": np.random.randint(12,60,500)
})

df.head(10)

,Character,Village,Team,MissionRank,ChakraLevel,BattlesWon,BattlesLost,JutsuKnown,Age
0,Shikamaru,Stone,Team 8,A,566,55,19,61,12
1,Yamato,Leaf,Team 10,C,477,2,48,51,12
2,Madara,Sand,Team 8,A,588,62,24,167,37
3,Tsunade,Sand,Team 10,B,209,18,39,23,56
4,Neji,Stone,Team 7,B,198,22,23,118,31
5,Shikamaru,Leaf,Team 10,B,825,28,13,12,34
6,Killer Bee,Cloud,Team 10,D,279,29,25,30,21
7,Tsunade,Cloud,Akatsuki,A,761,38,37,117,22
8,Tsunade,Sand,Team 10,A,611,24,22,75,52
9,Kakashi,Leaf,Team 10,S,116,7,21,34,52

In [52]:
# Count ninjas per village.
df.groupby("Village").size()

Village
Cloud    109
Leaf     106
Mist      95
Sand      97
Stone     93
dtype: int64

In [54]:
# Average chakra level per village.
df.groupby("Village")["ChakraLevel"].mean().sort_values( ascending = True)

Village
Mist     442.768421
Leaf     525.867925
Sand     530.762887
Stone    554.258065
Cloud    566.220183
Name: ChakraLevel, dtype: float64

In [56]:
# Total battles won per team.
df.groupby("Team")["BattlesWon"].sum().sort_values( ascending = True)

Team
Akatsuki    3760
Anbu        5002
Team 10     5036
Team 7      5212
Team 8      5260
Name: BattlesWon, dtype: int64

In [63]:
# Count characters per village and team.
df.groupby(["Village", "Team"]).size()

Village  Team
Cloud    Akatsuki    19
         Anbu        22
         Team 10     20
         Team 7      28
         Team 8      20
Leaf     Akatsuki     7
         Anbu        31
         Team 10     21
         Team 7      17
         Team 8      30
Mist     Akatsuki    22
         Anbu        19
         Team 10     22
         Team 7      13
         Team 8      19
Sand     Akatsuki    14
         Anbu        20
         Team 10     25
         Team 7      20
         Team 8      18
Stone    Akatsuki    18
         Anbu        14
         Team 10     19
         Team 7      23
         Team 8      19
dtype: int64

In [64]:
# Average chakra per village and team.
df.groupby(["Village", "Team"])["ChakraLevel"].mean()

Village  Team
Cloud    Akatsuki    513.263158
         Anbu        636.363636
         Team 10     528.000000
         Team 7      539.285714
         Team 8      615.300000
Leaf     Akatsuki    411.000000
         Anbu        529.096774
         Team 10     485.857143
         Team 7      587.941176
         Team 8      542.166667
Mist     Akatsuki    445.318182
         Anbu        416.736842
         Team 10     459.363636
         Team 7      486.615385
         Team 8      416.631579
Sand     Akatsuki    495.857143
         Anbu        573.550000
         Team 10     541.680000
         Team 7      472.300000
         Team 8      560.166667
Stone    Akatsuki    555.777778
         Anbu        481.571429
         Team 10     592.052632
         Team 7      515.739130
         Team 8      615.210526
Name: ChakraLevel, dtype: float64

In [66]:
df.groupby("Village").agg({
    "ChakraLevel":["mean","max","min"],
    "BattlesWon":"sum"
})

        ChakraLevel           BattlesWon
               mean  max  min        sum
Village
Cloud    566.220183  995  128       5149
Leaf     525.867925  997   57       5069
Mist     442.768421  954   56       4370
Sand     530.762887  986   61       4786
Stone    554.258065  994   78       4896

In [67]:
df.groupby("Team").agg({
    "Age":["mean","max"],
    "JutsuKnown":"mean",
    "BattlesWon":"sum"
})

                Age      JutsuKnown BattlesWon
               mean max        mean        sum
Team
Akatsuki  32.450000  59  100.487500       3760
Anbu      36.226415  59   98.528302       5002
Team 10   35.542056  59   97.327103       5036
Team 7    35.831683  59  101.089109       5212
Team 8    34.632075  59  103.094340       5260

In [68]:
# Village with most battles won.
df.groupby("Village")["BattlesWon"].sum().sort_values(ascending=False)

Village
Cloud    5149
Leaf     5069
Stone    4896
Sand     4786
Mist     4370
Name: BattlesWon, dtype: int64

In [70]:
# find Nmbr of movies starting with A for each group 

def starts_A(group):
    return group["Series_Title"].str.startswith('A').sum()

genre.apply(starts_A)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [71]:
def normal(group):
    group["norm_rating"] = group["IMDB_Rating"].min() / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min())
    return group

genre.apply(normal)

/tmp/ipykernel_16902/3635021881.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  group["norm_rating"] = group["IMDB_Rating"].min() / (group["IMDB_Rating"].max() - group["IMDB_Rating"].min())

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  norm_rating
Genre
Action   2        2303232  534858444.0       84.0     5.428571
         5        1642758  377845905.0       94.0     5.428571
         8        2067042  292576195.0       74.0     5.428571
         10       1661481  315544750.0       92.0     5.428571
         13       1485555  342551365.0       87.0     5.428571
...                   ...          ...        ...          ...
Thriller 700        27733   17550741.0       81.0          inf
Western  12        688390    6100000.0       90.0     7.800000
         48        302844    5321508.0       80.0     7.800000
         115       232772   15000000.0       74.0     7.800000
         691        65659   31800000.0       69.0     7.800000

[1000 rows x 10 columns]

# Group by Multiple Col

    df.groupby(["col1" , "col2"])

In [75]:
dou = movies.groupby(["Director", "Star1"])
dou.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [79]:
# which acotr director combo has earned most money 

dou["Gross"].sum().sort_values( ascending = False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [81]:
# which ator genre combo is best in meta score

movies.groupby(["Genre", "Star1"])["Metascore"].mean()

Genre     Star1
Action    Aamir Khan                    NaN
          Aaron Taylor-Johnson    66.000000
          Akshay Kumar                  NaN
          Alan Mak                75.000000
          Alia Bhatt                    NaN
                                    ...
Mystery   Rufus Sewell            66.000000
          Vidya Balan                   NaN
Thriller  Audrey Hepburn          81.000000
Western   Clint Eastwood          77.666667
          Henry Fonda             80.000000
Name: Metascore, Length: 829, dtype: float64