# Practice
## using dogs_dirty_dataset_4000

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/dogs_dirty_dataset_40000x50.csv")

/tmp/ipykernel_2506/1753395807.py:1: DtypeWarning: Columns (0: owner_income, 1: sensor_metric_1, 2: sensor_metric_2, 3: sensor_metric_4, 4: sensor_metric_6, 5: sensor_metric_7, 6: sensor_metric_8, 7: sensor_metric_9, 8: sensor_metric_10, 9: sensor_metric_11, 10: sensor_metric_12, 11: sensor_metric_13, 12: sensor_metric_15, 13: sensor_metric_16, 14: sensor_metric_18, 15: sensor_metric_19, 16: sensor_metric_21, 17: sensor_metric_24, 18: sensor_metric_26, 19: sensor_metric_27, 20: sensor_metric_28, 21: sensor_metric_30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/dogs_dirty_dataset_40000x50.csv")

In [3]:
df

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,vaccinated,neutered,owner_city,...,sensor_metric_21,sensor_metric_22,sensor_metric_23,sensor_metric_24,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30
0,3945,Buddy,Husky,20,11.06,11.123158009569451kg,Golden,NaN,NaN,Dubai,...,42.046651,55.209475,27.954712286774882,62.08132287774031,66.40400068807999,20.830123239751433,6.746515624580134,5.097813,25.193275,33.763476439949144
1,1591,Lola,Beagle,8,13.28,25.73,Mixed,Yes,Yes,Paris,...,69.438131,45.341790,63.00184138309305,49.874068363992215,20.19055578657499,45.46069454136345,36.6599662315661,30.067048,81.168220,64.4719662030773
2,4939,Buddy,Mixed,4,22.7,4.58,Golden,No,Yes,Berlin,...,14.018924,43.912491,13.91744250741555,62.724941051950864,43.69299287478287,40.149247050280394,79.18674859339576,54.256182,54.851926,43.59422368257874
3,3530,Buddy,Beagle,1,15.028390835628947kg,8.63,Black,No,No,London,...,76.676259,39.718442,39.93732431616114,93.02602553897646,54.22198696870119,91.62066809547306,32.61100582666343,63.46211,42.238509,62.92383362044525
4,3300,Lola,Bulldog,6,15.0,20.29,Mixed,Yes,NaN,Paris,...,68.746673,33.595721,50.744679814739314,22.772689844471707,41.675508278136334,59.86767587375865,46.80392623950959,73.911042,73.070655,81.35956851828129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40495,1382,Toby,Beagle,-1,13.65,21.58,Brown,Yes,No,London,...,72.104673,46.043065,44.21474733341035,32.617982,30.95002827476446,43.564863,73.71033,30.875631238260908,43.570355,27.253745
40496,1750,Bailey,Pug,19,25.73,-5.78,NaN,Yes,No,Tokyo,...,63.502323,70.973872,41.9776164483673,40.468504,40.87602459696255,50.241797,101.631073,48.50749330776365,39.200419,86.230768
40497,4708,Lola,Poodle,15,0.5623810521001218kg,NaN,Black,NaN,No,Berlin,...,36.719414,49.260271,91.07287703273056,44.141101,67.89443724346116,41.541819,45.616401,26.418215546977187,21.016773,30.849703
40498,1021,Milo,Beagle,22,19.89,NaN,Brown,Yes,No,Tokyo,...,25.300485,10.827934,72.24044912764421,34.707883,22.882265402697286,74.061638,27.992923,63.178179800340914,31.946941,45.940651
40499,3853,Duke,Mixed,16,-5.15,11.81,White,NaN,No,Paris,...,8.643709,46.071218,72.35070908960688,65.281749,36.95780046444946,58.948602,54.728721,62.683958744675635,34.534437,72.623608

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40500 entries, 0 to 40499
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40500 non-null  int64
 1   dog_name             40500 non-null  str
 2   breed                40500 non-null  str
 3   age_years            40500 non-null  int64
 4   weight_kg            38772 non-null  str
 5   height_cm            38775 non-null  str
 6   color                33817 non-null  str
 7   vaccinated           26911 non-null  str
 8   neutered             27062 non-null  str
 9   owner_city           40500 non-null  str
 10  owner_age            40045 non-null  str
 11  owner_income         40500 non-null  object
 12  diet_type            33743 non-null  str
 13  daily_walk_minutes   40500 non-null  str
 14  barks_per_day        40318 non-null  str
 15  vet_visits_per_year  40500 non-null  str
 16  last_vet_visit       40500 non-null  str
 17  adoption_date        40500 non-null  str
 18  favorite_toy         26980 non-null  str
 19  training_level       32419 non-null  str
 20  sensor_metric_1      40498 non-null  object
 21  sensor_metric_2      40500 non-null  object
 22  sensor_metric_3      40499 non-null  float64
 23  sensor_metric_4      40499 non-null  object
 24  sensor_metric_5      40497 non-null  float64
 25  sensor_metric_6      40500 non-null  object
 26  sensor_metric_7      40499 non-null  object
 27  sensor_metric_8      40499 non-null  object
 28  sensor_metric_9      40498 non-null  object
 29  sensor_metric_10     40498 non-null  object
 30  sensor_metric_11     40500 non-null  object
 31  sensor_metric_12     40500 non-null  object
 32  sensor_metric_13     40499 non-null  object
 33  sensor_metric_14     40499 non-null  str
 34  sensor_metric_15     40499 non-null  object
 35  sensor_metric_16     40498 non-null  object
 36  sensor_metric_17     40498 non-null  str
 37  sensor_metric_18     40498 non-null  object
 38  sensor_metric_19     40498 non-null  object
 39  sensor_metric_20     40499 non-null  str
 40  sensor_metric_21     40498 non-null  object
 41  sensor_metric_22     40500 non-null  float64
 42  sensor_metric_23     40499 non-null  str
 43  sensor_metric_24     40498 non-null  object
 44  sensor_metric_25     40498 non-null  str
 45  sensor_metric_26     40500 non-null  object
 46  sensor_metric_27     40497 non-null  object
 47  sensor_metric_28     40500 non-null  object
 48  sensor_metric_29     40499 non-null  float64
 49  sensor_metric_30     40499 non-null  object
dtypes: float64(4), int64(2), object(22), str(22)
memory usage: 15.4+ MB

In [5]:
# calculate Missing Value
df.isnull().sum().sort_values(ascending=False)

vaccinated             13589
favorite_toy           13520
neutered               13438
training_level          8081
diet_type               6757
color                   6683
weight_kg               1728
height_cm               1725
owner_age                455
barks_per_day            182
sensor_metric_27           3
sensor_metric_5            3
sensor_metric_10           2
sensor_metric_9            2
sensor_metric_1            2
sensor_metric_16           2
sensor_metric_24           2
sensor_metric_19           2
sensor_metric_17           2
sensor_metric_18           2
sensor_metric_25           2
sensor_metric_21           2
sensor_metric_30           1
sensor_metric_20           1
sensor_metric_13           1
sensor_metric_14           1
sensor_metric_29           1
sensor_metric_8            1
sensor_metric_15           1
sensor_metric_23           1
sensor_metric_7            1
sensor_metric_3            1
sensor_metric_4            1
dog_name                   0
adoption_date              0
last_vet_visit             0
vet_visits_per_year        0
daily_walk_minutes         0
owner_income               0
age_years                  0
breed                      0
owner_city                 0
dog_id                     0
sensor_metric_12           0
sensor_metric_2            0
sensor_metric_6            0
sensor_metric_11           0
sensor_metric_22           0
sensor_metric_26           0
sensor_metric_28           0
dtype: int64

In [6]:
df.describe()
# detects outliersss , wrong values like negative

,dog_id,age_years,sensor_metric_3,sensor_metric_5,sensor_metric_22,sensor_metric_29
count,40500.000000,40500.000000,40499.000000,40497.000000,40500.000000,40499.000000
mean,3005.914963,10.975383,50.049533,50.073290,49.771757,49.892417
std,1151.715975,7.780623,20.028544,20.092971,20.078555,20.018532
min,1000.000000,-2.000000,-30.876166,-36.389297,-30.910368,-23.378135
25%,2012.000000,4.000000,36.416682,36.621960,36.310734,36.344416
50%,2996.000000,11.000000,50.018460,50.074433,49.697575,50.020991
75%,4007.000000,18.000000,63.410940,63.618955,63.201042,63.383708
max,4999.000000,24.000000,122.309447,135.797856,128.900034,136.055535

In [7]:
# Object Col Check
df.select_dtypes(include="object").nunique()

/tmp/ipykernel_2506/4270522926.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").nunique()

dog_name                  15
breed                     11
weight_kg               8962
height_cm               8927
color                      5
vaccinated                 2
neutered                   2
owner_city                10
owner_age                 81
owner_income           37231
diet_type                  5
daily_walk_minutes       191
barks_per_day            201
vet_visits_per_year       17
last_vet_visit         10474
adoption_date          10375
favorite_toy               4
training_level             4
sensor_metric_1        29221
sensor_metric_2        29295
sensor_metric_4        31380
sensor_metric_6        31398
sensor_metric_7        31389
sensor_metric_8        29278
sensor_metric_9        31500
sensor_metric_10       31359
sensor_metric_11       29340
sensor_metric_12       29231
sensor_metric_13       29320
sensor_metric_14       25185
sensor_metric_15       29265
sensor_metric_16       31446
sensor_metric_17       25296
sensor_metric_18       31325
sensor_metric_19       31385
sensor_metric_20       25172
sensor_metric_21       31378
sensor_metric_23       25360
sensor_metric_24       29171
sensor_metric_25       25292
sensor_metric_26       31298
sensor_metric_27       31327
sensor_metric_28       29176
sensor_metric_30       29184
dtype: int64

In [8]:
# percentage of missig Value in eac col
(df.isnull().sum() / len(df)) * 100

dog_id                  0.000000
dog_name                0.000000
breed                   0.000000
age_years               0.000000
weight_kg               4.266667
height_cm               4.259259
color                  16.501235
vaccinated             33.553086
neutered               33.180247
owner_city              0.000000
owner_age               1.123457
owner_income            0.000000
diet_type              16.683951
daily_walk_minutes      0.000000
barks_per_day           0.449383
vet_visits_per_year     0.000000
last_vet_visit          0.000000
adoption_date           0.000000
favorite_toy           33.382716
training_level         19.953086
sensor_metric_1         0.004938
sensor_metric_2         0.000000
sensor_metric_3         0.002469
sensor_metric_4         0.002469
sensor_metric_5         0.007407
sensor_metric_6         0.000000
sensor_metric_7         0.002469
sensor_metric_8         0.002469
sensor_metric_9         0.004938
sensor_metric_10        0.004938
sensor_metric_11        0.000000
sensor_metric_12        0.000000
sensor_metric_13        0.002469
sensor_metric_14        0.002469
sensor_metric_15        0.002469
sensor_metric_16        0.004938
sensor_metric_17        0.004938
sensor_metric_18        0.004938
sensor_metric_19        0.004938
sensor_metric_20        0.002469
sensor_metric_21        0.004938
sensor_metric_22        0.000000
sensor_metric_23        0.002469
sensor_metric_24        0.004938
sensor_metric_25        0.004938
sensor_metric_26        0.000000
sensor_metric_27        0.007407
sensor_metric_28        0.000000
sensor_metric_29        0.002469
sensor_metric_30        0.002469
dtype: float64

# Phase 2
- What is wrong with this dataset?
- Where is it wrong?
- Why is it wrong?
- What should we do with it?

In [9]:
df.columns

Index(['dog_id', 'dog_name', 'breed', 'age_years', 'weight_kg', 'height_cm',
       'color', 'vaccinated', 'neutered', 'owner_city', 'owner_age',
       'owner_income', 'diet_type', 'daily_walk_minutes', 'barks_per_day',
       'vet_visits_per_year', 'last_vet_visit', 'adoption_date',
       'favorite_toy', 'training_level', 'sensor_metric_1', 'sensor_metric_2',
       'sensor_metric_3', 'sensor_metric_4', 'sensor_metric_5',
       'sensor_metric_6', 'sensor_metric_7', 'sensor_metric_8',
       'sensor_metric_9', 'sensor_metric_10', 'sensor_metric_11',
       'sensor_metric_12', 'sensor_metric_13', 'sensor_metric_14',
       'sensor_metric_15', 'sensor_metric_16', 'sensor_metric_17',
       'sensor_metric_18', 'sensor_metric_19', 'sensor_metric_20',
       'sensor_metric_21', 'sensor_metric_22', 'sensor_metric_23',
       'sensor_metric_24', 'sensor_metric_25', 'sensor_metric_26',
       'sensor_metric_27', 'sensor_metric_28', 'sensor_metric_29',
       'sensor_metric_30'],
      dtype='str')

In [10]:
# col with only missng values
df.columns[df.isnull().all()]

Index([], dtype='str')

In [11]:
df.duplicated().sum()

np.int64(175)

In [12]:
df.info()
# check which col is taking Unneccassary space

<class 'pandas.DataFrame'>
RangeIndex: 40500 entries, 0 to 40499
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40500 non-null  int64
 1   dog_name             40500 non-null  str
 2   breed                40500 non-null  str
 3   age_years            40500 non-null  int64
 4   weight_kg            38772 non-null  str
 5   height_cm            38775 non-null  str
 6   color                33817 non-null  str
 7   vaccinated           26911 non-null  str
 8   neutered             27062 non-null  str
 9   owner_city           40500 non-null  str
 10  owner_age            40045 non-null  str
 11  owner_income         40500 non-null  object
 12  diet_type            33743 non-null  str
 13  daily_walk_minutes   40500 non-null  str
 14  barks_per_day        40318 non-null  str
 15  vet_visits_per_year  40500 non-null  str
 16  last_vet_visit       40500 non-null  str
 17  adoption_date        40500 non-null  str
 18  favorite_toy         26980 non-null  str
 19  training_level       32419 non-null  str
 20  sensor_metric_1      40498 non-null  object
 21  sensor_metric_2      40500 non-null  object
 22  sensor_metric_3      40499 non-null  float64
 23  sensor_metric_4      40499 non-null  object
 24  sensor_metric_5      40497 non-null  float64
 25  sensor_metric_6      40500 non-null  object
 26  sensor_metric_7      40499 non-null  object
 27  sensor_metric_8      40499 non-null  object
 28  sensor_metric_9      40498 non-null  object
 29  sensor_metric_10     40498 non-null  object
 30  sensor_metric_11     40500 non-null  object
 31  sensor_metric_12     40500 non-null  object
 32  sensor_metric_13     40499 non-null  object
 33  sensor_metric_14     40499 non-null  str
 34  sensor_metric_15     40499 non-null  object
 35  sensor_metric_16     40498 non-null  object
 36  sensor_metric_17     40498 non-null  str
 37  sensor_metric_18     40498 non-null  object
 38  sensor_metric_19     40498 non-null  object
 39  sensor_metric_20     40499 non-null  str
 40  sensor_metric_21     40498 non-null  object
 41  sensor_metric_22     40500 non-null  float64
 42  sensor_metric_23     40499 non-null  str
 43  sensor_metric_24     40498 non-null  object
 44  sensor_metric_25     40498 non-null  str
 45  sensor_metric_26     40500 non-null  object
 46  sensor_metric_27     40497 non-null  object
 47  sensor_metric_28     40500 non-null  object
 48  sensor_metric_29     40499 non-null  float64
 49  sensor_metric_30     40499 non-null  object
dtypes: float64(4), int64(2), object(22), str(22)
memory usage: 15.4+ MB

## first Check wrong DateType of Col
- weight_kg is in str could be in int like this
- height_cm in str -> int

In [13]:
df["weight_kg"] = pd.to_numeric(df["weight_kg"], errors="coerce")
df["height_cm"] = pd.to_numeric(df["height_cm"], errors="coerce")
df["owner_age"] = pd.to_numeric(df["owner_age"], errors='coerce')
df["barks_per_day"] = pd.to_numeric(df["barks_per_day"], errors="coerce")
df["daily_walk_minutes"] = pd.to_numeric(df["daily_walk_minutes"], errors="coerce")
df["owner_income"] = pd.to_numeric(df["owner_income"], errors="coerce")
df["vet_visits_per_year"] = pd.to_numeric(df["vet_visits_per_year"], errors="coerce")
df["adoption_date"] = pd.to_numeric(df["adoption_date"], errors="coerce")

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40500 entries, 0 to 40499
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40500 non-null  int64
 1   dog_name             40500 non-null  str
 2   breed                40500 non-null  str
 3   age_years            40500 non-null  int64
 4   weight_kg            32925 non-null  float64
 5   height_cm            32906 non-null  float64
 6   color                33817 non-null  str
 7   vaccinated           26911 non-null  str
 8   neutered             27062 non-null  str
 9   owner_city           40500 non-null  str
 10  owner_age            39575 non-null  float64
 11  owner_income         40499 non-null  float64
 12  diet_type            33743 non-null  str
 13  daily_walk_minutes   40292 non-null  float64
 14  barks_per_day        40137 non-null  float64
 15  vet_visits_per_year  38088 non-null  float64
 16  last_vet_visit       40500 non-null  str
 17  adoption_date        0 non-null      float64
 18  favorite_toy         26980 non-null  str
 19  training_level       32419 non-null  str
 20  sensor_metric_1      40498 non-null  object
 21  sensor_metric_2      40500 non-null  object
 22  sensor_metric_3      40499 non-null  float64
 23  sensor_metric_4      40499 non-null  object
 24  sensor_metric_5      40497 non-null  float64
 25  sensor_metric_6      40500 non-null  object
 26  sensor_metric_7      40499 non-null  object
 27  sensor_metric_8      40499 non-null  object
 28  sensor_metric_9      40498 non-null  object
 29  sensor_metric_10     40498 non-null  object
 30  sensor_metric_11     40500 non-null  object
 31  sensor_metric_12     40500 non-null  object
 32  sensor_metric_13     40499 non-null  object
 33  sensor_metric_14     40499 non-null  str
 34  sensor_metric_15     40499 non-null  object
 35  sensor_metric_16     40498 non-null  object
 36  sensor_metric_17     40498 non-null  str
 37  sensor_metric_18     40498 non-null  object
 38  sensor_metric_19     40498 non-null  object
 39  sensor_metric_20     40499 non-null  str
 40  sensor_metric_21     40498 non-null  object
 41  sensor_metric_22     40500 non-null  float64
 42  sensor_metric_23     40499 non-null  str
 43  sensor_metric_24     40498 non-null  object
 44  sensor_metric_25     40498 non-null  str
 45  sensor_metric_26     40500 non-null  object
 46  sensor_metric_27     40497 non-null  object
 47  sensor_metric_28     40500 non-null  object
 48  sensor_metric_29     40499 non-null  float64
 49  sensor_metric_30     40499 non-null  object
dtypes: float64(12), int64(2), object(21), str(15)
memory usage: 15.4+ MB

## now Check if Cols are taking Unneccassary Space
- if it can be stored in int8 and is stored in in64

In [15]:
df["dog_id"] = df["dog_id"].astype("Int16")
df["age_years"] = df["age_years"].astype("int8")
df["owner_age"] = df["owner_age"].astype("float16")
df["vet_visits_per_year"] = df["vet_visits_per_year"].astype("float16")
df["weight_kg"] = df["weight_kg"].astype("float16")
df["height_cm"] = df["height_cm"].astype("float16")
df["owner_income"] = df["owner_income"].astype("float16")
df["barks_per_day"] = df["barks_per_day"].astype("float16")
df["daily_walk_minutes"] = df["daily_walk_minutes"].astype("float16")


# now we will Convert Catigorical col to type catigory instead of str

dog_cols = [ # this list contains names of catgorical Cols
    "breed", "color", "diet_type", "training_level",
    "owner_city", "vaccinated", "neutered"
]

for col in dog_cols: # loop over dog_col and cnvert those col into catigory
    df[col] = df[col].astype("category")

#list Comprehension: [expression for item in iterable if condition]
sensor_cols = [col for col in df.columns if "sensor_metric" in col]
# put all those cols in list which have "sensor col" in their name

# now change its type
for col in sensor_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype('float32')

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/core/dtypes/astype.py:136: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=copy)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40500 entries, 0 to 40499
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40500 non-null  Int16
 1   dog_name             40500 non-null  str
 2   breed                40500 non-null  category
 3   age_years            40500 non-null  int8
 4   weight_kg            32925 non-null  float16
 5   height_cm            32906 non-null  float16
 6   color                33817 non-null  category
 7   vaccinated           26911 non-null  category
 8   neutered             27062 non-null  category
 9   owner_city           40500 non-null  category
 10  owner_age            39575 non-null  float16
 11  owner_income         40499 non-null  float16
 12  diet_type            33743 non-null  category
 13  daily_walk_minutes   40292 non-null  float16
 14  barks_per_day        40137 non-null  float16
 15  vet_visits_per_year  38088 non-null  float16
 16  last_vet_visit       40500 non-null  str
 17  adoption_date        0 non-null      float64
 18  favorite_toy         26980 non-null  str
 19  training_level       32419 non-null  category
 20  sensor_metric_1      40493 non-null  float32
 21  sensor_metric_2      40497 non-null  float32
 22  sensor_metric_3      40499 non-null  float32
 23  sensor_metric_4      40497 non-null  float32
 24  sensor_metric_5      40497 non-null  float32
 25  sensor_metric_6      40499 non-null  float32
 26  sensor_metric_7      40498 non-null  float32
 27  sensor_metric_8      40495 non-null  float32
 28  sensor_metric_9      40495 non-null  float32
 29  sensor_metric_10     40497 non-null  float32
 30  sensor_metric_11     40498 non-null  float32
 31  sensor_metric_12     40497 non-null  float32
 32  sensor_metric_13     40496 non-null  float32
 33  sensor_metric_14     40496 non-null  float32
 34  sensor_metric_15     40497 non-null  float32
 35  sensor_metric_16     40494 non-null  float32
 36  sensor_metric_17     40493 non-null  float32
 37  sensor_metric_18     40496 non-null  float32
 38  sensor_metric_19     40497 non-null  float32
 39  sensor_metric_20     40494 non-null  float32
 40  sensor_metric_21     40495 non-null  float32
 41  sensor_metric_22     40500 non-null  float32
 42  sensor_metric_23     40496 non-null  float32
 43  sensor_metric_24     40495 non-null  float32
 44  sensor_metric_25     40494 non-null  float32
 45  sensor_metric_26     40498 non-null  float32
 46  sensor_metric_27     40496 non-null  float32
 47  sensor_metric_28     40499 non-null  float32
 48  sensor_metric_29     40499 non-null  float32
 49  sensor_metric_30     40497 non-null  float32
dtypes: Int16(1), category(7), float16(7), float32(30), float64(1), int8(1), str(3)
memory usage: 6.8 MB

In [17]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 40500 entries, 0 to 40499
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40500 non-null  Int16
 1   dog_name             40500 non-null  str
 2   breed                40500 non-null  category
 3   age_years            40500 non-null  int8
 4   weight_kg            32925 non-null  float16
 5   height_cm            32906 non-null  float16
 6   color                33817 non-null  category
 7   vaccinated           26911 non-null  category
 8   neutered             27062 non-null  category
 9   owner_city           40500 non-null  category
 10  owner_age            39575 non-null  float16
 11  owner_income         40499 non-null  float16
 12  diet_type            33743 non-null  category
 13  daily_walk_minutes   40292 non-null  float16
 14  barks_per_day        40137 non-null  float16
 15  vet_visits_per_year  38088 non-null  float16
 16  last_vet_visit       40500 non-null  str
 17  adoption_date        0 non-null      float64
 18  favorite_toy         26980 non-null  str
 19  training_level       32419 non-null  category
 20  sensor_metric_1      40493 non-null  float32
 21  sensor_metric_2      40497 non-null  float32
 22  sensor_metric_3      40499 non-null  float32
 23  sensor_metric_4      40497 non-null  float32
 24  sensor_metric_5      40497 non-null  float32
 25  sensor_metric_6      40499 non-null  float32
 26  sensor_metric_7      40498 non-null  float32
 27  sensor_metric_8      40495 non-null  float32
 28  sensor_metric_9      40495 non-null  float32
 29  sensor_metric_10     40497 non-null  float32
 30  sensor_metric_11     40498 non-null  float32
 31  sensor_metric_12     40497 non-null  float32
 32  sensor_metric_13     40496 non-null  float32
 33  sensor_metric_14     40496 non-null  float32
 34  sensor_metric_15     40497 non-null  float32
 35  sensor_metric_16     40494 non-null  float32
 36  sensor_metric_17     40493 non-null  float32
 37  sensor_metric_18     40496 non-null  float32
 38  sensor_metric_19     40497 non-null  float32
 39  sensor_metric_20     40494 non-null  float32
 40  sensor_metric_21     40495 non-null  float32
 41  sensor_metric_22     40500 non-null  float32
 42  sensor_metric_23     40496 non-null  float32
 43  sensor_metric_24     40495 non-null  float32
 44  sensor_metric_25     40494 non-null  float32
 45  sensor_metric_26     40498 non-null  float32
 46  sensor_metric_27     40496 non-null  float32
 47  sensor_metric_28     40499 non-null  float32
 48  sensor_metric_29     40499 non-null  float32
 49  sensor_metric_30     40497 non-null  float32
dtypes: Int16(1), category(7), float16(7), float32(30), float64(1), int8(1), str(3)
memory usage: 12.1 MB

In [18]:
# startdize columns Name
df.columns

Index(['dog_id', 'dog_name', 'breed', 'age_years', 'weight_kg', 'height_cm',
       'color', 'vaccinated', 'neutered', 'owner_city', 'owner_age',
       'owner_income', 'diet_type', 'daily_walk_minutes', 'barks_per_day',
       'vet_visits_per_year', 'last_vet_visit', 'adoption_date',
       'favorite_toy', 'training_level', 'sensor_metric_1', 'sensor_metric_2',
       'sensor_metric_3', 'sensor_metric_4', 'sensor_metric_5',
       'sensor_metric_6', 'sensor_metric_7', 'sensor_metric_8',
       'sensor_metric_9', 'sensor_metric_10', 'sensor_metric_11',
       'sensor_metric_12', 'sensor_metric_13', 'sensor_metric_14',
       'sensor_metric_15', 'sensor_metric_16', 'sensor_metric_17',
       'sensor_metric_18', 'sensor_metric_19', 'sensor_metric_20',
       'sensor_metric_21', 'sensor_metric_22', 'sensor_metric_23',
       'sensor_metric_24', 'sensor_metric_25', 'sensor_metric_26',
       'sensor_metric_27', 'sensor_metric_28', 'sensor_metric_29',
       'sensor_metric_30'],
      dtype='str')

In [19]:
df.columns = (   # Apply string functions to ALL column names at once
    df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
)

# 1. Removing extra spaces
# 2. Converting to lowercase
# 3. Replacing spaces with underscores

In [20]:
import numpy as np

df = df.apply(lambda col: col.str.lower() if col.dtype == "object" else col)
# IF column is string → clean it
# ELSE → return it as-is

df.replace(
    ["unknown", "?", "na", "n/a", "none", "nan", ""],
    np.nan,
    inplace=True
)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,vaccinated,neutered,owner_city,...,sensor_metric_21,sensor_metric_22,sensor_metric_23,sensor_metric_24,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30
0,3945,Buddy,Husky,20,11.062500,NaN,Golden,NaN,NaN,Dubai,...,42.046650,55.209476,27.954712,62.081322,66.403999,20.830124,6.746516,5.097813,25.193275,33.763477
1,1591,Lola,Beagle,8,13.281250,25.734375,Mixed,Yes,Yes,Paris,...,69.438133,45.341789,63.001842,49.874069,20.190556,45.460693,36.659966,30.067049,81.168221,64.471970
2,4939,Buddy,Mixed,4,22.703125,4.578125,Golden,No,Yes,Berlin,...,14.018924,43.912491,13.917442,62.724941,43.692993,40.149246,79.186752,54.256184,54.851925,43.594223
3,3530,Buddy,Beagle,1,NaN,8.632812,Black,No,No,London,...,76.676262,39.718441,39.937325,93.026024,54.221989,91.620667,32.611008,63.462109,42.238510,62.923832
4,3300,Lola,Bulldog,6,15.000000,20.296875,Mixed,Yes,NaN,Paris,...,68.746674,33.595722,50.744678,22.772690,41.675507,59.867676,46.803925,73.911041,73.070656,81.359566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40495,1382,Toby,Beagle,-1,13.648438,21.578125,Brown,Yes,No,London,...,72.104675,46.043064,44.214748,32.617981,30.950027,43.564865,73.710327,30.875631,43.570354,27.253746
40496,1750,Bailey,Pug,19,25.734375,-5.781250,NaN,Yes,No,Tokyo,...,63.502323,70.973869,41.977615,40.468502,40.876026,50.241798,101.631073,48.507492,39.200420,86.230766
40497,4708,Lola,Poodle,15,NaN,NaN,Black,NaN,No,Berlin,...,36.719414,49.260269,91.072876,44.141102,67.894440,41.541821,45.616402,26.418215,21.016773,30.849703
40498,1021,Milo,Beagle,22,19.890625,NaN,Brown,Yes,No,Tokyo,...,25.300484,10.827934,72.240448,34.707882,22.882265,74.061638,27.992924,63.178181,31.946941,45.940651
40499,3853,Duke,Mixed,16,-5.148438,11.812500,White,NaN,No,Paris,...,8.643709,46.071217,72.350708,65.281746,36.957802,58.948601,54.728722,62.683960,34.534439,72.623604

In [ ]:
# Convert Numeric Col stored as Objects 
# I have Alrdy onverted them above its just for practice 

# numeric_cols = [
#     "weight_cm", "height_cm","owner_age",
#     "daily_walk_minutes", "barks_per_day",
#     "vet_visits_per_year"
# ]

# for col in numeric_cols:
#     df[col] = pd.to_numeric(df[col], errors="coerce").astype("int16")

In [21]:
# remove duplicate rows
df.drop_duplicates(inplace=True)

# Dealing with Impossible Values
- Invalid Values 
- Values that can not Exist i.e age in -ve 

what we would: Find invalid (impossible) values → replace them with NaN

            df.loc[condition, "weight_kg"]

In [ ]:
df.loc[df["weight_kg"] <= 0, "weight_kg"] = np.nan
df.loc[df["weight_kg"] > 100, "weight_kg"] = np.nan

df.loc[ ( df["height_cm"] ) <= 0 & (df["height_cm"] > 50 ), "height_cm" ] = np.nan
df.loc [ (df["age_years"] <= 0 ) & ( df["age_years"] > 30 ), "age_years"] = np.nan
df.loc[ (df["owner_age"] <= 0) & (df["owner_age"] > 120), "owner_age"] = np.nan

In [23]:
df.head(3)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,vaccinated,neutered,owner_city,...,sensor_metric_21,sensor_metric_22,sensor_metric_23,sensor_metric_24,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30
0,3945,Buddy,Husky,20.0,11.062500,NaN,Golden,NaN,NaN,Dubai,...,42.046650,55.209476,27.954712,62.081322,66.403999,20.830124,6.746516,5.097813,25.193275,33.763477
1,1591,Lola,Beagle,8.0,13.281250,25.734375,Mixed,Yes,Yes,Paris,...,69.438133,45.341789,63.001842,49.874069,20.190556,45.460693,36.659966,30.067049,81.168221,64.471970
2,4939,Buddy,Mixed,4.0,22.703125,4.578125,Golden,No,Yes,Berlin,...,14.018924,43.912491,13.917442,62.724941,43.692993,40.149246,79.186752,54.256184,54.851925,43.594223

# Again Check Missing Values

In [24]:
df.isnull().sum().sort_values(ascending = False)

adoption_date          40000
training_level         15927
vaccinated             13431
favorite_toy           13365
neutered               13268
height_cm               8247
weight_kg               8246
diet_type               6683
color                   6603
vet_visits_per_year     2384
owner_age                912
barks_per_day            357
daily_walk_minutes       205
sensor_metric_1            7
sensor_metric_17           7
sensor_metric_16           6
sensor_metric_20           6
sensor_metric_25           6
sensor_metric_9            5
sensor_metric_24           5
sensor_metric_21           5
sensor_metric_8            5
sensor_metric_23           4
sensor_metric_13           4
sensor_metric_14           4
sensor_metric_18           4
sensor_metric_27           4
sensor_metric_2            3
sensor_metric_15           3
sensor_metric_30           3
sensor_metric_4            3
sensor_metric_5            3
sensor_metric_10           3
sensor_metric_19           3
sensor_metric_12           3
sensor_metric_26           2
sensor_metric_11           2
sensor_metric_7            2
sensor_metric_3            1
sensor_metric_28           1
owner_income               1
sensor_metric_6            1
sensor_metric_29           1
age_years                  0
last_vet_visit             0
owner_city                 0
dog_id                     0
dog_name                   0
breed                      0
sensor_metric_22           0
dtype: int64

In [25]:
# Find percentge of misiing Value
( df.isnull().sum() / len(df)) * 100

dog_id                   0.0000
dog_name                 0.0000
breed                    0.0000
age_years                0.0000
weight_kg               20.6150
height_cm               20.6175
color                   16.5075
vaccinated              33.5775
neutered                33.1700
owner_city               0.0000
owner_age                2.2800
owner_income             0.0025
diet_type               16.7075
daily_walk_minutes       0.5125
barks_per_day            0.8925
vet_visits_per_year      5.9600
last_vet_visit           0.0000
adoption_date          100.0000
favorite_toy            33.4125
training_level          39.8175
sensor_metric_1          0.0175
sensor_metric_2          0.0075
sensor_metric_3          0.0025
sensor_metric_4          0.0075
sensor_metric_5          0.0075
sensor_metric_6          0.0025
sensor_metric_7          0.0050
sensor_metric_8          0.0125
sensor_metric_9          0.0125
sensor_metric_10         0.0075
sensor_metric_11         0.0050
sensor_metric_12         0.0075
sensor_metric_13         0.0100
sensor_metric_14         0.0100
sensor_metric_15         0.0075
sensor_metric_16         0.0150
sensor_metric_17         0.0175
sensor_metric_18         0.0100
sensor_metric_19         0.0075
sensor_metric_20         0.0150
sensor_metric_21         0.0125
sensor_metric_22         0.0000
sensor_metric_23         0.0100
sensor_metric_24         0.0125
sensor_metric_25         0.0150
sensor_metric_26         0.0050
sensor_metric_27         0.0100
sensor_metric_28         0.0025
sensor_metric_29         0.0025
sensor_metric_30         0.0075
dtype: float64

# Handling Missing Values 
- Drop Cols using a set Threshold 
- Then Fill The Remaining Data

In [26]:
# Drop col where mssing values is more than 32 percent 

threshold = len(df) * 0.68 # keep col that have atleast 68% non missing valued
df = df.dropna(axis=1, thresh=threshold)

In [27]:
# again Check percentage
( df.isnull().sum() / len(df)) * 100

dog_id                  0.0000
dog_name                0.0000
breed                   0.0000
age_years               0.0000
weight_kg              20.6150
height_cm              20.6175
color                  16.5075
owner_city              0.0000
owner_age               2.2800
owner_income            0.0025
diet_type              16.7075
daily_walk_minutes      0.5125
barks_per_day           0.8925
vet_visits_per_year     5.9600
last_vet_visit          0.0000
sensor_metric_1         0.0175
sensor_metric_2         0.0075
sensor_metric_3         0.0025
sensor_metric_4         0.0075
sensor_metric_5         0.0075
sensor_metric_6         0.0025
sensor_metric_7         0.0050
sensor_metric_8         0.0125
sensor_metric_9         0.0125
sensor_metric_10        0.0075
sensor_metric_11        0.0050
sensor_metric_12        0.0075
sensor_metric_13        0.0100
sensor_metric_14        0.0100
sensor_metric_15        0.0075
sensor_metric_16        0.0150
sensor_metric_17        0.0175
sensor_metric_18        0.0100
sensor_metric_19        0.0075
sensor_metric_20        0.0150
sensor_metric_21        0.0125
sensor_metric_22        0.0000
sensor_metric_23        0.0100
sensor_metric_24        0.0125
sensor_metric_25        0.0150
sensor_metric_26        0.0050
sensor_metric_27        0.0100
sensor_metric_28        0.0025
sensor_metric_29        0.0025
sensor_metric_30        0.0075
dtype: float64

In [28]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
Index: 40000 entries, 0 to 40499
Data columns (total 45 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40000 non-null  Int16
 1   dog_name             40000 non-null  str
 2   breed                40000 non-null  category
 3   age_years            40000 non-null  float64
 4   weight_kg            31754 non-null  float16
 5   height_cm            31753 non-null  float16
 6   color                33397 non-null  category
 7   owner_city           40000 non-null  category
 8   owner_age            39088 non-null  float16
 9   owner_income         39999 non-null  float16
 10  diet_type            33317 non-null  category
 11  daily_walk_minutes   39795 non-null  float16
 12  barks_per_day        39643 non-null  float16
 13  vet_visits_per_year  37616 non-null  float16
 14  last_vet_visit       40000 non-null  str
 15  sensor_metric_1      39993 non-null  float32
 16  sensor_metric_2      39997 non-null  float32
 17  sensor_metric_3      39999 non-null  float32
 18  sensor_metric_4      39997 non-null  float32
 19  sensor_metric_5      39997 non-null  float32
 20  sensor_metric_6      39999 non-null  float32
 21  sensor_metric_7      39998 non-null  float32
 22  sensor_metric_8      39995 non-null  float32
 23  sensor_metric_9      39995 non-null  float32
 24  sensor_metric_10     39997 non-null  float32
 25  sensor_metric_11     39998 non-null  float32
 26  sensor_metric_12     39997 non-null  float32
 27  sensor_metric_13     39996 non-null  float32
 28  sensor_metric_14     39996 non-null  float32
 29  sensor_metric_15     39997 non-null  float32
 30  sensor_metric_16     39994 non-null  float32
 31  sensor_metric_17     39993 non-null  float32
 32  sensor_metric_18     39996 non-null  float32
 33  sensor_metric_19     39997 non-null  float32
 34  sensor_metric_20     39994 non-null  float32
 35  sensor_metric_21     39995 non-null  float32
 36  sensor_metric_22     40000 non-null  float32
 37  sensor_metric_23     39996 non-null  float32
 38  sensor_metric_24     39995 non-null  float32
 39  sensor_metric_25     39994 non-null  float32
 40  sensor_metric_26     39998 non-null  float32
 41  sensor_metric_27     39996 non-null  float32
 42  sensor_metric_28     39999 non-null  float32
 43  sensor_metric_29     39999 non-null  float32
 44  sensor_metric_30     39997 non-null  float32
dtypes: Int16(1), category(4), float16(7), float32(30), float64(1), str(2)
memory usage: 10.3 MB

# Filling Missing Values

- Fill Missing Values:

    - it depends on Datatype

            df["age"].fillna(df["age"].mean())  -->> for values use median/mean etc

            df["city"].fillna(df["city"].mode()[0]) -->> for catigorical use mode() ( most common values)


            df["review_text"].fillna("No review")  -->> for text use place holders

In [29]:
# Owner age 
df["owner_age"] = df["owner_age"].fillna(df["owner_age"].median())

In [30]:
# Owner income 
df["owner_income"] = df["owner_income"].fillna(df["owner_income"].median())

In [31]:
# Daily Waliks per minutes
df["daily_walk_minutes"] = df["daily_walk_minutes"].fillna(
    df["daily_walk_minutes"].median()
)

In [32]:
# barks per Day
df["barks_per_day"] = df["barks_per_day"].fillna(df["barks_per_day"].median())

In [33]:
df["vet_visits_per_year"] = df["vet_visits_per_year"].fillna(df["vet_visits_per_year"].median())

In [34]:
# as differnt breed have different sizes .. global mean would be wrong
# so we group them by breed then in find mean of each group
# Labrador → fill using Labrador median
# Bulldog → fill using Bulldog median

df["weight_kg"] = df.groupby("breed")["weight_kg"].transform( lambda x : x.fillna(x.median()))

In [35]:
df["height_cm"] = df.groupby("breed")["height_cm"].transform( lambda x : x.fillna(x.median()))

In [36]:
# Categorical Cols are fill with most frequent category

df["diet_type"] = df['diet_type'].fillna(df["diet_type"].mode()[0])

In [37]:
df["color"] = df["color"].fillna(df["color"].mode()[0])

In [38]:
# there are many sensor col so handle altogather
sensor_col = [col for col in df.columns if "sensor_metric" in col]

for col in sensor_col:
    df[col] = df[col].fillna(df[col].mean())

In [39]:
# now check Values
df.info()
# no missing values

<class 'pandas.DataFrame'>
Index: 40000 entries, 0 to 40499
Data columns (total 45 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dog_id               40000 non-null  Int16
 1   dog_name             40000 non-null  str
 2   breed                40000 non-null  category
 3   age_years            40000 non-null  float64
 4   weight_kg            40000 non-null  float16
 5   height_cm            40000 non-null  float16
 6   color                40000 non-null  category
 7   owner_city           40000 non-null  category
 8   owner_age            40000 non-null  float16
 9   owner_income         40000 non-null  float16
 10  diet_type            40000 non-null  category
 11  daily_walk_minutes   40000 non-null  float16
 12  barks_per_day        40000 non-null  float16
 13  vet_visits_per_year  40000 non-null  float16
 14  last_vet_visit       40000 non-null  str
 15  sensor_metric_1      40000 non-null  float32
 16  sensor_metric_2      40000 non-null  float32
 17  sensor_metric_3      40000 non-null  float32
 18  sensor_metric_4      40000 non-null  float32
 19  sensor_metric_5      40000 non-null  float32
 20  sensor_metric_6      40000 non-null  float32
 21  sensor_metric_7      40000 non-null  float32
 22  sensor_metric_8      40000 non-null  float32
 23  sensor_metric_9      40000 non-null  float32
 24  sensor_metric_10     40000 non-null  float32
 25  sensor_metric_11     40000 non-null  float32
 26  sensor_metric_12     40000 non-null  float32
 27  sensor_metric_13     40000 non-null  float32
 28  sensor_metric_14     40000 non-null  float32
 29  sensor_metric_15     40000 non-null  float32
 30  sensor_metric_16     40000 non-null  float32
 31  sensor_metric_17     40000 non-null  float32
 32  sensor_metric_18     40000 non-null  float32
 33  sensor_metric_19     40000 non-null  float32
 34  sensor_metric_20     40000 non-null  float32
 35  sensor_metric_21     40000 non-null  float32
 36  sensor_metric_22     40000 non-null  float32
 37  sensor_metric_23     40000 non-null  float32
 38  sensor_metric_24     40000 non-null  float32
 39  sensor_metric_25     40000 non-null  float32
 40  sensor_metric_26     40000 non-null  float32
 41  sensor_metric_27     40000 non-null  float32
 42  sensor_metric_28     40000 non-null  float32
 43  sensor_metric_29     40000 non-null  float32
 44  sensor_metric_30     40000 non-null  float32
dtypes: Int16(1), category(4), float16(7), float32(30), float64(1), str(2)
memory usage: 6.6 MB

# Feature Engineering
- Creating new meaningful columns from existing data to improve analysis / ML models

1. Features must add information (not noise)
2. Combine columns intelligently
3. Think in terms of behavior / patterns
4. Domain understanding > random features

In [43]:
# Create heavy_dog col
df["is_heavy_dog"] = df["weight_kg"] > 35
# create bmi_like col
df["bmi_like"] = df["weight_kg"] / ( df["height_cm"] / 100 ) **2
# create activity Core col
df["activity_core"] = df["daily_walk_minutes"] * df["age_years"]
# high income owner
df["high_income_owner"] = df["owner_income"] > df["owner_income"].median()

In [44]:
df.head(3)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner
0,3945,Buddy,Husky,20.0,11.062500,20.203125,Golden,Dubai,65.0,inf,...,66.403999,20.830124,6.746516,5.097813,25.193275,33.763477,False,271.25,500.0,False
1,1591,Lola,Beagle,8.0,13.281250,25.734375,Mixed,Paris,49.0,30800.0,...,20.190556,45.460693,36.659966,30.067049,81.168221,64.471970,False,200.50,1032.0,False
2,4939,Buddy,Mixed,4.0,22.703125,4.578125,Golden,Berlin,26.0,inf,...,43.692993,40.149246,79.186752,54.256184,54.851925,43.594223,False,10832.00,156.0,False

# Analysis

In [45]:
# top 3 heavist dogs
df.sort_values("weight_kg", ascending=False).head(3)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner
21050,3657,Luna,Labrador,15.0,59.00000,20.265625,Black,Paris,30.0,inf,...,75.444786,59.438229,44.088108,57.573330,42.510201,57.369579,True,1436.0,1620.0,False
33985,3731,Bear,Poodle,-2.0,58.37500,22.968750,Black,Toronto,71.0,inf,...,45.022030,67.726212,57.747723,56.173286,75.875763,51.103519,True,1106.0,-160.0,False
6396,4641,Bear,Golden Retriever,24.0,58.34375,14.398438,Mixed,Dubai,53.0,inf,...,48.795238,67.222916,64.017624,86.214455,66.058075,18.789122,True,2812.0,3552.0,False

In [46]:
# most common breed
df["breed"].value_counts().head(3)

breed
Boxer              3693
German Shepherd    3666
Mixed              3651
Name: count, dtype: int64

In [47]:
# highiest Activity dogs
df.sort_values("activity_core", ascending=False).head(3)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner
16247,2167,Duke,Labrador,24.0,13.890625,27.421875,Black,Lahore,33.0,30672.0,...,39.543667,60.950222,49.468594,60.414349,92.954361,56.094547,False,184.75,4296.0,False
39095,3570,Charlie,Boxer,24.0,20.375000,4.000000,White,Lahore,81.0,57664.0,...,37.865879,60.395279,53.144142,4.380833,25.274290,64.857162,False,12736.00,4296.0,False
15743,4129,Max,Poodle,24.0,5.441406,9.132812,Brown,London,80.0,inf,...,3.724291,46.603687,75.607132,59.869781,50.035904,71.574310,False,652.50,4296.0,False

In [48]:
# Most Common diet
df["diet_type"].value_counts().head(3)

diet_type
Dry    13521
Wet     6634
Raw     6627
Name: count, dtype: int64

In [53]:
# rare breed
df["breed"].value_counts(ascending=True).head()

breed
Husky               3600
Golden Retriever    3610
Bulldog             3613
Unknown             3617
Labrador            3627
Name: count, dtype: int64

In [54]:
# Heavy and Seneror Dogs
df[ (df["weight_kg"] > 35 ) & ( df["age_years"] > 10 )].head(2)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner
24,1501,Lucy,Mixed,13.0,39.15625,6.980469,Black,Berlin,42.0,20640.0,...,65.754593,80.326286,47.339249,37.469582,61.373047,40.007572,True,8032.0,1781.0,False
42,4650,Bear,Husky,11.0,39.46875,0.810059,Black,Sydney,36.0,inf,...,44.702503,40.634846,41.450272,51.580082,13.610462,76.557404,True,inf,946.0,False

In [57]:
# high incomce onwer + active dog

df[ (df["owner_income"] > 10000) & ( df["daily_walk_minutes"] > 60)].head(2)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner
1,1591,Lola,Beagle,8.0,13.28125,25.734375,Mixed,Paris,49.0,30800.0,...,20.190556,45.460693,36.659966,30.067049,81.168221,64.471970,False,200.5,1032.0,False
3,3530,Buddy,Beagle,1.0,20.68750,8.632812,Black,London,32.0,inf,...,54.221989,91.620667,32.611008,63.462109,42.238510,62.923832,False,2776.0,74.0,False

In [59]:
# dogs from top3 cities 
top_3_cities = df["owner_city"].value_counts().head(3).index

df[ df["owner_city"].isin(top_3_cities)].head()

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_25,sensor_metric_26,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner
1,1591,Lola,Beagle,8.0,13.281250,25.734375,Mixed,Paris,49.0,30800.0,...,20.190556,45.460693,36.659966,30.067049,81.168221,64.471970,False,200.500,1032.0,False
2,4939,Buddy,Mixed,4.0,22.703125,4.578125,Golden,Berlin,26.0,inf,...,43.692993,40.149246,79.186752,54.256184,54.851925,43.594223,False,10832.000,156.0,False
4,3300,Lola,Bulldog,6.0,15.000000,20.296875,Mixed,Paris,48.0,47200.0,...,41.675507,59.867676,46.803925,73.911041,73.070656,81.359566,False,364.000,414.0,False
9,2121,Buddy,Husky,20.0,15.898438,25.062500,Mixed,Berlin,22.0,45376.0,...,65.520073,75.753311,43.476746,62.410126,34.441647,25.370102,False,252.875,380.0,False
14,3381,Duke,Pug,-2.0,20.281250,31.437500,Mixed,Berlin,42.0,55296.0,...,32.177517,49.028732,58.967869,43.599827,94.883827,47.133923,False,205.125,20.0,False

In [ ]:
# for each dog subtract the avg weight of its breed
df["weight_vs_breed"] = df["weight_kg"] - df.groupby("breed")["weight_kg"].transform("mean")
# for each dog subtract avg activityo of its breed

df["activity_vs_breed"] = df["activity_core"] - df.groupby("breed")["activity_core"].transform("mean")

df.head(1) # some values will be negative so handle it

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner,weight_vs_breed,activity_vs_breed
0,3945,Buddy,Husky,20.0,11.0625,20.203125,Golden,Dubai,65.0,inf,...,6.746516,5.097813,25.193275,33.763477,False,271.25,500.0,False,-9.210806,-464.128889

In [75]:

df.loc[ df["activity_vs_breed"] <= 0 , "activity_vs_breed"] = np.nan
df.loc[ df["weight_vs_breed"] <= 0, "weight_vs_breed"] = np.nan

# fiiling values
df["activity_vs_breed"] = df["activity_vs_breed"].fillna(df["activity_vs_breed"].median())
df["weight_vs_breed"] = df["weight_vs_breed"].fillna(df["weight_vs_breed"].median())

df.head(3)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,dog_id,dog_name,breed,age_years,weight_kg,height_cm,color,owner_city,owner_age,owner_income,...,sensor_metric_27,sensor_metric_28,sensor_metric_29,sensor_metric_30,is_heavy_dog,bmi_like,activity_core,high_income_owner,weight_vs_breed,activity_vs_breed
0,3945,Buddy,Husky,20.0,11.062500,20.203125,Golden,Dubai,65.0,inf,...,6.746516,5.097813,25.193275,33.763477,False,271.25,500.0,False,7.818634,1024.369260
1,1591,Lola,Beagle,8.0,13.281250,25.734375,Mixed,Paris,49.0,30800.0,...,36.659966,30.067049,81.168221,64.471970,False,200.50,1032.0,False,7.818634,99.833654
2,4939,Buddy,Mixed,4.0,22.703125,4.578125,Golden,Berlin,26.0,inf,...,79.186752,54.256184,54.851925,43.594223,False,10832.00,156.0,False,2.365185,1024.369260

In [81]:
# breed with hieghest avg activty
df.groupby("breed")["activity_core"].mean().sort_values(ascending=False)

breed
Husky               964.128889
Pug                 940.143719
Golden Retriever    937.982548
Unknown             933.687033
Beagle              932.166346
Boxer               927.853236
Mixed               926.234182
Poodle              916.065659
Labrador            908.341880
Bulldog             906.078605
German Shepherd     892.056465
Name: activity_core, dtype: float64

In [82]:
# city with hiesght income variance
df.groupby("owner_city")["owner_income"].std().sort_values(ascending=False)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/pandas/io/formats/format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

owner_city
Berlin     NaN
Dubai      NaN
Karachi    NaN
Lahore     NaN
London     NaN
New York   NaN
Paris      NaN
Sydney     NaN
Tokyo      NaN
Toronto    NaN
Name: owner_income, dtype: float16