In [1]:
import pandas as pd
import numpy as np

In [3]:
power = pd.Series(
    [95, 94, 80, 92],
    index=["Naruto", "Sasuke", "Sakura", "Kakashi"]
)

power

Naruto     95
Sasuke     94
Sakura     80
Kakashi    92
dtype: int64

In [9]:
power.loc["Naruto"]
power.loc["Kakashi"]
power.iloc[0]
power.iloc[0:4]

Naruto     95
Sasuke     94
Sakura     80
Kakashi    92
dtype: int64

# Data Frame

In [2]:
# using 2d list
std_data = [ 
    [100,90,45],
    [43,78,43],
    [93,32,90],
    [22,76,32]
]

df = pd.DataFrame(std_data, columns=["iq", "marks", "age"])
df

    iq  marks  age
0  100     90   45
1   43     78   43
2   93     32   90
3   22     76   32

In [21]:
df.shape
df.columns
df.values
df.index
df.info()
df.describe()
df.isnull().sum()
df.duplicated()
df.iloc[0:2,0]
df.iloc[1:4, 0:3]

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   iq      4 non-null      int64
 1   marks   4 non-null      int64
 2   age     4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes

   iq  marks  age
1  43     78   43
2  93     32   90
3  22     76   32

In [3]:
df

    iq  marks  age
0  100     90   45
1   43     78   43
2   93     32   90
3   22     76   32

In [4]:
df["iq+age"] = df['iq'] + df["age"]
df["mk"] = df["iq"] + df["marks"]
df

    iq  marks  age  iq+age   mk
0  100     90   45     145  190
1   43     78   43      86  121
2   93     32   90     183  125
3   22     76   32      54   98

In [13]:
# droping col
df.drop("iq+age" , axis=1)
df.drop("mk",  axis=1)
df.drop("iq" ,axis=1)
df.drop("marks", axis=1)
df.drop(3)
df.drop(1).reset_index(drop=True)

    iq  marks  age  iq+age   mk
0  100     90   45     145  190
1   93     32   90     183  125
2   22     76   32      54   98

In [14]:
movies = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/movies.csv")
ipl = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/ipl-matches.csv")

In [15]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [24]:
ipl['City'].value_counts()
ipl["Team1"].value_counts()
ipl["Team2"].value_counts(ascending=True)
movies.sort_values("title_x").head()
movies.sort_values(["actors"]).head()
movies.sort_values(["imdb_id"]).head()
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [29]:
data = {
    "name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Eve", None],
    "score": [90, 85, 90, 90, 85, 70, np.nan],
    "year": [2021, 2020, 2021, 2021, 2020, 2019, 2022],
    "city": ["NY", "LA", "NY", "NY", "LA", None, "SF"]
}

df = pd.DataFrame(data)
print(df)

      name  score  year city
0    Alice   90.0  2021   NY
1      Bob   85.0  2020   LA
2  Charlie   90.0  2021   NY
3    Alice   90.0  2021   NY
4      Bob   85.0  2020   LA
5      Eve   70.0  2019  NaN
6      NaN    NaN  2022   SF

In [ ]:
df['name'].value_counts()
df.sort_values(["score"]).reset_index()

   index     name  score  year city
0      5      Eve   70.0  2019  NaN
1      1      Bob   85.0  2020   LA
2      4      Bob   85.0  2020   LA
3      0    Alice   90.0  2021   NY
4      3    Alice   90.0  2021   NY
5      2  Charlie   90.0  2021   NY
6      6      NaN    NaN  2022   SF

In [39]:
print( df.isnull())
print( df.dropna())
df.fillna({"score": 0, "name": "unknown"})

    name  score   year   city
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False   True
6   True   True  False  False
      name  score  year city
0    Alice   90.0  2021   NY
1      Bob   85.0  2020   LA
2  Charlie   90.0  2021   NY
3    Alice   90.0  2021   NY
4      Bob   85.0  2020   LA

      name  score  year city
0    Alice   90.0  2021   NY
1      Bob   85.0  2020   LA
2  Charlie   90.0  2021   NY
3    Alice   90.0  2021   NY
4      Bob   85.0  2020   LA
5      Eve   70.0  2019  NaN
6  unknown    0.0  2022   SF

In [40]:
# imdb-top-1000
movies = pd.read_csv("imdb-top-1000.csv")
movies.head(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0

In [43]:
genre = movies.groupby("Genre")
genre.max().head()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0

In [ ]:
movies.groupby("Genre")["Gross"].sum().sort_values(ascending=False).head(2)
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values().sample()

Genre
Film-Noir    7.966667
Name: IMDB_Rating, dtype: float64

In [51]:
movies.groupby("Genre").get_group("Action")
movies.groupby("Genre").get_group("Comedy")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
51,Modern Times,1936,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,217881,163245.0,96.0
52,City Lights,1931,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,167839,19181.0,99.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
...,...,...,...,...,...,...,...,...,...,...
977,The Naked Gun: From the Files of Police Squad!,1988,85,Comedy,7.6,David Zucker,Leslie Nielsen,152871,78756177.0,76.0
978,"Planes, Trains & Automobiles",1987,93,Comedy,7.6,John Hughes,Steve Martin,124773,49530280.0,72.0
989,The Long Goodbye,1973,112,Comedy,7.6,Robert Altman,Elliott Gould,26337,959000.0,87.0
994,A Hard Day's Night,1964,87,Comedy,7.6,Richard Lester,John Lennon,40351,13780024.0,96.0
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0

In [54]:
genre.agg(
    {
        "Runtime": "min",
        "Gross": "max",
        "Metascore": "mean"
     
     }
)

           Runtime        Gross  Metascore
Genre
Action          45  936662225.0  73.419580
Adventure       88  874211619.0  78.437500
Animation       71  873839108.0  81.093333
Biography       93  753585104.0  76.240506
Comedy          68  886752933.0  78.720000
Crime           80  790482117.0  77.080460
Drama           64  924558264.0  79.701245
Family         100  435110554.0  79.000000
Fantasy         76  445151978.0        NaN
Film-Noir      100  123353292.0  95.666667
Horror          71  298791505.0  80.000000
Mystery         96  474203697.0  79.125000
Thriller       108   17550741.0  81.000000
Western        132   31800000.0  78.250000

In [56]:
genre.agg(
    {
        "Runtime": ["min", "max"],
        "Gross": ["min", "max", "mean"]
    }
)

          Runtime             Gross
              min  max          min          max          mean
Genre
Action         45  321       3296.0  936662225.0  1.897224e+08
Adventure      88  228      61001.0  874211619.0  1.319017e+08
Animation      71  137     128985.0  873839108.0  1.784326e+08
Biography      93  209      21877.0  753585104.0  9.404952e+07
Comedy         68  188       1305.0  886752933.0  1.010572e+08
Crime          80  229       6013.0  790482117.0  7.899656e+07
Drama          64  242       3600.0  924558264.0  1.225259e+08
Family        100  115    4000000.0  435110554.0  2.195553e+08
Fantasy        76   94  337574718.0  445151978.0  3.913633e+08
Film-Noir     100  108     449191.0  123353292.0  4.197018e+07
Horror         71  122      89029.0  298791505.0  9.405902e+07
Mystery        96  138    1035953.0  474203697.0  1.047014e+08
Thriller      108  108   17550741.0   17550741.0  1.755074e+07
Western       132  165    5321508.0   31800000.0  1.455538e+07

In [57]:
students = pd.read_csv("students.csv")
regs = pd.read_csv("courses.csv")
nov = pd.read_csv("reg-month1.csv")
dec = pd.read_csv("reg-month2.csv")

In [58]:
pd.concat([nov, dec])

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [59]:
pd.concat([nov, dec], ignore_index= True)

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [60]:
pd.concat([nov, dec], keys=["nov", "dec"])

        student_id  course_id
nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [62]:
df = pd.read_csv("birds_noisy_dataset.csv")

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 90 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bird_id           80000 non-null  str
 1   species           74319 non-null  str
 2   family            74239 non-null  str
 3   continent         74429 non-null  str
 4   country           74215 non-null  str
 5   habitat           74241 non-null  str
 6   diet              74283 non-null  str
 7   wing_span_cm      72016 non-null  float64
 8   weight_g          71926 non-null  float64
 9   beak_length_mm    71906 non-null  float64
 10  tail_length_cm    71970 non-null  float64
 11  age_years         72088 non-null  float64
 12  gender            74243 non-null  str
 13  migratory         74317 non-null  str
 14  observation_year  75909 non-null  float64
 15  observer_id       39889 non-null  str
 16  location_lat      71974 non-null  float64
 17  location_long     72031 non-null  float64
 18  weather           74186 non-null  str
 19  temperature_c     71968 non-null  float64
 20  feature_1         71471 non-null  str
 21  feature_2         71347 non-null  str
 22  feature_3         71364 non-null  str
 23  feature_4         71365 non-null  str
 24  feature_5         71393 non-null  str
 25  feature_6         71454 non-null  str
 26  feature_7         71409 non-null  str
 27  feature_8         71449 non-null  str
 28  feature_9         71349 non-null  str
 29  feature_10        71599 non-null  str
 30  feature_11        71457 non-null  str
 31  feature_12        71489 non-null  str
 32  feature_13        71476 non-null  str
 33  feature_14        71285 non-null  str
 34  feature_15        71481 non-null  str
 35  feature_16        71259 non-null  str
 36  feature_17        71356 non-null  str
 37  feature_18        71560 non-null  str
 38  feature_19        71456 non-null  str
 39  feature_20        71396 non-null  str
 40  feature_21        71522 non-null  str
 41  feature_22        71442 non-null  str
 42  feature_23        71491 non-null  str
 43  feature_24        71521 non-null  str
 44  feature_25        71297 non-null  str
 45  feature_26        71525 non-null  str
 46  feature_27        71335 non-null  str
 47  feature_28        71249 non-null  str
 48  feature_29        71334 non-null  str
 49  feature_30        71437 non-null  str
 50  feature_31        71435 non-null  str
 51  feature_32        71459 non-null  str
 52  feature_33        71468 non-null  str
 53  feature_34        71562 non-null  str
 54  feature_35        71383 non-null  str
 55  feature_36        71531 non-null  str
 56  feature_37        71486 non-null  str
 57  feature_38        71482 non-null  str
 58  feature_39        71432 non-null  str
 59  feature_40        71395 non-null  str
 60  feature_41        71366 non-null  str
 61  feature_42        71643 non-null  str
 62  feature_43        71482 non-null  str
 63  feature_44        71472 non-null  str
 64  feature_45        71485 non-null  str
 65  feature_46        71370 non-null  str
 66  feature_47        71500 non-null  str
 67  feature_48        71503 non-null  str
 68  feature_49        71235 non-null  str
 69  feature_50        71558 non-null  str
 70  feature_51        71374 non-null  str
 71  feature_52        71470 non-null  str
 72  feature_53        71437 non-null  str
 73  feature_54        71408 non-null  str
 74  feature_55        71426 non-null  str
 75  feature_56        71458 non-null  str
 76  feature_57        71436 non-null  str
 77  feature_58        71454 non-null  str
 78  feature_59        71367 non-null  str
 79  feature_60        71475 non-null  str
 80  feature_61        71372 non-null  str
 81  feature_62        71489 non-null  str
 82  feature_63        71481 non-null  str
 83  feature_64        71406 non-null  str
 84  feature_65        71388 non-null  str
 85  feature_66        71392 non-null  str
 86  feature_67        71420 non-null  str
 87  feature_68        71444 non-null  str
 88  feature_69        71456 non-null  str
 89  feature_70        71481 non-null  str
dtypes: float64(9), str(81)
memory usage: 54.9 MB

In [67]:
df.isnull().sum()

bird_id          0
species       5681
family        5761
continent     5571
country       5785
              ...
feature_66    8608
feature_67    8580
feature_68    8556
feature_69    8544
feature_70    8519
Length: 90, dtype: int64

In [73]:
numeric_cols = [
    "wing_span_cm", "weight_g", "beak_length_mm", "tail_length_cm", 
    "age_years", "observation_year", "location_lat", "location_long", "temperature_c"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors= "coerce")


#ist Comprehension: [expression for item in iterable if condition]
feature_cols = [col for col in df.columns if "feature_" in col]
# put all those cols in list which have "feature_" in their name
for col in feature_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("float32")


# impossible Values 
df.loc[ (df["wing_span_cm"] <= 0) | (df["wing_span_cm"] > 100), "wing_span_cm"] = np.nan
df.loc[ (df["weight_g"] < 0) | ( df["weight_g"]), "weight_g"] = np.nan


df['diet'] = df['diet'].fillna(df['diet'].mode()[0])
df['migratory'] = df['migratory'].fillna(df['migratory'].mode()[0])
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

# Numeric
# Fill missing with median wing span, or median per species
df["wing_span_cm"] = df.groupby("species")["wing_span_cm"].transform( lambda x: x.fillna(x.median()))
df["weight_g"] = df.groupby("species")["weight_g"].transform( lambda x : x.fillna(x.median()))
df['beak_length_mm'] = df.groupby('species')['beak_length_mm'].transform(lambda x: x.fillna(x.median()))