In [1]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1,2,3], index=["a","b","c"])
print(s)

print( s['a'])
print( s['b'])

a    1
b    2
c    3
dtype: int64
1
2

In [6]:
index_val = [('a',2019), ('b',2020)]
s = pd.Series([1,2], index=index_val)

s['a']  # index_val = [('a',2019), ('b',2020)]

KeyError: 'a'

In [ ]:
# to solve above # creat Multi INdex from Tuples 
# pd.MultiIndex.from_tuples(tuples)

tuples = [ ('nov', 2020), ('nov', 2021), ('jan', 2002), ("jan", 2001)]
mul_index = pd.MultiIndex.from_tuples(tuples)

s = pd.Series([1,2,3,4], index = mul_index)

print(s)
print()
print( s["nov"])
print()
print( s["jan"] )
print(s[('jan', 2001)])
# now two levels of indexes are made level 0 and level 1
# Level 1 → jan 
# Level 2 → 2019

tuples = [('math',1), ('math',2), ('cs',1), ('cs',2)]
s = pd.Series([10,20,30,40], index=pd.MultiIndex.from_tuples(tuples))

nov  2020    1
     2021    2
jan  2002    3
     2001    4
dtype: int64

2020    1
2021    2
dtype: int64

2002    3
2001    4
dtype: int64
4

the above :

they are now is hiercal because there is one uppr level and and one lower level index

Folder → Subfolder → File

- nov/
   - 2019 → 1
   - 2020 → 2
- jan/
   - 2019 → 3
   - 2020 → 4

In [19]:
# another way to form Multi index is using from_product
# pd.MultiIndex.from_product([A, B])

idx = pd.MultiIndex.from_product( [
    ['cse', 'ece'],
    [2020,2022,2028]
])

s = pd.Series(range(1,7), index=idx)

s

cse  2020    1
     2022    2
     2028    3
ece  2020    4
     2022    5
     2028    6
dtype: int64

the above 

        pd.MultiIndex.from_product([A, B])

> Cartesian product (ALL combinations)

['cse','ece'] × [2019,2020,2021]

becomes

- (cse,2019)
- (cse,2020)
- (cse,2021)
- (ece,2019)
- (ece,2020)
- (ece,2021)

# stack vs Unstack

unstack() = convert inner index to columns

stack() = convert columns → index

In [22]:
index = pd.MultiIndex.from_product([
    ['A', 'B'],
    [1,2]
])

s = pd.Series([1,2,3,4], index = index)
s

A  1    1
   2    2
B  1    3
   2    4
dtype: int64

In [ ]:
df = s.unstack()
df # inner index becomes cols

   1  2
A  1  2
B  3  4

In [ ]:
df.stack() #  col becomes inner index

A  1    1
   2    2
B  1    3
   2    4
dtype: int64

In [26]:
index = pd.MultiIndex.from_product([
    ['A','B'],
    [1,2,3]
])

s = pd.Series(range(6), index=index)

print(s)
print()

df = s.unstack()
df

A  1    0
   2    1
   3    2
B  1    3
   2    4
   3    5
dtype: int64

   1  2  3
A  0  1  2
B  3  4  5

# Data Frames

In [30]:


index = pd.MultiIndex.from_product([
    ['cse','ece'],
    [2019,2020]
])

df = pd.DataFrame({
    'students': [100,120,80,90],
    'avg_package': [10,12,8,9]
}, index=index)

print(df)
print()
print (df.loc["cse"] )
print()
df.loc["ece"]

          students  avg_package
cse 2019       100           10
    2020       120           12
ece 2019        80            8
    2020        90            9

      students  avg_package
2019       100           10
2020       120           12

      students  avg_package
2019        80            8
2020        90            9

In [31]:
# multi index on columns 
cols = pd.MultiIndex.from_product([
    ["Hokage", "Akatsuki"],
    ["Missions", "Income"]
])

df2 = pd.DataFrame([
    [100,10,90,29],
    [120,34,90,22]
], index=[2020, 2021], columns=cols)

df2

       Hokage        Akatsuki
     Missions Income Missions Income
2020      100     10       90     29
2021      120     34       90     22

In [ ]:
df2["Hokage"]

      Missions  Income
2020       100      10
2021       120      34

In [33]:
df2["Hokage"]["Missions"]

2020    100
2021    120
Name: Missions, dtype: int64

In [35]:
df3 = pd.DataFrame(
    [
        [100,10,90,9],
        [120,12,95,10],
        [80,8,70,7],
        [90,9,75,8]
    ],
    index=pd.MultiIndex.from_product([['cse','ece'],[2019,2020]]),
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['students','avg_package']])
)

df3

            delhi               mumbai
         students avg_package students avg_package
cse 2019      100          10       90           9
    2020      120          12       95          10
ece 2019       80           8       70           7
    2020       90           9       75           8

In [37]:
df3.loc[('cse',2019)]

delhi   students       100
        avg_package     10
mumbai  students        90
        avg_package      9
Name: (cse, 2019), dtype: int64

# Pivot Table #

```python
df.pivot_table(
    index='sex',
    columns='smoker',
    values='total_bill',
    aggfunc='sum'
)
```

In [38]:

import seaborn as sns

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.pivot_table(index='sex', values='total_bill')  #Average bill per gender
# equalent
# df.groupby('sex')['total_bill'].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [40]:
df.pivot_table(
    index='sex',
    columns='smoker',
    values='total_bill',
    aggfunc=['mean','max']
)

             mean               max
smoker        Yes         No    Yes     No
sex
Male    22.284500  19.791237  50.81  48.33
Female  17.977879  18.105185  44.30  35.83