# filtering Movies.csv

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [4]:
# Drama Movies
movies[movies["genres"].str.contains("Drama")]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [9]:
# Movies with Runtime Between 100–120 and Gener Action
# as runtime is stored as string so convert to number 1st
movies["runtime"] = pd.to_numeric(movies["runtime"], errors="coerce")
movies[ (movies["genres"].str.contains("Action")) & (movies["runtime"] >= 100) & (movies["runtime"] <= 120) ]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
24,Junglee (2019 film),tt7463730,https://upload.wikimedia.org/wikipedia/en/e/e2...,https://en.wikipedia.org/wiki/Junglee_(2019_film),Junglee,Junglee,0,2019,115.0,Action|Adventure,5.3,1064,Dipankar Nair runs a Elephant sanctuary but th...,The story revolves around a vet who on his ho...,NaN,Vidyut Jammwal|Lars Kjeldsen|,NaN,29 March 2019 (USA)
46,Arjun Patiala,tt7881524,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Arjun_Patiala,Arjun Patiala,Arjun Patiala,0,2019,107.0,Action|Comedy,4.1,676,Arjun Patiala(Diljit Dosanjh)has recently been...,This spoof comedy narrates the story of a cop ...,NaN,Diljit Dosanjh|Kriti Sanon|Varun Sharma|Ronit ...,NaN,26 July 2019 (USA)
77,Mardaani 2,tt5668770,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mardaani_2,Mardaani 2,Mardaani 2,0,2019,103.0,Action|Drama|Thriller,7.4,8100,Shivani Shivaji Roy locks horns with the devil...,Shivani Shivaji Roy locks horns with the devil...,NaN,Rani Mukerji|Rajesh Sharma|Shruti Bapna|,NaN,NaN
169,The Ghazi Attack,tt6299040,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Ghazi_Attack...,The Ghazi Attack,The Ghazi Attack,0,2017,116.0,Action|Thriller|War,7.6,10332,In 1971 amid rising tensions between India an...,A Pakistani submarine Ghazi plans to secretly...,The war you did not know about,Rana Daggubati|Kay Kay Menon|Atul Kulkarni|Om ...,1 win & 7 nominations,17 February 2017 (USA)
175,Trapped (2016 Hindi film),tt6206564,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Trapped_(2016_In...,Trapped,Trapped,0,2016,105.0,Action|Drama|Thriller,7.5,8295,'Shaurya' (Rajkummar Rao) must pluck up the co...,A man struggles to survive after he unintentio...,NaN,Rajkummar Rao|Geetanjali Thapa|Shiladitya Sen|...,4 wins & 4 nominations,17 March 2017 (India)
201,Bank Chor,tt3611266,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bank_Chor,Bank Chor,Bank Chor,0,2017,120.0,Action|Comedy|Thriller,5.9,2164,Introducing the worst Bank Chor EVER: Champak ...,A comic-caper that tells the story of 3 moron...,3 Idiots. 1 Bank. 1 Screwed Up Day,Riteish Deshmukh|Vivek Oberoi|Rhea Chakraborty...,NaN,16 June 2017 (India)
258,Irudhi Suttru,tt5310090,https://upload.wikimedia.org/wikipedia/en/f/fe...,https://en.wikipedia.org/wiki/Saala_Khadoos,Saala Khadoos,Saala Khadoos,0,2016,109.0,Action|Drama|Sport,7.6,10507,An under-fire boxing coach Prabhu is transfer...,The story of a former boxer who quits boxing f...,NaN,Madhavan|Ritika Singh|Mumtaz Sorcar|Nassar|Rad...,9 wins & 2 nominations,29 January 2016 (USA)
276,Rocky Handsome,tt3410408,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rocky_Handsome,Rocky Handsome,Rocky Handsome,0,2016,119.0,Action|Thriller,6.8,6582,Kabir runs a pawn shop in Goa he befriends his...,A reclusive pawn shop owner sets his sights on...,His only friend... her only hope.,John Abraham|Nishikant Kamat|Sharad Kelkar|Ted...,NaN,25 March 2016 (USA)
284,The Blueberry Hunt,tt2009592,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Blueberry_Hunt,The Blueberry Hunt,The Blueberry Hunt,0,2016,110.0,Action|Thriller,5.7,186,"The film centers on a recluse known as ""Colone...","The film centers on a recluse known as ""Colone...",NaN,Kartik Elangovan|Vinay Forrt|Aahana Kumra|P.T....,NaN,8 April 2016 (India)
359,31st October (film),tt4386684,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/31st_October_(film),31st October,31st October,0,2015,109.0,Action|Drama|History,5.9,205,On 31st October 1984 Prime Minister of India ...,The assassination of Indira Gandhi leads to a ...,A journey against all odds,Soha Ali Khan|Lakha Lakhwinder Singh|Nagesh Bh...,NaN,21 October 2016 (USA)
384,Ab Tak Chhappan 2,tt2202086,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ab_Tak_Chhappan_2,Ab Tak Chhappan 2,Ab Tak Chhappan 2,0,2015,106.0,Action|Crime|Thriller,5.8,1194,Home Minister Janardhan Jagirdarand chief Mini...,Home Minister Janardhan Jagirdarand chief Mini...,NaN,Nana Patekar|Mohan Agashe|Gul Panag|Ashutosh R...,NaN,27 February 2015 (India)
390,Hey Bro,tt4512230,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hey_Bro,Hey Bro,Hey Bro,0,2015,113.0,Action|Comedy|Drama,3.3,119,A villager goes to Mumbai to find his judwa br...,A villager goes to Mumbai to find his judwa br...,NaN,Ganesh Acharya|Maninder Singh|Nupur Sharma|Pre...,NaN,6 March 2015 (India)
391,NH10 (film),tt3742284,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/NH10_(film),NH10,NH10,0,2015,115.0,Action|Crime|Drama,7.2,11378,Meera and Arjun are professionals living in Gu...,On their way to a weekend retreat a married c...,No turning back.,Anushka Sharma|Neil Bhoopalam|Darshan Kumaar|D...,2 wins & 5 nominations,13 March 2015 (India)
441,Bhaag Johnny,tt3619710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhaag_Johnny,Bhaag Johnny,Bhaag Johnny,0,2015,118.0,Action|Fantasy|Thriller,5.1,851,Forced to kill a woman Johnny is granted the ...,Forced to kill a woman Johnny is granted the ...,NaN,Kunal Khemu|Zoa Morani|Mandana Karimi|Manasi S...,NaN,25 September 2015 (India)
442,Jazbaa,tt4323504,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jazbaa,Jazbaa,Jazbaa,0,2015,119.0,Action|Crime|Drama,5.8,3021,Anuradha Verma is a prominent criminal lawyer ...,Tensions arise when the daughter of nation's b...,NaN,Aishwarya Rai Bachchan|Irrfan Khan|Shabana Azm...,NaN,9 October 2015 (India)
449,Titli (2014 film),tt3019620,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Titli_(2014_film),Titli,Titli,0,2014,116.0,Action|Drama|Thriller,7.6,3677,In the badlands of Delhi's dystopic underbelly...,A Hindi feature film set in the lower depths o...,Daring| Desireable| Dangerous,Nawazuddin Siddiqui|Niharika Singh|Anil George...,4 wins & 5 nominations,20 June 2014 (USA)
454,Karle Pyaar Karle,tt3465488,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Karle_Pyaar_Karle,Karle Pyaar Karle,Karle Pyaar Karle,0,2014,110.0,Action|Romance,2.8,111,Karle Pyaar Karle is an adrenaline gushing ac...,Karle Pyaar Karle is an adrenaline gushing ac...,NaN,Shiv Darshan|Hasleen Kaur|Aham Sharma|Rumi Kha...,NaN,17 January 2014 (USA)
476,Dishkiyaoon,tt3539966,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dishkiyaoon,Dishkiyaoon,Dishkiyaoon,0,2014,119.0,Action|Thriller,5.2,918,Vicky wanted to be the godfather of Mumbai und...,Vicky wanted to be the godfather of Mumbai und...,NaN,Harman Baweja|Harsh Chhaya|Sunny Deol|Rajit Ka...,NaN,28 March 2014 (India)
524,Mardaani,tt3495000,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mardaani,Mardaani,Mardaani,0,2014,113.0,Action|Crime|Drama,7.3,9623,India is the world's hub for child sex traffic...,A story of Shivani Shivaji Roy Crime Branch ...,NaN,Rani Mukerji|Tahir Raj Bhasin|Priyanka Sharma|,3 wins & 14 nominations,22 August 2014 (India)
598,Go Goa Gone,tt2436516,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Go_Goa_Gone,Go Goa Gone,Go Goa Gone,0,2013,108.0,Action|Adventure|Comedy,6.6,10605,Two friends Luv (Vir Das) and Hardik (Kunal K...,A group of friends just looking to have a goo...,NaN,Saif Ali Khan|Kunal Khemu|Vir Das|Anand Tiwari...,1 win & 3 nominations,10 May 2013 (India)
672,Blood Money (2012 film),tt2246595,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Blood_Money_(201...,Blood Money,Blood Money,0,2012,109.0,Action|Drama|Thriller,5.1,893,The film is about a young and simple man Kuna...,A young man elopes with the girl he loves and ...,When dreams become nightmares,Manish Chaudhary|Kunal Khemu|Amrita Puri|Sheka...,NaN,30 March 2012 (India)
682,Ishaqzaade,tt2308773,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ishaqzaade,Ishaqzaade,Ishaqzaade,0,2012,120.0,Action|Drama|Romance,6.5,6214,Rising from the ashes of hooliganism and small...,While fighting for the political supremacy of ...,Born to Hate... Destined to Love,Arjun Kapoor|Parineeti Chopra|Gauhar Khan|Anil...,11 wins & 17 nominations,11 May 2012 (India)
698,Maximum (film),tt2339549,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Maximum_(film),Maximum,Maximum,0,2012,110.0,Action|Crime|Drama,4.9,187,It's the story of two cops and their struggle ...,Revolves around two cops who wants be at the t...,NaN,Sonu Sood|Naseeruddin Shah|Neha Dhupia|Vinay P...,NaN,29 June 2012 (USA)
706,Krishna Aur Kans,tt2321492,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Krishna_Aur_Kans,Krishna Aur Kans,Krishna Aur Kans,0,2012,117.0,Action|Adventure|Animation,6.3,157,It is the story of Krishna the destiny's chil...,Hailed as India's first stereoscopic animated ...,NaN,Manoj Bajpayee|Harish Bhimani|Neetu Chaudhary|...,NaN,3 August 2012 (India)
716,Chittagong (film),tt1785333,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chittagong_(film),Chittagong,Chittagong,0,2012,105.0,Action|Drama|War,7.2,1334,Set in the turbulence of the 1930s British Ind...,School kids organize an armed revolt in the 19...,Ordinary Boys| Extraordinary Triumph,Manoj Bajpayee|Barry John|Delzad Hiwale|Vega T...,4 wins,12 October 2012 (India)
731,Dabangg 2,tt2112131,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dabangg_2,Dabangg 2,Dabangg 2,0,2012,120.0,Action|Comedy,4.9,14077,Chulbul Pandey is transferred and promoted to ...,Chulbul Pandey invites a fresh trouble when he...,NaN,Salman Khan|Sonakshi Sinha|Prakash Raj|Vinod K...,9 wins & 20 nominations,21 December 2012 (India)
741,Hostel (2011 film),tt1825801,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hostel_(2011_film),Hostel,Hostel,0,2011,111.0,Action|Crime|Drama,5.1,533,After the passing of his parents Karan reside...,An Engineering student is molested beaten and...,The Truth Will HIT You,Vatsal Sheth|Tulip Joshi|Mukesh Tiwari|Nagesh ...,NaN,21 January 2011 (India)
751,Angel (2011 film),tt1825655,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Angel_(2011_film),Angel,Angel,0,2011,114.0,Action|Drama,6.5,80,D.N. Nagar Police are summoned to a Chawl wher...,After serving time in jail for running over a ...,NaN,Sumit Arora|Arun|Raakesh Babu|Prem Kishen Dwiv...,NaN,4 February 2011 (India)
756,Zokkomon,tt1605790,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zokkomon,Zokkomon,Zokkomon,0,2011,109.0,Action|Adventure,4.0,274,After the passing of his parents in an acciden...,An orphan is abused and abandoned believed to...,Betrayal. Friendship. Bravery.,Darsheel Safary|Anupam Kher|Manjari Fadnnis|Ti...,NaN,22 April 2011 (India)
774,Bbuddah... Hoga Terra Baap,tt1869296,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bbuddah..._Hoga_...,Bbuddah... Hoga Terra Baap,Bbuddah... Hoga Terra Baap,0,2011,114.0,Action|Crime|Thriller,5.6,2580,After a series of bomb blasts in Mumbai ACP K...,A quick-tempered flamboyantly-dressed retire...,NaN,Amitabh Bachchan|Hema Malini|Sonu Sood|Sonal C...,NaN,1 July 2011 (USA)
775,Delhi Belly (film),tt1934231,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Delhi_Belly_(film),Delhi Belly,Delhi Belly,0,2011,103.0,Action|Comedy|Crime,7.5,25281,Delhi-based Sonia agrees to deliver a package ...,Three struggling room-mates unknowingly become...,Shit Happens!,Imran Khan|Vir Das|Kunaal Roy Kapur|Shenaz Tre...,5 wins & 9 nominations,1 July 2011 (USA)
790,Sahi Dhandhe Galat Bande,tt1630282,NaN,https://en.wikipedia.org/wiki/Sahi_Dhandhe_Gal...,Sahi Dhandhe Galat Bande,Sahi Dhandhe Galat Bande,0,2011,119.0,Action|Comedy|Drama,4.9,259,Rajbir is sentenced to a year in jail for Assa...,The son of a politician is abducted. The kidna...,NaN,Anupam Kher|Sharat Saxena|Udit Khurana|Tina De...,NaN,19 August 2011 (India)
800,Saheb Biwi Aur Gangster,tt2073070,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Saheb_Biwi_Aur_G...,Saheb Biwi Aur Gangster,Saheb Biwi Aur Gangster,0,2011,118.0,Action|Crime|Drama,7.2,3709,After the death of his first wife wealthy Raj...,Hired to kill a nobleman the assassin instead...,NaN,Jimmy Sheirgill|Mahie Gill|Randeep Hooda|Shrey...,3 nominations,23 September 2011 (USA)
853,Chase (2010 film),tt1594964,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chase_(2010_film),Chase,Chase,0,2010,103.0,Action|Crime|Drama,4.8,87,After a dramatic chase Mumbai Police finally ...,Police launch a manhunt for an escaped rehab-p...,NaN,Anuj Saxena|Udita Goswami|Tarina Patel|Sameer ...,NaN,30 April 2010 (India)
880,Red Alert: The War Within,tt1245732,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Red_Alert:_The_W...,Red Alert: The War Within,Red Alert: The War Within,0,2009,120.0,Action|Drama|Thriller,6.4,318,While delivering food in a forest area in Andh...,An impoverished cook is forced to join a band ...,We both fired. He missed. I didn't.,Sunil Shetty|Sameera Reddy|Ashish Vidyarthi|Vi...,NaN,7 July 2010 (USA)
886,Aakrosh (2010 film),tt1708453,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aakrosh_(2010_film),Aakrosh,Aakrosh,0,2010,115.0,Action|Crime|Thriller,7.0,2987,Giving in to intense media pressure the Home ...,The Central Bureau of Investigation deputes tw...,There is no honour in honour killing,Ajay Devgn|Akshaye Khanna|Bipasha Basu|Paresh ...,1 win,15 October 2010 (India)
888,Knock Out (2010 film),tt1558578,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Knock_Out_(2010_...,Knock Out,Knock Out,0,2010,117.0,Action|Crime|Drama,5.9,1857,While making a phone call from a phone booth i...,Hidden with a mysterious agenda a sniper hold...,NaN,Sanjay Dutt|Irrfan Khan|Kangana Ranaut|Gulshan...,NaN,15 October 2010 (India)
905,Ramaa: The Saviour,tt1279105,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ramaa:_The_Saviour,Ramaa: The Saviour,Ramaa: The Saviour,0,2010,120.0,Action|Adventure|Drama,3.4,132,Snobbish Komal (Ananya Shukla) and her brother...,While playing a video game on TV school-child...,NaN,Sahil Khan|Tanushree Dutta|Meghan Jadhav|Koush...,NaN,12 November 2010 (India)
934,Aa Dekhen Zara,tt1372681,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aa_Dekhen_Zara,Aa Dekhen Zara,Aa Dekhen Zara,0,2009,117.0,Action|Sci-Fi|Thriller,5.0,812,Mumbai-based struggling wildlife photographer ...,A photographer has nothing going for him unti...,A Date With Fate,Neil Nitin Mukesh|,NaN,27 March 2009 (India)
947,Kisaan,tt1372266,https://upload.wikimedia.org/wikipedia/en/c/c5...,https://en.wikipedia.org/wiki/Kisaan,Kisaan,Kisaan,0,2009,100.0,Action|Crime|Drama,5.4,256,Widower farmer Dayal Singh based in Palheri ...,Widower farmer Dayal Singh based in Palheri ...,NaN,Jackie Shroff|Sohail Khan|Arbaaz Khan|Nauheed ...,1 nomination,20 March 2009 (India)
958,Acid Factory,tt1201557,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Acid_Factory,Acid Factory,Acid Factory,0,2009,108.0,Action|Crime|Mystery,5.0,625,Cape Town Police's Assistant Commissioner Ranb...,Five people trapped in a factory where two hos...,NaN,Fardeen Khan|Dia Mirza|Manoj Bajpayee|Aftab Sh...,NaN,9 October 2009 (India)
962,Blue (2009 film),tt1223922,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Blue_(2009_film),Blue,Blue,0,2009,119.0,Action|Adventure|Thriller,3.7,4203,Bangkok-based bike-racer Sameer Singh gets in ...,A group of people facing a lot of challenges ...,250 feet deep lies the secret of...,Akshay Kumar|Sanjay Dutt|Lara Dutta|Zayed Khan...,4 wins & 1 nomination,16 October 2009 (USA)
995,Tashan (film),tt0995752,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tashan_(film),Tashan,Tashan,0,2008,120.0,Action|Drama|Romance,3.8,4580,What happens when you throw two guys who hate ...,What happens when you throw 2 guys who hate ea...,The Ishtyle... The Goodluck... The Pharmoola,Akshay Kumar|Saif Ali Khan|Kareena Kapoor|Anil...,NaN,25 April 2008 (India)
1018,Chamku,tt1266545,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chamku,Chamku,Chamku,0,2008,105.0,Action|Crime|Thriller,4.0,474,After witnessing his entire Bhagpur Bihar-bas...,A traumatized child becomes a Naxalite and up...,NaN,Bobby Deol|Priyanka Chopra|Irrfan Khan|Akhilen...,NaN,29 August 2008 (India)
1071,Dhokha,tt1090650,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dhokha,Dhokha,Dhokha,0,2007,117.0,Action|Drama|Romance,6.3,405,Post-September 11 2001 Zaid Ahmed Khan lives...,Post-September 11 2001 Zaid Ahmed Khan lives...,Some betrayals are never forgotten,Muzamil Ibrahim|Muzammil Ibrahim|Tulip Joshi|A...,NaN,31 August 2007 (India)
1079,Eklavya: The Royal Guard,tt0459605,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Eklavya:_The_Roy...,Eklavya: The Royal Guard,Eklavya,0,2007,105.0,Action|Drama|Thriller,6.1,2983,It has been chronicled in the Geeta that Eklav...,As the kingdom of Devigarh comes apart at the ...,The Royal Guard,Amitabh Bachchan|Saif Ali Khan|Sanjay Dutt|Vid...,1 nomination,16 February 2007 (India)
1121,Sarhad Paar,tt0476861,NaN,https://en.wikipedia.org/wiki/Sarhad_Paar,Sarhad Paar,Sarhad Paar,0,2006,117.0,Action|Drama|Romance,4.2,100,Sarhad Paar examines the connection between a ...,An Indian soldier tries to exact revenge on th...,NaN,Mahima Chaudhry|Tabu|Sanjay Dutt|Chandrachur S...,NaN,23 November 2006 (India)
1129,Speed (2007 film),tt0816657,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Speed_(2007_film),Speed,Speed,0,2007,102.0,Action|Crime|Thriller,2.9,480,Zayed comes to London to convince his girlfrie...,A young man receives a phone call from a woman...,NaN,Urmila Matondkar|Sanjay Suri|Zayed Khan|Aftab ...,NaN,19 October 2007 (India)
1132,Showbiz (film),tt1152845,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Showbiz_(film),Showbiz,Showbiz,0,2007,108.0,Action|Crime|Drama,3.8,108,Rohan Arya lives a wealthy lifestyle in Mumbai...,Rohan Arya lives a wealthy lifestyle in Mumbai...,NaN,Tushar Jalota|Mrinalini Sharma|,NaN,28 December 2007 (India)
1204,The Killer (2006 film),tt0833484,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Killer_(2006...,The Killer,The Killer,0,2006,117.0,Action|Comedy|Crime,4.6,929,The Central Bureau of Investigation (CBI) Ind...,The Central Bureau of Investigation (CBI) Ind...,NaN,Irrfan Khan|Emraan Hashmi|Priyanka Kothari|,NaN,21 July 2006 (India)
1207,Teesri Aankh: The Hidden Camera,tt0779768,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Teesri_Aankh:_Th...,Teesri Aankh: The Hidden Camera,Teesri Aankh: The Hidden Camera,0,2006,111.0,Action|Crime|Thriller,2.5,272,Assigned to extradite a London-based criminal ...,About women who are trapped used and abused b...,It's not about mythology....it's technology !,Sunny Deol|Ameesha Patel|Neha Dhupia|Mukesh Ri...,NaN,3 March 2006 (India)

In [10]:
# movies with unknown run time
movies[movies["runtime"].notnull()]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138.0,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131.0,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112.0,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121.0,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102.0,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153.0,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148.0,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146.0,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136.0,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35.0,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [11]:
# top 10 most voted movies
movies.sort_values("imdb_votes", ascending=False).head(10)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
912,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots,3 Idiots,3 Idiots,0,2009,170.0,Comedy|Drama,8.4,310481,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
1127,Taare Zameen Par,tt0986264,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Taare_Zameen_Par,Like Stars on Earth,Taare Zameen Par,0,2007,165.0,Drama|Family,8.4,148498,Ishaan Awasthi is an eight-year-old child whos...,An eight-year-old boy is thought to be a lazy ...,Every Child is Special,Darsheel Safary|Aamir Khan|Tisca Chopra|Vipin ...,18 wins & 8 nominations,21 December 2007 (India)
567,PK (film),tt2338151,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/PK_(film),PK,PK,0,2014,153.0,Comedy|Drama|Fantasy,8.1,143605,P. K. is a comedy of ideas about a stranger in...,An alien on Earth loses the only device he can...,NaN,Aamir Khan|Anushka Sharma|Saurabh Shukla|Sanja...,14 wins & 15 nominations,19 December 2014 (India)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161.0,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
74,Dil Bechara,tt8110330,NaN,https://en.wikipedia.org/wiki/Dil_Bechara,Dil Bechara,Dil Bechara,0,2019,101.0,Drama|Romance,6.6,117000,A love story about two cancer patients.,A love story about two cancer patients.,NaN,Sushant Singh Rajput|Sanjana Sanghi|Sahil Vaid|,NaN,NaN
1195,Rang De Basanti,tt0405508,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rang_De_Basanti,Rang De Basanti,Rang De Basanti,0,2006,167.0,Comedy|Drama,8.2,103071,Sue comes to India to make a film on Indian re...,The story of six young Indians who assist an E...,A Generation Awakens.,Aamir Khan|Siddharth|Sharman Joshi|Kunal Kapoo...,Nominated for 1 BAFTA Film Award,26 January 2006 (USA)
1568,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224.0,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1567,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224.0,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
829,My Name Is Khan,tt1188996,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/My_Name_Is_Khan,My Name Is Khan,My Name Is Khan,0,2010,165.0,Drama,8.0,92755,Rizwan Khan a Muslim from the Borivali sectio...,An Indian Muslim man with Asperger's syndrome ...,An ordinary man| An extraordinary journey ... ...,Shah Rukh Khan|Kajol|Katie A. Keane|Kenton Dut...,20 wins & 26 nominations,12 February 2010 (USA)
1384,Swades,tt0367110,https://upload.wikimedia.org/wikipedia/en/8/85...,https://en.wikipedia.org/wiki/Swades,Swades,Swades: We the People,0,2004,210.0,Drama,8.2,76737,Set in modern day India Swades is a film that...,A successful Indian scientist returns to an In...,We| the people,Shah Rukh Khan|Gayatri Joshi|Kishori Ballal|Sm...,14 wins & 23 nominations,17 December 2004 (India)

In [3]:
# Top 10 movies by votes in Comedy genre
movies [ movies['genres'].str.contains("Comedy")].sort_values("imdb_votes", ascending=False).head(10)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
912,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots,3 Idiots,3 Idiots,0,2009,170,Comedy|Drama,8.4,310481,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
567,PK (film),tt2338151,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/PK_(film),PK,PK,0,2014,153,Comedy|Drama|Fantasy,8.1,143605,P. K. is a comedy of ideas about a stranger in...,An alien on Earth loses the only device he can...,NaN,Aamir Khan|Anushka Sharma|Saurabh Shukla|Sanja...,14 wins & 15 nominations,19 December 2014 (India)
1195,Rang De Basanti,tt0405508,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rang_De_Basanti,Rang De Basanti,Rang De Basanti,0,2006,167,Comedy|Drama,8.2,103071,Sue comes to India to make a film on Indian re...,The story of six young Indians who assist an E...,A Generation Awakens.,Aamir Khan|Siddharth|Sharman Joshi|Kunal Kapoo...,Nominated for 1 BAFTA Film Award,26 January 2006 (USA)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
709,Barfi!,tt2082197,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Barfi!,Barfi!,Barfi!,0,2012,151,Comedy|Drama|Romance,8.1,70443,Set in the 1970s in a pretty corner of India ...,Three young people learn that love can neither...,NaN,Ranbir Kapoor|Priyanka Chopra|Ileana D'Cruz|Sa...,50 wins & 28 nominations,14 September 2012 (India)
1403,Munna Bhai M.B.B.S.,tt0374887,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Munna_Bhai_M.B.B.S.,Munna Bhai M.B.B.S.,Munna Bhai M.B.B.S.,0,2003,156,Comedy|Drama|Musical,8.1,67148,In India gangsters are called Bhai (brothers)....,A gangster sets out to fulfill his father's dr...,He might just cure you.,Sanjay Dutt|Arshad Warsi|Gracy Singh|Sunil Dut...,19 wins & 29 nominations,19 December 2003 (India)
362,Bajrangi Bhaijaan,tt3863552,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bajrangi_Bhaijaan,Bajrangi Bhaijaan,Bajrangi Bhaijaan,0,2015,163,Action|Comedy|Drama,8.0,65877,A little mute girl from a Pakistani village ge...,An Indian man with a magnanimous heart takes a...,NaN,Salman Khan|Harshaali Malhotra|Nawazuddin Sidd...,25 wins & 13 nominations,17 July 2015 (USA)
1571,Dil Chahta Hai,tt0292490,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dil_Chahta_Hai,Dil Chahta Hai,Dil Chahta Hai,0,2001,183,Comedy|Drama|Romance,8.1,62313,Three young men Akash Sameer and Siddharth a...,Three inseparable childhood friends are just o...,Welcome to a summer of their lives you will ne...,Aamir Khan|Saif Ali Khan|Akshaye Khanna|Preity...,22 wins & 37 nominations,10 August 2001 (India)
778,Zindagi Na Milegi Dobara,tt1562872,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zindagi_Na_Mileg...,Zindagi Na Milegi Dobara,Zindagi Na Milegi Dobara,0,2011,155,Comedy|Drama,8.1,60826,Three friends decide to turn their fantasy vac...,Three friends decide to turn their fantasy vac...,NaN,Hrithik Roshan|Farhan Akhtar|Abhay Deol|Katrin...,30 wins & 22 nominations,15 July 2011 (India)

In [7]:
#Top 10 Action movies after 2010 with rating > 7.5 and runtime < 150


## as runtime is stored as string so convert to number 1st
movies["runtime"] = pd.to_numeric(movies["runtime"], errors="coerce")
movies["release_date"] = pd.to_numeric(movies["runtime"], errors="coerce")
movies[ 
    (movies["genres"].str.contains("Action")) &
    (movies["release_date"] > 2010) &
    (movies["imdb_rating"] > 7.5) &
    (movies["runtime"] < 150)
 
       ].sort_values("imdb_rating").head(10)

Empty DataFrame
Columns: [title_x, imdb_id, poster_path, wiki_link, title_y, original_title, is_adult, year_of_release, runtime, genres, imdb_rating, imdb_votes, story, summary, tagline, actors, wins_nominations, release_date]
Index: []

In [9]:
# Movies with votes above dataset average
movies[movies["imdb_votes"] > movies["imdb_votes"].mean()].head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138.0,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,138.0
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112.0,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,112.0

In [11]:
# Movies where title contains "Love"

movies[movies["title_x"].str.contains("Love")].sort_values("title_x").head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
721,Ajab Gazabb Love,tt2356959,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ajab_Gazabb_Love,Ajab Gazabb Love,Ajab Gazabb Love,0,2012,116.0,Comedy|Romance,4.2,491,Rajveer falls in love with Madhuri. He realize...,Rajveer falls in love with Madhuri. He realize...,NaN,Jackky Bhagnani|Nidhi Subbaiah|Darshan Jariwal...,1 nomination,116.0
339,Beiimaan Love,tt5227468,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Beiimaan_Love,Beiimaan Love,Beiimaan Love,0,2016,120.0,Drama|Romance|Thriller,2.9,354,A young and ambitious woman's life suddenly co...,A young and ambitious woman's life suddenly co...,A perfectly imperfect love story.,Sunny Leone|Rajniesh Duggall|Daniel Weber|Raje...,NaN,120.0
1241,Classic – Dance of Love,tt0454433,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Classic_%E2%80%9...,Classic Dance of Love,Classic Dance of Love,0,2005,NaN,Drama,4.9,47,An orphaned and homeless girl ends up in a dan...,An orphaned and homeless girl ends up in a dan...,NaN,Mithun Chakraborty|Meghna Naidu|Vikas Bhardwaj...,NaN,NaN
1517,Ek Chhotisi Love Story,tt0331479,https://upload.wikimedia.org/wikipedia/en/8/8c...,https://en.wikipedia.org/wiki/Ek_Chhotisi_Love...,Ek Chhotisi Love Story,Ek Chhotisi Love Story,0,2002,122.0,Drama,2.9,525,A story of coming of age of a young 15 year ol...,A story of coming of age of a young 15 year ol...,I am 15. She is 26. I am madly in love with ...,Saroj Bhargava|Manisha Koirala|Jesse Randhawa|...,NaN,122.0
1584,Ek Rishtaa: The Bond of Love,tt0284083,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Rishtaa:_The_...,Bond of Love,Ek Rishtaa: The Bond of Love,0,2001,174.0,Drama|Family,5.0,1418,Multi-millionaire Vijay Kapoor own and manages...,Vijay Kapoor a wealthy businessman and his fa...,In times of happiness| they turned their backs...,Amitabh Bachchan|Rakhee Gulzar|Akshay Kumar|Ka...,NaN,174.0

In [13]:
# Movies that are NOT Comedy but rating > 8
movies[ ~(movies["genres"].str.contains("Comedy") ) & (movies["imdb_rating"] > 8)].head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138.0,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,138.0
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153.0,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,153.0