# Creating Column
- two types

    - Completely new col in Dataset
    - existing columns → new useful column

## Completely New Col

    df["col_name"] = values

## New Col From Existing Cols
- Here we make new Col from existing Col by using Operations, Consitions etc

- exm:

        def["new_col"] = df["Old_col"] + df["Old_col2"]
        df["new_col"] = df["old_column"] > 7


# Droping Col and Row
## Col
    df.drop("column_name", axis=1)

- axis = 1 means Col
- azis = 0 means Row

## row

    df.drop(2)

- whole row at index 2 will be dropped
- After Deleting rows the indexing needs to be reset so we use

        df.reset_index(drop=True)

In [1]:
import pandas as pd

In [3]:
movies = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/movies.csv")
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [ ]:
# Completely New Col

movies["Country"] = "India"
movies.head(2)
movies["Country"].head(2)   # new Col

0    India
1    India
Name: Country, dtype: str

In [ ]:
# from Exiting Col

movies["hit_movies"] = movies["imdb_rating"] > 8
movies.head(2) # now Col has been added

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country,hit_movies
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India,True
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India,False

In [14]:
# long Movie Col
movies["runtime"] = pd.to_numeric(movies["runtime"], errors="coerce")
movies["Long_movie"] = movies["runtime"] > 200
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,...,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country,hit_movies,Long_movie
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138.0,Action|Drama|War,...,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India,True,False
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131.0,War,...,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India,False,False

In [17]:
# genere Count Col
movies["genres_Count"] = movies["genres"].str.split("|").str.len()
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,...,story,summary,tagline,actors,wins_nominations,release_date,Country,hit_movies,Long_movie,genres_Count
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138.0,Action|Drama|War,...,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India,True,False,3
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131.0,War,...,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India,False,False,1

In [47]:
# Data Frame 

data = {
    "name": ["Alyan", "Adil", "Asad", "Aroosa", "Alien"],
    "age": [22, 21, 23, 20, 24],
    "city": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "salary": [50000, 60000, 55000, 52000, 65000]
}

df = pd.DataFrame(data)
df

     name  age       city  salary
0   Alyan   22     Lahore   50000
1    Adil   21    Karachi   60000
2    Asad   23  Islamabad   55000
3  Aroosa   20     Lahore   52000
4   Alien   24    Karachi   65000

In [48]:
# insertng a Column
df["bonus"] = df["salary"] * 0.10
df["name_length"] = df["name"].str.len()
df

     name  age       city  salary   bonus  name_length
0   Alyan   22     Lahore   50000  5000.0            5
1    Adil   21    Karachi   60000  6000.0            4
2    Asad   23  Islamabad   55000  5500.0            4
3  Aroosa   20     Lahore   52000  5200.0            6
4   Alien   24    Karachi   65000  6500.0            5

In [49]:
df.drop("name_length", axis=1, inplace=True)
df # we drooped the name_length Cols

     name  age       city  salary   bonus
0   Alyan   22     Lahore   50000  5000.0
1    Adil   21    Karachi   60000  6000.0
2    Asad   23  Islamabad   55000  5500.0
3  Aroosa   20     Lahore   52000  5200.0
4   Alien   24    Karachi   65000  6500.0

In [ ]:
df.drop(4, inplace=True) # 4th row from all cols will be delete
df.drop(1, inplace=True)
df # we see the indexing is wrong .. so to reset index we use df.reset_index(drop=True)

     name  age       city  salary   bonus
0   Alyan   22     Lahore   50000  5000.0
2    Asad   23  Islamabad   55000  5500.0
3  Aroosa   20     Lahore   52000  5200.0

In [51]:
df.reset_index(drop=True)

     name  age       city  salary   bonus
0   Alyan   22     Lahore   50000  5000.0
1    Asad   23  Islamabad   55000  5500.0
2  Aroosa   20     Lahore   52000  5200.0

# Practice

In [53]:
data = {
    "student_id": [101,102,103,104,105,106,107,108],
    "name": ["Ali","Sara","Ahmed","Zara","Usman","Hina","Bilal","Ayesha"],
    "age": [21,22,20,23,24,21,22,20],
    "city": ["Lahore","Karachi","Islamabad","Lahore","Karachi","Lahore","Islamabad","Karachi"],
    "math_score": [78,88,92,65,70,85,90,60],
    "english_score": [80,75,85,60,72,88,91,65],
    "study_hours": [3,5,6,2,3,4,5,2]
}

df1 = pd.DataFrame(data)
df1

   student_id    name  age       city  math_score  english_score  study_hours
0         101     Ali   21     Lahore          78             80            3
1         102    Sara   22    Karachi          88             75            5
2         103   Ahmed   20  Islamabad          92             85            6
3         104    Zara   23     Lahore          65             60            2
4         105   Usman   24    Karachi          70             72            3
5         106    Hina   21     Lahore          85             88            4
6         107   Bilal   22  Islamabad          90             91            5
7         108  Ayesha   20    Karachi          60             65            2

In [57]:
df1["total_score"] = df1["english_score"] + df1["math_score"]
df1["avg_score"] = df1["total_score"] / 2
df1["is_toper"] = df1["avg_score"] > 90
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper
0,101,Ali,21,Lahore,78,80,3,158,79.0,False
1,102,Sara,22,Karachi,88,75,5,163,81.5,False
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False
3,104,Zara,23,Lahore,65,60,2,125,62.5,False
4,105,Usman,24,Karachi,70,72,3,142,71.0,False
5,106,Hina,21,Lahore,85,88,4,173,86.5,False
6,107,Bilal,22,Islamabad,90,91,5,181,90.5,True
7,108,Ayesha,20,Karachi,60,65,2,125,62.5,False

In [58]:
# A col using Cotigory 
# age >= 22 → "Senior"
# age < 22 → "Junior"

# use np.where(condition, if true, if false)
import numpy as np
df1["age_category"] = np.where(df1["age"] >= 22, "senoir",  "Junior")
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,Sara,22,Karachi,88,75,5,163,81.5,False,senoir
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
3,104,Zara,23,Lahore,65,60,2,125,62.5,False,senoir
4,105,Usman,24,Karachi,70,72,3,142,71.0,False,senoir
5,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
6,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,senoir
7,108,Ayesha,20,Karachi,60,65,2,125,62.5,False,Junior

In [60]:
# Droping Col
df1.drop("student_id", axis=1)
df1.drop("name", axis=1)

,student_id,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,22,Karachi,88,75,5,163,81.5,False,senoir
2,103,20,Islamabad,92,85,6,177,88.5,False,Junior
3,104,23,Lahore,65,60,2,125,62.5,False,senoir
4,105,24,Karachi,70,72,3,142,71.0,False,senoir
5,106,21,Lahore,85,88,4,173,86.5,False,Junior
6,107,22,Islamabad,90,91,5,181,90.5,True,senoir
7,108,20,Karachi,60,65,2,125,62.5,False,Junior

In [62]:
# Row Filtering
# keep only students with Scores > 70

df1 = df1[df1["math_score"] > 70]
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,Sara,22,Karachi,88,75,5,163,81.5,False,senoir
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
5,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
6,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,senoir

In [65]:
df1[df1["avg_score"] >= 75]
df1 = df1.reset_index(drop=True)
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior
1,102,Sara,22,Karachi,88,75,5,163,81.5,False,senoir
2,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
3,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
4,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,senoir

In [68]:
df1 = df1.sort_values("avg_score", ascending=False)
df1 = df1.reset_index(drop=True)
df1

,student_id,name,age,city,math_score,english_score,study_hours,total_score,avg_score,is_toper,age_category
0,107,Bilal,22,Islamabad,90,91,5,181,90.5,True,senoir
1,103,Ahmed,20,Islamabad,92,85,6,177,88.5,False,Junior
2,106,Hina,21,Lahore,85,88,4,173,86.5,False,Junior
3,102,Sara,22,Karachi,88,75,5,163,81.5,False,senoir
4,101,Ali,21,Lahore,78,80,3,158,79.0,False,Junior