# important Data Frame Methods

- Value Counts:

        df.value_counts()  -->> returns frequency of each item in series But in DF returns frequency of each row

- sort_values:

        df.sort_value()

        - if we want to sort data using a specific col 

                df.sort_values("col_name")

- Rank

        df.rank() -->> dont work on DF

        rank item on base of one col ( rank on the base of score)

        df.rank(["score"]).rank()

- sort_index()

        df.sort_index()

- set index:

        df.set_index("col_name") -->> this col will act as index

- reset index:

        def.reset_index()

- Rename:

        df.rename(columns={"old_name" : "new_name"})

- N unique;

        DF.unique() -->> nbr of unique Value

- Missing Values:

        df.isnull()
        df.notnull()
        df.hasnull()

        movies["year"].hasnull()

        df.dropna()  -->> drop missing ( nan ) values ( if in Df there is one missing value in row the Whole row raw is dropped )

        df.dropna(how="all") -->> now only those rows will drop that which filed with missing values
 
        df.fillna(value_to_replace_nan_with)  -->>

- Drop Duplictes:

        df.drop_duplicates()  -->> drop Duplicate rows

        it has hidden parameter keep i.e which raw to keep 

        df.drop_duplicated(keep="first) -->> keep 1st raw and removes other duplictaes

- Apply

        df.apply()

In [21]:
import pandas as pd
import numpy as np

In [2]:
a = pd.Series([1,2,1,1,1,2,2,4,5])
a.value_counts()

1    4
2    3
4    1
5    1
Name: count, dtype: int64

In [6]:
marks = pd.DataFrame( [
    [1, 2, 3],
    [1, 2, 3],
    [3,4,5],
    [5,0,2],
    [1, 2, 3]
],columns=["x","y",'z'] )
marks

   x  y  z
0  1  2  3
1  1  2  3
2  3  4  5
3  5  0  2
4  1  2  3

In [ ]:
marks.value_counts()
# 1 2 3 row repeats 3 time

x  y  z
1  2  3    3
3  4  5    1
5  0  2    1
Name: count, dtype: int64

# Csv Filies

In [8]:
movies = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/movies.csv")
ipl = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/ipl-matches.csv")

In [ ]:
# toss decision to bat
ipl["TossDecision"].value_counts() 
# as its one col so its a series

TossDecision
field    599
bat      351
Name: count, dtype: int64

In [11]:
# how many Matches each team has Played
ipl["Team1"].value_counts() + ipl["Team2"].value_counts()

Team1
Chennai Super Kings            208
Deccan Chargers                 75
Delhi Capitals                  63
Delhi Daredevils               161
Gujarat Lions                   30
Gujarat Titans                  16
Kings XI Punjab                190
Kochi Tuskers Kerala            14
Kolkata Knight Riders          223
Lucknow Super Giants            15
Mumbai Indians                 231
Pune Warriors                   46
Punjab Kings                    28
Rajasthan Royals               192
Rising Pune Supergiant          16
Rising Pune Supergiants         14
Royal Challengers Bangalore    226
Sunrisers Hyderabad            152
Name: count, dtype: int64

# df.sort_value(["col_name"])  or
# df.sort_value("col_name")

In [19]:
movies.sort_values("title_x").head(6)
movies.sort_values(["actors"])
movies.sort_values(["poster_path"]).head(2)
movies.sort_values(["title_x", "year_of_release"]).head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1498,16 December (film),tt0313844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/16_December_(film),16-Dec,16-Dec,0,2002,158,Action|Thriller,6.9,1091,16 December 1971 was the day when India won t...,Indian intelligence agents race against time t...,NaN,Danny Denzongpa|Gulshan Grover|Milind Soman|Di...,2 nominations,22 March 2002 (India)
1021,1920 (film),tt1301698,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1920_(film),1920,1920,0,2008,138,Horror|Mystery|Romance,6.4,2588,A devotee of Bhagwan Shri Hanuman Arjun Singh...,After forsaking his family and religion a hus...,A Love Made in Heaven...A Revenge Born in Hell...,Rajniesh Duggall|Adah Sharma|Anjori Alagh|Raj ...,NaN,12 September 2008 (India)

In [22]:
data = {
    "name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Eve", None],
    "score": [90, 85, 90, 90, 85, 70, np.nan],
    "year": [2021, 2020, 2021, 2021, 2020, 2019, 2022],
    "city": ["NY", "LA", "NY", "NY", "LA", None, "SF"]
}

df = pd.DataFrame(data)
print(df)

      name  score  year city
0    Alice   90.0  2021   NY
1      Bob   85.0  2020   LA
2  Charlie   90.0  2021   NY
3    Alice   90.0  2021   NY
4      Bob   85.0  2020   LA
5      Eve   70.0  2019  NaN
6      NaN    NaN  2022   SF

In [25]:
print( df["name"].value_counts())
print()
print( df.value_counts())

name
Alice      2
Bob        2
Charlie    1
Eve        1
Name: count, dtype: int64

name     score  year  city
Alice    90.0   2021  NY      2
Bob      85.0   2020  LA      2
Charlie  90.0   2021  NY      1
Name: count, dtype: int64

In [27]:
print( df.sort_values("year"))
print()
print(df.sort_values("year", ascending=False))

      name  score  year city
5      Eve   70.0  2019  NaN
1      Bob   85.0  2020   LA
4      Bob   85.0  2020   LA
0    Alice   90.0  2021   NY
3    Alice   90.0  2021   NY
2  Charlie   90.0  2021   NY
6      NaN    NaN  2022   SF

      name  score  year city
6      NaN    NaN  2022   SF
2  Charlie   90.0  2021   NY
0    Alice   90.0  2021   NY
3    Alice   90.0  2021   NY
1      Bob   85.0  2020   LA
4      Bob   85.0  2020   LA
5      Eve   70.0  2019  NaN

In [29]:
df["score_rank"] = df["score"].rank(ascending=False)
df

      name  score  year city  score_rank
0    Alice   90.0  2021   NY         2.0
1      Bob   85.0  2020   LA         4.5
2  Charlie   90.0  2021   NY         2.0
3    Alice   90.0  2021   NY         2.0
4      Bob   85.0  2020   LA         4.5
5      Eve   70.0  2019  NaN         6.0
6      NaN    NaN  2022   SF         NaN

In [35]:
print(df.isnull())
print()
print(df.dropna())
print()
print(df.dropna(how="all"))
print()
df_filled = df.fillna(0)
print(df_filled)

    name  score   year   city  score_rank
0  False  False  False  False       False
1  False  False  False  False       False
2  False  False  False  False       False
3  False  False  False  False       False
4  False  False  False  False       False
5  False  False  False   True       False
6   True   True  False  False        True

      name  score  year city  score_rank
0    Alice   90.0  2021   NY         2.0
1      Bob   85.0  2020   LA         4.5
2  Charlie   90.0  2021   NY         2.0
3    Alice   90.0  2021   NY         2.0
4      Bob   85.0  2020   LA         4.5

      name  score  year city  score_rank
0    Alice   90.0  2021   NY         2.0
1      Bob   85.0  2020   LA         4.5
2  Charlie   90.0  2021   NY         2.0
3    Alice   90.0  2021   NY         2.0
4      Bob   85.0  2020   LA         4.5
5      Eve   70.0  2019  NaN         6.0
6      NaN    NaN  2022   SF         NaN

      name  score  year city  score_rank
0    Alice   90.0  2021   NY         2.0
1      Bob   85.0  2020   LA         4.5
2  Charlie   90.0  2021   NY         2.0
3    Alice   90.0  2021   NY         2.0
4      Bob   85.0  2020   LA         4.5
5      Eve   70.0  2019    0         6.0
6        0    0.0  2022   SF         0.0

In [36]:
df.fillna({"score": 0, "name": "unknown" , "city" : "unkown"})

      name  score  year    city  score_rank
0    Alice   90.0  2021      NY         2.0
1      Bob   85.0  2020      LA         4.5
2  Charlie   90.0  2021      NY         2.0
3    Alice   90.0  2021      NY         2.0
4      Bob   85.0  2020      LA         4.5
5      Eve   70.0  2019  unkown         6.0
6  unknown    0.0  2022      SF         NaN