# Handling Missing Values 

- Missing Values:

        df.isnull()
        df.notnull()
        df.hasnull()

        movies["year"].hasnull()

        df.dropna()  -->> drop missing ( nan ) values ( if in Df there is one missing value in row the Whole row raw is dropped )

        df.dropna(how="all") -->> now only those rows will drop that which filed with missing values
 
        df.fillna(value_to_replace_nan_with)  -->>

        df.fillna({"score": 0, "name": "unknown" , "city" : "unkown"})  -->> can also pass dictionary



- Always Check missing Values statistics:

        df.isna().sum()

- find percentage of missing Values in each col:

        (df.isna().sum() / len(df)) * 100

- drop rows with missing specific Cols:

        df.dropna(subset=["salary","age"])

- drop col when 60% missing for that set a threshold first:

        threshold = len(df) * 0.6

        df = df.dropna(axis=1, thresh=threshold)

- Fill Missing Values:

    - it depends on Datatype

            df["age"].fillna(df["age"].mean())  -->> for values use median/mean etc

            df["city"].fillna(df["city"].mode()[0]) -->> for catigorical use mode() ( most common values)


            df["review_text"].fillna("No review")  -->> for text use place holders

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("/home/aizen/AI_ML/7.Data_Analysis_and_Visualization/2_Pandas/missing_values_practice_dataset.csv")
df.head()

,employee_id,name,age,city,department,education,experience_years,salary,performance_score,projects_completed,hours_per_week,last_review_notes
0,1000,Bilal,26.0,Islamabad,Data,PhD,7.0,154826.0,77.21,13.0,43.0,model data data feature pipeline training
1,1001,Zara,32.0,Peshawar,AI,Bachelors,11.0,154881.0,87.03,NaN,57.0,analysis model model data pipeline analysis
2,1002,Ayesha,43.0,Quetta,Data,Masters,NaN,NaN,87.85,0.0,55.0,data analysis training model training pipeline...
3,1003,Usman,41.0,NaN,AI,PhD,6.0,125155.0,80.34,15.0,NaN,system system data model neural learning
4,1004,Bilal,30.0,Quetta,Backend,Bachelors,5.0,NaN,58.34,2.0,35.0,model data pipeline training system learning m...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         1200 non-null   int64
 1   name                1200 non-null   str
 2   age                 1051 non-null   float64
 3   city                1034 non-null   str
 4   department          1200 non-null   str
 5   education           1023 non-null   str
 6   experience_years    1063 non-null   float64
 7   salary              992 non-null    float64
 8   performance_score   1055 non-null   float64
 9   projects_completed  960 non-null    float64
 10  hours_per_week      1055 non-null   float64
 11  last_review_notes   1031 non-null   str
dtypes: float64(6), int64(1), str(5)
memory usage: 112.6 KB

In [ ]:
# Fiind Miisng Vale in Every Col
df.isnull().sum()

employee_id             0
name                    0
age                   149
city                  166
department              0
education             177
experience_years      137
salary                208
performance_score     145
projects_completed    240
hours_per_week        145
last_review_notes     169
dtype: int64

In [ ]:
# percentage of missig Value in eac col
(df.isnull().sum() / len(df)) * 100

employee_id            0.000000
name                   0.000000
age                   12.416667
city                  13.833333
department             0.000000
education             14.750000
experience_years      11.416667
salary                17.333333
performance_score     12.083333
projects_completed    20.000000
hours_per_week        12.083333
last_review_notes     14.083333
dtype: float64

In [ ]:
# Visualize missing Values
df.isnull().sum().sort_values(ascending = False)

projects_completed    240
salary                208
education             177
last_review_notes     169
city                  166
age                   149
performance_score     145
hours_per_week        145
experience_years      137
name                    0
employee_id             0
department              0
dtype: int64

In [ ]:
# Remove rows with missing Data 
# if one missing value whole row is dropped
df_clean = df.dropna()
df_clean.shape

(318, 12)

In [16]:
# fill missing Vales
df["age"].fillna(21)

0       26.0
1       32.0
2       43.0
3       41.0
4       30.0
        ...
1195    27.0
1196    38.0
1197    25.0
1198    40.0
1199    23.0
Name: age, Length: 1200, dtype: float64

In [18]:
df["age"] = df["age"].fillna(df["age"].mean())
df["age"]

0       26.0
1       32.0
2       43.0
3       41.0
4       30.0
        ...
1195    27.0
1196    38.0
1197    25.0
1198    40.0
1199    23.0
Name: age, Length: 1200, dtype: float64

In [20]:
df["city"].sample(10)

194     Islamabad
591           NaN
723      Peshawar
1018          NaN
667       Karachi
536           NaN
581       Karachi
118           NaN
93      Islamabad
374        Quetta
Name: city, dtype: str

In [27]:
# Remove rows only if salary is missing
df = df.dropna(subset=["salary"])

In [28]:
df["salary"] = df["salary"].fillna(df["salary"].median())

In [29]:
df["city"] = df["city"].fillna(df["city"].mode()[0])

In [30]:
df["last_review_notes"] = df["last_review_notes"].fillna("no review")

In [31]:
# Drop columns if >40% missing

threshold = len(df) * 0.4

df = df.dropna(axis = 1, thresh = threshold)

In [32]:
df.isnull().sum()

employee_id             0
name                    0
age                     0
city                    0
department              0
education             136
experience_years      112
salary                  0
performance_score     120
projects_completed    209
hours_per_week        116
last_review_notes       0
dtype: int64

In [33]:
# top 5 cols with missing values
df.isnull().sum().sort_values(ascending = False).head()

projects_completed    209
education             136
performance_score     120
hours_per_week        116
experience_years      112
dtype: int64

In [ ]:
# remove Rows where project_completed is missing -->> NAN

df = df.dropna(subset=["projects_completed"])

In [39]:
# Fill Missig Education with Mode
df["education"] = df["education"].fillna(df["education"].mode()[0])

In [40]:
# Fill Missing Perfromance using mean

df["performance_score"] = df["performance_score"].fillna(df["performance_score"].mean())

In [41]:
# fill missing Values in Experience with 0
df["experience_years"] = df["experience_years"].fillna(0)

In [42]:
df.isna().sum()

employee_id            0
name                   0
age                    0
city                   0
department             0
education              0
experience_years       0
salary                 0
performance_score      0
projects_completed     0
hours_per_week        95
last_review_notes      0
dtype: int64

In [44]:
df["hours_per_week"] = df["hours_per_week"].fillna(df["hours_per_week"].mean())

In [ ]:
df.isna().sum() # Handled all missing Values

employee_id           0
name                  0
age                   0
city                  0
department            0
education             0
experience_years      0
salary                0
performance_score     0
projects_completed    0
hours_per_week        0
last_review_notes     0
dtype: int64

In [46]:
df

,employee_id,name,age,city,department,education,experience_years,salary,performance_score,projects_completed,hours_per_week,last_review_notes
0,1000,Bilal,26.0,Islamabad,Data,PhD,7.0,154826.0,77.210000,13.0,43.000000,model data data feature pipeline training
3,1003,Usman,41.0,Peshawar,AI,PhD,6.0,125155.0,80.340000,15.0,44.944767,system system data model neural learning
5,1005,Fatima,42.0,Karachi,Backend,PhD,4.0,139246.0,89.870000,8.0,56.000000,system neural training learning system pipeline
6,1006,Ahmed,41.0,Peshawar,Frontend,Masters,9.0,134948.0,75.194416,3.0,55.000000,pipeline learning feature learning system pred...
7,1007,Bilal,26.0,Quetta,Data,Bachelors,7.0,61341.0,54.310000,4.0,33.000000,no review
...,...,...,...,...,...,...,...,...,...,...,...,...
1189,2189,Usman,25.0,Karachi,AI,PhD,1.0,90182.0,73.010000,11.0,44.944767,system feature analysis pipeline neural
1192,2192,Usman,40.0,Quetta,Frontend,Bachelors,7.0,53163.0,51.150000,19.0,47.000000,feature system pipeline system neural data dat...
1193,2193,Fatima,24.0,Karachi,ML,Masters,7.0,62419.0,94.840000,7.0,35.000000,learning data data system system data prediction
1198,2198,Ali,40.0,Peshawar,AI,Bachelors,9.0,42413.0,81.960000,4.0,32.000000,no review
1199,2199,Usman,23.0,Karachi,Data,Masters,6.0,49505.0,53.760000,19.0,36.000000,no review

# Generating A Dataset

In [48]:

import numpy as np
import random
from faker import Faker

fake = Faker()
np.random.seed(42)
random.seed(42)

n_rows = 1000

# Generate messy data
data = {
    "user_id": [fake.uuid4() for _ in range(n_rows)],
    "age": np.random.randint(18, 70, n_rows),
    "gender": np.random.choice(["Male", "Female", "male", "female", "M", "F", None], n_rows),
    "country": np.random.choice(["USA", "UK", "India", "Pakistan", None, "us", "UK"], n_rows),
    "signup_date": [fake.date_between(start_date="-5y", end_date="today") for _ in range(n_rows)],
    "last_login": [fake.date_between(start_date="-2y", end_date="today") for _ in range(n_rows)],
    "subscription_plan": np.random.choice(["Free", "Basic", "Premium", None], n_rows),
    "purchase_amount": np.random.choice([np.nan, *np.random.randint(0, 500, 10)], n_rows),
    "feedback_score": np.random.choice([1, 2, 3, 4, 5, None], n_rows),
    "referrer": np.random.choice([fake.name(), None, "Friend", "Google", "Ad", "ad"], n_rows),
    "notes": [fake.sentence(nb_words=6) if random.random() > 0.2 else None for _ in range(n_rows)],
    "irrelevant_col": np.random.rand(n_rows),
}

df = pd.DataFrame(data)

# Introduce some duplicates
df = pd.concat([df, df.sample(50)], ignore_index=True)

# Shuffle rows
df = df.sample(frac=1).reset_index(drop=True)

# Save the dataset for practice
df.to_csv("messy_dataset.csv", index=False)

print("Messy dataset generated with shape:", df.shape)
print(df.head(10))

Messy dataset generated with shape: (1050, 12)
                                user_id  age  gender   country signup_date  \
0  a8273311-8ddb-4daa-a2d2-a1c09710d82b   48    Male        UK  2025-06-13
1  38504e7d-68a3-4ed0-afb1-a616a4311363   30  female       USA  2021-11-02
2  39ffff26-5e29-425f-971c-5a318ba90273   43  Female        UK  2025-04-05
3  4543aaf9-2e48-49b9-88d0-cf858cebaa69   32    Male  Pakistan  2024-05-19
4  9e4bcf0d-4ed8-4ae6-a14e-4f0a7105694b   38     NaN     India  2023-01-23
5  ef6a19d3-b3e8-4d4a-80c6-5fdfc33bec84   26  female        UK  2021-08-31
6  f259e3dd-b5bc-4e26-a3b8-ce6989acfcf3   65    male  Pakistan  2023-12-28
7  dbb5b402-3f62-4dc3-990b-e73906c929bc   33    Male  Pakistan  2024-01-21
8  258cfc56-78c2-4c5c-9297-5ad434c0c23b   59    Male       NaN  2024-12-24
9  8ed86b64-f67f-4d96-b81d-65876fb51bbd   51       M       USA  2024-10-17

   last_login subscription_plan  purchase_amount feedback_score  \
0  2025-07-06              Free             20.0              5
1  2025-12-10           Premium             20.0              5
2  2025-05-12             Basic            405.0              2
3  2025-07-18             Basic            306.0              3
4  2024-07-12           Premium            146.0              2
5  2025-02-04           Premium             25.0              5
6  2024-08-16           Premium             92.0              4
7  2025-09-08               NaN            307.0              2
8  2024-07-08             Basic            146.0              2
9  2025-05-06              Free            307.0              4

        referrer                                              notes  \
0         Friend                 Front include meeting north plant.
1  Brandon Smith  Authority discuss them city interview weight s...
2             ad                               Short first perhaps.
3         Google             Enough degree seven eye modern debate.
4  Brandon Smith                         Born take throw what over.
5         Google           Live buy show factor gas design suggest.
6             Ad           Food instead boy support including note.
7         Google                                 Policy his threat.
8         Google                                                NaN
9             ad                                                NaN

   irrelevant_col
0        0.114237
1        0.407890
2        0.478159
3        0.242544
4        0.623519
5        0.014381
6        0.886288
7        0.445410
8        0.119107
9        0.542573

In [50]:
df1 = pd.read_csv("messy_dataset.csv")
df1

,user_id,age,gender,country,signup_date,last_login,subscription_plan,purchase_amount,feedback_score,referrer,notes,irrelevant_col
0,a8273311-8ddb-4daa-a2d2-a1c09710d82b,48,Male,UK,2025-06-13,2025-07-06,Free,20.0,5.0,Friend,Front include meeting north plant.,0.114237
1,38504e7d-68a3-4ed0-afb1-a616a4311363,30,female,USA,2021-11-02,2025-12-10,Premium,20.0,5.0,Brandon Smith,Authority discuss them city interview weight s...,0.407890
2,39ffff26-5e29-425f-971c-5a318ba90273,43,Female,UK,2025-04-05,2025-05-12,Basic,405.0,2.0,ad,Short first perhaps.,0.478159
3,4543aaf9-2e48-49b9-88d0-cf858cebaa69,32,Male,Pakistan,2024-05-19,2025-07-18,Basic,306.0,3.0,Google,Enough degree seven eye modern debate.,0.242544
4,9e4bcf0d-4ed8-4ae6-a14e-4f0a7105694b,38,NaN,India,2023-01-23,2024-07-12,Premium,146.0,2.0,Brandon Smith,Born take throw what over.,0.623519
...,...,...,...,...,...,...,...,...,...,...,...,...
1045,b12b3e60-5ce5-43de-a96c-e640d34cb0de,43,NaN,NaN,2025-04-27,2025-02-20,Free,275.0,2.0,ad,None miss shoulder cause national name none.,0.793129
1046,9ce02a3f-c6de-4ca5-9476-09df5e025b8b,49,NaN,NaN,2021-08-06,2026-03-07,Basic,275.0,5.0,Brandon Smith,Religious small government it foreign beyond a...,0.723072
1047,7eb080d2-9267-4b3e-9bfa-c5fca10b2eef,69,F,UK,2025-03-21,2024-05-07,Premium,146.0,NaN,Google,Relate operation tax wide outside.,0.014609
1048,211e9726-cdd7-4bc0-ac14-729f2c9ed67b,56,M,USA,2021-10-02,2025-02-01,NaN,NaN,2.0,Google,Least center dinner character chance.,0.255744
1049,f2a88de9-b468-4a69-9149-a3d3f6524dca,21,NaN,USA,2025-12-30,2025-11-23,Premium,231.0,5.0,ad,Manage some today walk.,0.451566

In [51]:
# missing Vales statistics

df1.isnull().sum()

user_id                0
age                    0
gender               145
country              154
signup_date            0
last_login             0
subscription_plan    292
purchase_amount      106
feedback_score       192
referrer             173
notes                187
irrelevant_col         0
dtype: int64

In [55]:
(df1.isnull().sum() / len(df1)) * 100

user_id               0.000000
age                   0.000000
gender               13.809524
country              14.666667
signup_date           0.000000
last_login            0.000000
subscription_plan    27.809524
purchase_amount      10.095238
feedback_score       18.285714
referrer             16.476190
notes                17.809524
irrelevant_col        0.000000
dtype: float64

In [ ]:
# drop all row where purchase_amount is missing

df1 = df1.dropna(subset=["purchase_amount"])

In [57]:
# Fill missing subscription_plan with "Free"
df1["subscription_plan"] = df1["subscription_plan"].fillna("Free")

In [58]:
# Fill missing Gender with Unknwon
df1["gender"]  = df1["gender"].fillna("unknown possibly Gay")

In [62]:
# Fill missing feedback_score with column median

df1["feedback_score"] = df1["feedback_score"].fillna(df1["feedback_score"].median())

In [64]:
# Fill missing country with "
df1['country'] = df1['country'].fillna('Unknown')

In [66]:
# Drop rows where both signup_date and last_login are missing
df1 = df1.dropna(subset=["signup_date", "last_login"], how= "all")

In [67]:
# Count Duplicate Rows

df1.duplicated().sum()

np.int64(47)

In [68]:
df1 = df1.drop_duplicates()

In [71]:
# Standardized Inconsistent ENtries

# Normalize gender column
df1["gender"] = df1["gender"].replace( 
    {
        'M': "Male",
        "F": "Female",
        "male": "Male",
        "female": "Female"
    }
)

df["gender"]

0         Male
1       female
2       Female
3         Male
4          NaN
         ...
1045       NaN
1046       NaN
1047         F
1048         M
1049       NaN
Name: gender, Length: 1050, dtype: str

In [72]:
df1.isnull().sum()

user_id                0
age                    0
gender                 0
country                0
signup_date            0
last_login             0
subscription_plan      0
purchase_amount        0
feedback_score         0
referrer             149
notes                155
irrelevant_col         0
dtype: int64